import { createContext, useContext, ReactNode, useState, useEffect } from 'react';

type Language = 'fr' | 'en' | 'it' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.plans': 'Tarifs',
    'nav.generateQr': 'Scanner QR',
    'nav.dashboard': 'Tableau de bord',
    'nav.contacts': 'Contacts',
    'nav.campaigns': 'Campagnes',
    'nav.templates': 'Modèles',
    'nav.login': 'Se connecter',
    'nav.logout': 'Se déconnecter',
    
    // Auth
    'auth.hello': 'Bonjour',
    'auth.loggedAs': 'Connecté en tant que',
    'auth.user': 'Utilisateur',
    'auth.loginSubtitle': 'Connectez-vous ou créez votre compte pour commencer',
    'auth.loginTab': 'Connexion',
    'auth.signupTab': 'Inscription',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.ownerName': 'Nom du Propriétaire',
    'auth.restaurantName': 'Nom du Restaurant',
    'auth.confirmPassword': 'Confirmer le Mot de Passe',
    'auth.emailPlaceholder': 'votre@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.namePlaceholder': 'Votre nom',
    'auth.restaurantPlaceholder': 'Nom de votre restaurant',
    'auth.loginButton': 'Se connecter',
    'auth.signupButton': 'Créer un compte',
    
    // Plans page
    'plans.badge': 'Système Premium de Marketing',
    'plans.title': 'Révolutionnez le Marketing de Votre Restaurant',
    'plans.subtitle': 'Capturez des contacts, construisez des relations et augmentez vos ventes avec notre plateforme complète de marketing digital pour restaurants.',
    'plans.whyChoose': 'Pourquoi choisir notre plateforme ?',
    'plans.captureMore': 'Capturez Plus de Clients',
    'plans.captureDesc': 'Transformez les visiteurs en contacts avec des QR codes stratégiques',
    'plans.directComm': 'Communication Directe',
    'plans.directCommDesc': 'Envoyez des campagnes personnalisées par SMS à vos clients',
    'plans.measurableResults': 'Résultats Mesurables',
    'plans.measurableDesc': 'Suivez les métriques et optimisez vos campagnes marketing',
    'plans.singlePlan': 'Plan Unique, Fonctionnalités Complètes',
    'plans.transformDesc': 'Tout ce dont vous avez besoin pour transformer votre restaurant',
    'plans.mostPopular': 'Le Plus Populaire',
    'plans.professional': 'Plan Professionnel',
    'plans.forRestaurants': 'Pour les restaurants qui veulent grandir',
    'plans.perMonth': '/mois',
    'plans.startNow': 'Commencer Maintenant',
    'plans.cancelAnytime': 'Annulez à tout moment • Support 24/7 • Pas de frais cachés',
    'plans.smartCollection': 'Collecte intelligente de contacts',
    'plans.smartCollectionDesc': 'Capturez automatiquement les informations clients via QR codes',
    'plans.targetedCampaigns': 'Campagnes ciblées',
    'plans.targetedCampaignsDesc': 'SMS et emails personnalisés basés sur les préférences',
    'plans.automation': 'Automatisation avancée',
    'plans.automationDesc': 'Séquences automatiques pour fidéliser vos clients',
    'plans.analytics': 'Analytics détaillées',
    'plans.analyticsDesc': 'Suivez les performances et optimisez vos résultats',
    'plans.templateLibrary': 'Bibliothèque de templates',
    'plans.templateLibraryDesc': 'Templates pré-conçus pour tous types de campagnes',
    'plans.support': 'Support premium',
    'plans.supportDesc': 'Assistance prioritaire et onboarding personnalisé',
    'plans.getStarted': 'Pour commencer',
    'plans.scanQr': 'Scannez des QR codes dans votre restaurant',
    'plans.collectContacts': 'Collectez les contacts de vos clients',
    'plans.createCampaigns': 'Créez des campagnes ciblées',
    'plans.trackResults': 'Suivez vos résultats en temps réel',

    // Home page
    'home.heroTitle': 'Révolutionnez le marketing de votre restaurant',
    'home.heroSubtitle': 'Capturez des contacts, créez des campagnes et augmentez vos ventes avec DopplerDine',
    'home.startFree': 'Commencer gratuitement',
    'home.learnMore': 'En savoir plus',
    'home.whyChoose': 'Pourquoi choisir DopplerDine ?',
    'home.feature1Title': 'Collecte de contacts intelligente',
    'home.feature1Desc': 'Transformez chaque visite en opportunité avec nos QR codes personnalisés',
    'home.feature2Title': 'Campagnes automatisées',
    'home.feature2Desc': 'Envoyez des messages personnalisés au bon moment',
    'home.feature3Title': 'Analytics avancées',
    'home.feature3Desc': 'Suivez et optimisez vos performances marketing',
    'home.howItWorks': 'Comment ça marche',
    'home.step1': 'Générez vos QR codes',
    'home.step1Desc': 'Créez des codes QR personnalisés pour vos tables et menus',
    'home.step2': 'Collectez les contacts',
    'home.step2Desc': 'Les clients scannent et partagent leurs informations',
    'home.step3': 'Lancez vos campagnes',
    'home.step3Desc': 'Envoyez des promotions ciblées via SMS et email',
    'home.step4': 'Analysez les résultats',
    'home.step4Desc': 'Optimisez vos campagnes avec des données précises',

    // Index page
    'index.welcome': 'Bienvenue sur DopplerDine',
    'index.description': 'La plateforme de marketing digital conçue spécialement pour les restaurants',
    'index.getStarted': 'Commencer',
    'index.viewPricing': 'Voir les tarifs',

    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.subtitle': 'Aperçu de votre entreprise et métriques de performance',
    'dashboard.overview': 'Aperçu',
    'dashboard.overviewTitle': 'Aperçu',
    'dashboard.overviewSubtitle': 'Tableau de bord principal de votre DopplerDine',
    'dashboard.scanQr': 'Scanner QR',
    'dashboard.newCampaign': 'Nouvelle Campagne',
    'dashboard.analytics': 'Analytics',
    
    // Dashboard KPIs
    'dashboard.totalContacts': 'Total Contacts',
    'dashboard.thisWeek': 'cette semaine',
    'dashboard.activeCampaigns': 'Campagnes Actives',
    'dashboard.total': 'total',
    'dashboard.conversionRate': 'Taux de Conversion',
    'dashboard.last30Days': 'Derniers 30 jours',
    'dashboard.uniqueQr': 'QR Unique',
    'dashboard.yourAccessCode': 'Votre code d\'accès',
    
    // Dashboard sections
    'dashboard.recentCampaigns': 'Campagnes Récentes',
    'dashboard.recentCampaignsDesc': 'Vos dernières campagnes marketing',
    'dashboard.recentContacts': 'Contacts Récents',
    'dashboard.recentContactsDesc': 'Nouveaux contacts ajoutés récemment',
    'dashboard.noCampaignsYet': 'Aucune campagne pour le moment',
    'dashboard.noContactsYet': 'Aucun contact pour le moment',
    
    // Quick Actions
    'dashboard.quickActions': 'Actions Rapides',
    'dashboard.quickActionsDesc': 'Raccourcis vers les fonctions principales',
    'dashboard.captureContact': 'Capturer Contact',
    'dashboard.captureContactDesc': 'Scanner un QR code pour ajouter un contact',
    'dashboard.newCampaignAction': 'Nouvelle Campagne',
    'dashboard.newCampaignDesc': 'Créer une campagne marketing',
    'dashboard.manageContacts': 'Gérer Contacts',
    'dashboard.manageContactsDesc': 'Voir et modifier vos contacts',
    
    // Campaign Status
    'campaign.status.draft': 'Brouillon',
    'campaign.status.scheduled': 'Programmé',
    'campaign.status.sending': 'Envoi en cours',
    'campaign.status.sent': 'Envoyé',
    'campaign.status.completed': 'Terminé',
    'campaign.status.failed': 'Échec',
    'campaign.status.active': 'Actif',

    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Acompanhe o desempenho das suas campanhas e contatos',
    'analytics.last7days': 'Derniers 7 jours',
    'analytics.last30days': 'Derniers 30 jours',
    'analytics.last90days': 'Derniers 90 jours',
    'analytics.lastYear': 'Dernière année',
    'analytics.refresh': 'Actualiser',
    'analytics.totalCampaigns': 'Total Campagnes',
    'analytics.totalContacts': 'Total Contacts',
    'analytics.messagesSent': 'Messages Envoyés',
    'analytics.totalCost': 'Coût Total',
    'analytics.selectedPeriod': 'Période sélectionnée',
    'analytics.newContactsAdded': 'Nouveaux contacts ajoutés',
    'analytics.successRate': 'Taux de succès',
    'analytics.campaignExpenses': 'Dépenses des campagnes',
    'analytics.sendTrend': 'Tendance d\'envoi',
    'analytics.sentVsDelivered': 'Envoyés vs Livrés',
    'analytics.sent': 'Envoyés',
    'analytics.delivered': 'Livrés',
    'analytics.campaignsByType': 'Campagnes par Type',
    'analytics.typeDistribution': 'Distribution par type',
    'analytics.campaignStatus': 'Statut des Campagnes',
    'analytics.currentState': 'État actuel',
    'analytics.recentActivity': 'Activité Récente',
    'analytics.lastActions': 'Dernières actions',
    'analytics.noActivity': 'Aucune activité récente',
    'analytics.campaign': 'Campagne',
    'analytics.contact': 'Contact',
    'analytics.performance': 'Performance',
    'analytics.detailedMetrics': 'Métriques détaillées',
    'analytics.deliveryRate': 'Taux de livraison',
    'analytics.costPerMessage': 'Coût par message',
    'analytics.messagesPerContact': 'Messages par contact',

    // Campaigns
    'campaigns.title': 'Campagnes',
    'campaigns.subtitle': 'Créez et gérez vos campagnes marketing',
    'campaigns.newCampaign': 'Nouvelle campagne',
    'campaigns.createNew': 'Créer une nouvelle campagne',
    'campaigns.configurePromo': 'Configurez votre campagne de promotion automatisée',
    'campaigns.templateOptional': 'Utiliser un template (optionnel)',
    'campaigns.chooseTemplate': 'Choisir un template existant',
    'campaigns.createFromScratch': 'Créer depuis zéro',
    'campaigns.campaignName': 'Nom de la campagne',
    'campaigns.campaignType': 'Type de campagne',
    'campaigns.selectType': 'Sélectionner un type',
    'campaigns.templateVariables': 'Variables du template',
    'campaigns.promoMessage': 'Message promotionnel',
    'campaigns.writeMessage': 'Rédigez votre message promotionnel...',
    'campaigns.charactersForSms': 'caractères pour SMS',
    'campaigns.previewVariables': 'Aperçu avec variables appliquées ci-dessous',
    'campaigns.finalMessage': 'Aperçu du message final:',
    'campaigns.scheduledAt': 'Date et heure d\'envoi (optionnel)',
    'campaigns.leaveEmpty': 'Laissez vide pour envoyer immédiatement',
    'campaigns.sendViaTwilio': 'Envoi via Twilio',
    'campaigns.twilioConfigured': 'Configuration du Twilio déjà configurée',
    'campaigns.creating': 'Création...',
    'campaigns.createCampaign': 'Créer la campagne',
    'campaigns.cancel': 'Annuler',
    'campaigns.myCampaigns': 'Mes campagnes',
    'campaigns.manageTrack': 'Gérez et suivez vos campagnes marketing',
    'campaigns.noCampaigns': 'Aucune campagne',
    'campaigns.createFirst': 'Créez votre première campagne pour commencer à engager vos clients.',
    'campaigns.error': 'Erreur',
    'campaigns.fillRequired': 'Veuillez remplir tous les champs obligatoires',
    'campaigns.success': 'Succès',
    'campaigns.created': 'Campagne créée avec succès',
    'campaigns.cannotCreate': 'Impossible de créer la campagne',
    'campaigns.sent': 'Campagne envoyée avec succès',
    'campaigns.cannotSend': 'Impossible d\'envoyer la campagne',
    'campaigns.deleted': 'Campagne supprimée avec succès',
    'campaigns.cannotDelete': 'Impossible de supprimer la campagne',

    // Contacts
    'contacts.title': 'Contacts',
    'contacts.subtitle': 'Gérez votre base de contacts client',
    'contacts.scanQr': 'Scanner QR',
    'contacts.newContact': 'Nouveau Contact',
    'contacts.total': 'Total',
    'contacts.viaQr': 'Via QR Code',
    'contacts.withEmail': 'Avec Email',
    'contacts.thisWeek': 'Cette Semaine',
    'contacts.searchPlaceholder': 'Chercher par nom, téléphone ou email...',
    'contacts.allSources': 'Toutes les sources',
    'contacts.manual': 'Manuel',
    'contacts.import': 'Importation',
    'contacts.export': 'Exporter',
    'contacts.noContacts': 'Aucun contact trouvé',
    'contacts.selectAll': 'Sélectionner tous',
    'contacts.unselectAll': 'Désélectionner tous',
    'contacts.addedOn': 'Ajouté le',
    'contacts.confirmDelete': 'Confirmer suppression',
    'contacts.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer le contact',
    'contacts.cannotUndo': 'Cette action ne peut pas être annulée.',
    'contacts.delete': 'Supprimer',
    'contacts.adjustFilters': 'Essayez d\'ajuster les filtres ou termes de recherche',
    'contacts.startScanning': 'Commencez en scannant des QR codes ou en ajoutant des contacts manuellement',
    'contacts.addContact': 'Ajouter Contact',

    // Templates
    'templates.title': 'Modèles',
    'templates.subtitle': 'Créez et gérez vos modèles de messages',
    'templates.newTemplate': 'Nouveau Modèle',
    'templates.totalTemplates': 'Total Modèles',
    'templates.categories': 'Catégories',
    'templates.mostUsed': 'Plus Utilisé',
    'templates.general': 'Général',
    'templates.none': 'Aucun',
    'templates.editTemplate': 'Modifier Modèle',
    'templates.createNewTemplate': 'Créer Nouveau Modèle',
    'templates.useVariables': 'Utilisez {{variable}} pour des contenus dynamiques',
    'templates.templateName': 'Nom du Modèle',
    'templates.templateNameExample': 'Ex: Promotion Lundi',
    'templates.category': 'Catégorie',
    'templates.selectCategory': 'Sélectionner une catégorie',
    'templates.templateMessage': 'Message du Modèle',
    'templates.messageExample': 'Bonjour {{nom}}, découvrez notre offre spéciale...',
    'templates.variablesDetected': 'Variables détectées:',
    'templates.modifying': 'Modification...',
    'templates.creating': 'Création...',
    'templates.modify': 'Modifier',
    'templates.create': 'Créer',
    'templates.myTemplates': 'Mes Modèles',
    'templates.manageTemplates': 'Gérez vos modèles de messages',
    'templates.noTemplates': 'Aucun modèle',
    'templates.createFirstTemplate': 'Créez votre premier modèle pour gagner du temps lors de la création de campagnes.',
    'templates.createTemplate': 'Créer Modèle',
    'templates.loadProTemplates': 'Charger Modèles Pro',
    'templates.variables': 'variables',
    'templates.variable': 'variable',
    'templates.copy': 'Copier',
    'templates.error': 'Erreur',
    'templates.fillRequired': 'Veuillez remplir tous les champs obligatoires',
    'templates.success': 'Succès',
    'templates.templateModified': 'Modèle modifié avec succès',
    'templates.templateCreated': 'Modèle créé avec succès',
    'templates.cannotSave': 'Impossible de sauvegarder le modèle',
    'templates.templateDeleted': 'Modèle supprimé avec succès',
    'templates.cannotDelete': 'Impossible de supprimer le modèle',
    'templates.copied': 'Copié',
    'templates.copiedToClipboard': 'Copié dans le presse-papiers',
    'templates.defaultTemplatesAdded': 'Modèles par défaut ajoutés avec succès',
    'templates.cannotLoadDefaults': 'Impossible de charger les modèles par défaut',

    // Template Categories
    'templateCategories.general': 'Général',
    'templateCategories.promotion': 'Promotion',
    'templateCategories.welcome': 'Bienvenue',
    'templateCategories.reminder': 'Rappel',
    'templateCategories.event': 'Événement',
    'templateCategories.special_offer': 'Offre Spéciale',
    'templateCategories.feedback': 'Commentaires',

    // QR Form
    'qrForm.title': 'Formulaire de Contact QR',
    'qrForm.fillForm': 'Remplissez ce formulaire pour recevoir nos offres exclusives',
    'qrForm.name': 'Nom complet',
    'qrForm.namePlaceholder': 'Votre nom complet',
    'qrForm.phone': 'Téléphone',
    'qrForm.phonePlaceholder': 'Votre numéro de téléphone',
    'qrForm.email': 'Email (optionnel)',
    'qrForm.emailPlaceholder': 'votre@email.com',
    'qrForm.submitButton': 'Recevoir les offres',
    'qrForm.submitting': 'Envoi...',
    'qrForm.successTitle': 'Merci !',
    'qrForm.successMessage': 'Vos informations ont été enregistrées avec succès. Vous recevrez bientôt nos meilleures offres !',
    'qrForm.errorTitle': 'Erreur',
    'qrForm.errorMessage': 'Une erreur est survenue. Veuillez réessayer.',
    'qrForm.fillRequired': 'Veuillez remplir tous les champs obligatoires',
    'qrForm.scanInstructions': 'Scannez le code QR avec votre téléphone pour accéder au formulaire de contact',
    'qrForm.qrCodeGenerated': 'Code QR généré avec succès',
    'qrForm.generateButton': 'Générer Code QR',
    'qrForm.downloadQr': 'Télécharger QR',
    'qrForm.printQr': 'Imprimer QR',
    'qrForm.newQr': 'Nouveau QR',
    'qrForm.qrTips': 'Conseils d\'utilisation:',
    'qrForm.tip1': 'Placez le QR code sur vos tables',
    'qrForm.tip2': 'Ajoutez-le à vos menus',
    'qrForm.tip3': 'Affichez-le à l\'entrée de votre restaurant',
    
    // QR Generator
    'qrGenerator.loadError': 'Impossible de charger le code QR',
    'qrGenerator.shareDescription': 'Partagez ce code QR pour que les clients laissent leurs données',
    'qrGenerator.directLink': 'Lien direct:',
    'qrGenerator.downloadQr': 'Télécharger QR',
    'qrGenerator.share': 'Partager',
    'qrGenerator.howToUse': 'Comment utiliser:',
    'qrGenerator.instruction1': '1. Imprimez ou montrez le code QR aux clients',
    'qrGenerator.instruction2': '2. Les clients scannent avec l\'appareil photo de leur téléphone',
    'qrGenerator.instruction3': '3. Ils remplissent le formulaire',
    'qrGenerator.instruction4': '4. Les données apparaissent automatiquement dans vos contacts',
    'qrGenerator.linkCopied': 'Lien copié!',
    'qrGenerator.linkCopiedDesc': 'Le lien du formulaire a été copié dans le presse-papiers.',
    'qrGenerator.loading': 'Chargement du code QR...',
    'qrGenerator.cannotGenerate': 'Impossible de générer le code QR.',

    // NotFound
    'notFound.title': 'Page non trouvée',
    'notFound.message': 'La page que vous recherchez n\'existe pas.',
    'notFound.backHome': 'Retour à l\'accueil',
  },
  
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.plans': 'Pricing',
    'nav.generateQr': 'Scan QR',
    'nav.dashboard': 'Dashboard',
    'nav.contacts': 'Contacts',
    'nav.campaigns': 'Campaigns',
    'nav.templates': 'Templates',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    
    // Auth
    'auth.hello': 'Hello',
    'auth.loggedAs': 'Logged in as',
    'auth.user': 'User',
    'auth.loginSubtitle': 'Log in or create your account to get started',
    'auth.loginTab': 'Login',
    'auth.signupTab': 'Sign Up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.ownerName': 'Owner Name',
    'auth.restaurantName': 'Restaurant Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.emailPlaceholder': 'your@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.namePlaceholder': 'Your name',
    'auth.restaurantPlaceholder': 'Your restaurant name',
    'auth.loginButton': 'Sign In',
    'auth.signupButton': 'Create Account',
    
    // Plans page
    'plans.badge': 'Premium Marketing System',
    'plans.title': 'Revolutionize Your Restaurant Marketing',
    'plans.subtitle': 'Capture contacts, build relationships and increase your sales with our complete digital marketing platform for restaurants.',
    'plans.whyChoose': 'Why choose our platform?',
    'plans.captureMore': 'Capture More Customers',
    'plans.captureDesc': 'Transform visitors into contacts with strategic QR codes',
    'plans.directComm': 'Direct Communication',
    'plans.directCommDesc': 'Send personalized SMS campaigns to your customers',
    'plans.measurableResults': 'Measurable Results',
    'plans.measurableDesc': 'Track metrics and optimize your marketing campaigns',
    'plans.singlePlan': 'Single Plan, Complete Features',
    'plans.transformDesc': 'Everything you need to transform your restaurant',
    'plans.mostPopular': 'Most Popular',
    'plans.professional': 'Professional Plan',
    'plans.forRestaurants': 'For restaurants that want to grow',
    'plans.perMonth': '/month',
    'plans.startNow': 'Start Now',
    'plans.cancelAnytime': 'Cancel anytime • 24/7 Support • No hidden fees',
    'plans.smartCollection': 'Smart contact collection',
    'plans.smartCollectionDesc': 'Automatically capture customer information via QR codes',
    'plans.targetedCampaigns': 'Targeted campaigns',
    'plans.targetedCampaignsDesc': 'Personalized SMS and emails based on preferences',
    'plans.automation': 'Advanced automation',
    'plans.automationDesc': 'Automated sequences to build customer loyalty',
    'plans.analytics': 'Detailed analytics',
    'plans.analyticsDesc': 'Track performance and optimize your results',
    'plans.templateLibrary': 'Template library',
    'plans.templateLibraryDesc': 'Pre-designed templates for all campaign types',
    'plans.support': 'Premium support',
    'plans.supportDesc': 'Priority assistance and personalized onboarding',
    'plans.getStarted': 'Get started',
    'plans.scanQr': 'Scan QR codes in your restaurant',
    'plans.collectContacts': 'Collect your customers\' contacts',
    'plans.createCampaigns': 'Create targeted campaigns',
    'plans.trackResults': 'Track your results in real time',

    // Home page
    'home.heroTitle': 'Revolutionize your restaurant marketing',
    'home.heroSubtitle': 'Capture contacts, create campaigns and increase your sales with DopplerDine',
    'home.startFree': 'Start for free',
    'home.learnMore': 'Learn more',
    'home.whyChoose': 'Why choose DopplerDine?',
    'home.feature1Title': 'Smart contact collection',
    'home.feature1Desc': 'Transform every visit into an opportunity with our custom QR codes',
    'home.feature2Title': 'Automated campaigns',
    'home.feature2Desc': 'Send personalized messages at the right time',
    'home.feature3Title': 'Advanced analytics',
    'home.feature3Desc': 'Track and optimize your marketing performance',
    'home.howItWorks': 'How it works',
    'home.step1': 'Generate your QR codes',
    'home.step1Desc': 'Create custom QR codes for your tables and menus',
    'home.step2': 'Collect contacts',
    'home.step2Desc': 'Customers scan and share their information',
    'home.step3': 'Launch your campaigns',
    'home.step3Desc': 'Send targeted promotions via SMS and email',
    'home.step4': 'Analyze results',
    'home.step4Desc': 'Optimize your campaigns with accurate data',

    // Index page
    'index.welcome': 'Welcome to DopplerDine',
    'index.description': 'The digital marketing platform designed specifically for restaurants',
    'index.getStarted': 'Get Started',
    'index.viewPricing': 'View Pricing',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of your business and performance metrics',
    'dashboard.overview': 'Overview',
    'dashboard.overviewTitle': 'Overview',
    'dashboard.overviewSubtitle': 'Main dashboard of your DopplerDine',
    'dashboard.scanQr': 'Scan QR',
    'dashboard.newCampaign': 'New Campaign',
    'dashboard.analytics': 'Analytics',
    
    // Dashboard KPIs
    'dashboard.totalContacts': 'Total Contacts',
    'dashboard.thisWeek': 'this week',
    'dashboard.activeCampaigns': 'Active Campaigns',
    'dashboard.total': 'total',
    'dashboard.conversionRate': 'Conversion Rate',
    'dashboard.last30Days': 'Last 30 days',
    'dashboard.uniqueQr': 'Unique QR',
    'dashboard.yourAccessCode': 'Your access code',
    
    // Dashboard sections
    'dashboard.recentCampaigns': 'Recent Campaigns',
    'dashboard.recentCampaignsDesc': 'Your latest marketing campaigns',
    'dashboard.recentContacts': 'Recent Contacts',
    'dashboard.recentContactsDesc': 'Recently added new contacts',
    'dashboard.noCampaignsYet': 'No campaigns yet',
    'dashboard.noContactsYet': 'No contacts yet',
    
    // Quick Actions
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.quickActionsDesc': 'Shortcuts to main functions',
    'dashboard.captureContact': 'Capture Contact',
    'dashboard.captureContactDesc': 'Scan a QR code to add a contact',
    'dashboard.newCampaignAction': 'New Campaign',
    'dashboard.newCampaignDesc': 'Create a marketing campaign',
    'dashboard.manageContacts': 'Manage Contacts',
    'dashboard.manageContactsDesc': 'View and edit your contacts',
    
    // Campaign Status
    'campaign.status.draft': 'Draft',
    'campaign.status.scheduled': 'Scheduled',
    'campaign.status.sending': 'Sending',
    'campaign.status.sent': 'Sent',
    'campaign.status.completed': 'Completed',
    'campaign.status.failed': 'Failed',
    'campaign.status.active': 'Active',

    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Track the performance of your campaigns and contacts',
    'analytics.last7days': 'Last 7 days',
    'analytics.last30days': 'Last 30 days',
    'analytics.last90days': 'Last 90 days',
    'analytics.lastYear': 'Last year',
    'analytics.refresh': 'Refresh',
    'analytics.totalCampaigns': 'Total Campaigns',
    'analytics.totalContacts': 'Total Contacts',
    'analytics.messagesSent': 'Messages Sent',
    'analytics.totalCost': 'Total Cost',
    'analytics.selectedPeriod': 'Selected period',
    'analytics.newContactsAdded': 'New contacts added',
    'analytics.successRate': 'Success rate',
    'analytics.campaignExpenses': 'Campaign expenses',
    'analytics.sendTrend': 'Send Trend',
    'analytics.sentVsDelivered': 'Sent vs Delivered',
    'analytics.sent': 'Sent',
    'analytics.delivered': 'Delivered',
    'analytics.campaignsByType': 'Campaigns by Type',
    'analytics.typeDistribution': 'Type distribution',
    'analytics.campaignStatus': 'Campaign Status',
    'analytics.currentState': 'Current state',
    'analytics.recentActivity': 'Recent Activity',
    'analytics.lastActions': 'Last actions',
    'analytics.noActivity': 'No recent activity',
    'analytics.campaign': 'Campaign',
    'analytics.contact': 'Contact',
    'analytics.performance': 'Performance',
    'analytics.detailedMetrics': 'Detailed metrics',
    'analytics.deliveryRate': 'Delivery rate',
    'analytics.costPerMessage': 'Cost per message',
    'analytics.messagesPerContact': 'Messages per contact',

    // Campaigns
    'campaigns.title': 'Campaigns',
    'campaigns.subtitle': 'Create and manage your marketing campaigns',
    'campaigns.newCampaign': 'New campaign',
    'campaigns.createNew': 'Create new campaign',
    'campaigns.configurePromo': 'Configure your automated promotion campaign',
    'campaigns.templateOptional': 'Use template (optional)',
    'campaigns.chooseTemplate': 'Choose existing template',
    'campaigns.createFromScratch': 'Create from scratch',
    'campaigns.campaignName': 'Campaign name',
    'campaigns.campaignType': 'Campaign type',
    'campaigns.selectType': 'Select type',
    'campaigns.templateVariables': 'Template variables',
    'campaigns.promoMessage': 'Promotional message',
    'campaigns.writeMessage': 'Write your promotional message...',
    'campaigns.charactersForSms': 'characters for SMS',
    'campaigns.previewVariables': 'Preview with variables applied below',
    'campaigns.finalMessage': 'Final message preview:',
    'campaigns.scheduledAt': 'Send date and time (optional)',
    'campaigns.leaveEmpty': 'Leave empty to send immediately',
    'campaigns.sendViaTwilio': 'Send via Twilio',
    'campaigns.twilioConfigured': 'Twilio configuration already set up',
    'campaigns.creating': 'Creating...',
    'campaigns.createCampaign': 'Create campaign',
    'campaigns.cancel': 'Cancel',
    'campaigns.myCampaigns': 'My campaigns',
    'campaigns.manageTrack': 'Manage and track your marketing campaigns',
    'campaigns.noCampaigns': 'No campaigns',
    'campaigns.createFirst': 'Create your first campaign to start engaging your customers.',
    'campaigns.error': 'Error',
    'campaigns.fillRequired': 'Please fill all required fields',
    'campaigns.success': 'Success',
    'campaigns.created': 'Campaign created successfully',
    'campaigns.cannotCreate': 'Cannot create campaign',
    'campaigns.sent': 'Campaign sent successfully',
    'campaigns.cannotSend': 'Cannot send campaign',
    'campaigns.deleted': 'Campaign deleted successfully',
    'campaigns.cannotDelete': 'Cannot delete campaign',

    // Contacts
    'contacts.title': 'Contacts',
    'contacts.subtitle': 'Manage your customer contact database',
    'contacts.scanQr': 'Scan QR',
    'contacts.newContact': 'New Contact',
    'contacts.total': 'Total',
    'contacts.viaQr': 'Via QR Code',
    'contacts.withEmail': 'With Email',
    'contacts.thisWeek': 'This Week',
    'contacts.searchPlaceholder': 'Search by name, phone or email...',
    'contacts.allSources': 'All sources',
    'contacts.manual': 'Manual',
    'contacts.import': 'Import',
    'contacts.export': 'Export',
    'contacts.noContacts': 'No contacts found',
    'contacts.selectAll': 'Select all',
    'contacts.unselectAll': 'Unselect all',
    'contacts.addedOn': 'Added on',
    'contacts.confirmDelete': 'Confirm deletion',
    'contacts.deleteConfirm': 'Are you sure you want to delete the contact',
    'contacts.cannotUndo': 'This action cannot be undone.',
    'contacts.delete': 'Delete',
    'contacts.adjustFilters': 'Try adjusting the filters or search terms',
    'contacts.startScanning': 'Start by scanning QR codes or adding contacts manually',
    'contacts.addContact': 'Add Contact',

    // Templates
    'templates.title': 'Templates',
    'templates.subtitle': 'Create and manage your message templates',
    'templates.newTemplate': 'New Template',
    'templates.totalTemplates': 'Total Templates',
    'templates.categories': 'Categories',
    'templates.mostUsed': 'Most Used',
    'templates.general': 'General',
    'templates.none': 'None',
    'templates.editTemplate': 'Edit Template',
    'templates.createNewTemplate': 'Create New Template',
    'templates.useVariables': 'Use {{variable}} for dynamic content',
    'templates.templateName': 'Template Name',
    'templates.templateNameExample': 'Ex: Monday Promotion',
    'templates.category': 'Category',
    'templates.selectCategory': 'Select category',
    'templates.templateMessage': 'Template Message',
    'templates.messageExample': 'Hello {{name}}, discover our special offer...',
    'templates.variablesDetected': 'Variables detected:',
    'templates.modifying': 'Modifying...',
    'templates.creating': 'Creating...',
    'templates.modify': 'Modify',
    'templates.create': 'Create',
    'templates.myTemplates': 'My Templates',
    'templates.manageTemplates': 'Manage your message templates',
    'templates.noTemplates': 'No templates',
    'templates.createFirstTemplate': 'Create your first template to save time when creating campaigns.',
    'templates.createTemplate': 'Create Template',
    'templates.loadProTemplates': 'Load Pro Templates',
    'templates.variables': 'variables',
    'templates.variable': 'variable',
    'templates.copy': 'Copy',
    'templates.error': 'Error',
    'templates.fillRequired': 'Please fill all required fields',
    'templates.success': 'Success',
    'templates.templateModified': 'Template modified successfully',
    'templates.templateCreated': 'Template created successfully',
    'templates.cannotSave': 'Cannot save template',
    'templates.templateDeleted': 'Template deleted successfully',
    'templates.cannotDelete': 'Cannot delete template',
    'templates.copied': 'Copied',
    'templates.copiedToClipboard': 'Copied to clipboard',
    'templates.defaultTemplatesAdded': 'Default templates added successfully',
    'templates.cannotLoadDefaults': 'Cannot load default templates',

    // Template Categories
    'templateCategories.general': 'General',
    'templateCategories.promotion': 'Promotion',
    'templateCategories.welcome': 'Welcome',
    'templateCategories.reminder': 'Reminder',
    'templateCategories.event': 'Event',
    'templateCategories.special_offer': 'Special Offer',
    'templateCategories.feedback': 'Feedback',

    // QR Form
    'qrForm.title': 'QR Contact Form',
    'qrForm.fillForm': 'Fill this form to receive our exclusive offers',
    'qrForm.name': 'Full name',
    'qrForm.namePlaceholder': 'Your full name',
    'qrForm.phone': 'Phone',
    'qrForm.phonePlaceholder': 'Your phone number',
    'qrForm.email': 'Email (optional)',
    'qrForm.emailPlaceholder': 'your@email.com',
    'qrForm.submitButton': 'Receive offers',
    'qrForm.submitting': 'Submitting...',
    'qrForm.successTitle': 'Thank you!',
    'qrForm.successMessage': 'Your information has been successfully saved. You will soon receive our best offers!',
    'qrForm.errorTitle': 'Error',
    'qrForm.errorMessage': 'An error occurred. Please try again.',
    'qrForm.fillRequired': 'Please fill all required fields',
    'qrForm.scanInstructions': 'Scan the QR code with your phone to access the contact form',
    'qrForm.qrCodeGenerated': 'QR code generated successfully',
    'qrForm.generateButton': 'Generate QR Code',
    'qrForm.downloadQr': 'Download QR',
    'qrForm.printQr': 'Print QR',
    'qrForm.newQr': 'New QR',
    'qrForm.qrTips': 'Usage tips:',
    'qrForm.tip1': 'Place the QR code on your tables',
    'qrForm.tip2': 'Add it to your menus',
    'qrForm.tip3': 'Display it at your restaurant entrance',
    
    // QR Generator
    'qrGenerator.loadError': 'Could not load QR code',
    'qrGenerator.shareDescription': 'Share this QR code so customers can leave their data',
    'qrGenerator.directLink': 'Direct link:',
    'qrGenerator.downloadQr': 'Download QR',
    'qrGenerator.share': 'Share',
    'qrGenerator.howToUse': 'How to use:',
    'qrGenerator.instruction1': '1. Print or show the QR code to customers',
    'qrGenerator.instruction2': '2. Customers scan with their phone camera',
    'qrGenerator.instruction3': '3. They fill out the form',
    'qrGenerator.instruction4': '4. Data automatically appears in your contacts',
    'qrGenerator.linkCopied': 'Link copied!',
    'qrGenerator.linkCopiedDesc': 'The form link has been copied to clipboard.',
    'qrGenerator.loading': 'Loading QR code...',
    'qrGenerator.cannotGenerate': 'Could not generate QR code.',

    // NotFound
    'notFound.title': 'Page not found',
    'notFound.message': 'The page you are looking for does not exist.',
    'notFound.backHome': 'Back to home',
  },
  
  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.plans': 'Prezzi',
    'nav.generateQr': 'Scansiona QR',
    'nav.dashboard': 'Dashboard',
    'nav.contacts': 'Contatti',
    'nav.campaigns': 'Campagne',
    'nav.templates': 'Modelli',
    'nav.login': 'Accedi',
    'nav.logout': 'Esci',
    
    // Auth
    'auth.hello': 'Ciao',
    'auth.loggedAs': 'Connesso come',
    'auth.user': 'Utente',
    'auth.loginSubtitle': 'Accedi o crea il tuo account per iniziare',
    'auth.loginTab': 'Accesso',
    'auth.signupTab': 'Registrazione',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.ownerName': 'Nome del Proprietario',
    'auth.restaurantName': 'Nome del Ristorante',
    'auth.confirmPassword': 'Conferma Password',
    'auth.emailPlaceholder': 'tua@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.namePlaceholder': 'Il tuo nome',
    'auth.restaurantPlaceholder': 'Nome del tuo ristorante',
    'auth.loginButton': 'Accedi',
    'auth.signupButton': 'Crea Account',
    
    // Plans page
    'plans.badge': 'Sistema di Marketing Premium',
    'plans.title': 'Rivoluziona il Marketing del Tuo Ristorante',
    'plans.subtitle': 'Cattura contatti, costruisci relazioni e aumenta le tue vendite con la nostra piattaforma completa di marketing digitale per ristoranti.',
    'plans.whyChoose': 'Perché scegliere la nostra piattaforma?',
    'plans.captureMore': 'Cattura Più Clienti',
    'plans.captureDesc': 'Trasforma i visitatori in contatti con codici QR strategici',
    'plans.directComm': 'Comunicazione Diretta',
    'plans.directCommDesc': 'Invia campagne SMS personalizzate ai tuoi clienti',
    'plans.measurableResults': 'Risultati Misurabili',
    'plans.measurableDesc': 'Traccia le metriche e ottimizza le tue campagne marketing',
    'plans.singlePlan': 'Piano Unico, Funzionalità Complete',
    'plans.transformDesc': 'Tutto quello che serve per trasformare il tuo ristorante',
    'plans.mostPopular': 'Più Popolare',
    'plans.professional': 'Piano Professionale',
    'plans.forRestaurants': 'Per ristoranti che vogliono crescere',
    'plans.perMonth': '/mese',
    'plans.startNow': 'Inizia Ora',
    'plans.cancelAnytime': 'Cancella in qualsiasi momento • Supporto 24/7 • Nessun costo nascosto',
    'plans.smartCollection': 'Raccolta intelligente di contatti',
    'plans.smartCollectionDesc': 'Cattura automaticamente le informazioni dei clienti tramite codici QR',
    'plans.targetedCampaigns': 'Campagne mirate',
    'plans.targetedCampaignsDesc': 'SMS ed email personalizzati basati sulle preferenze',
    'plans.automation': 'Automazione avanzata',
    'plans.automationDesc': 'Sequenze automatiche per fidelizzare i clienti',
    'plans.analytics': 'Analytics dettagliate',
    'plans.analyticsDesc': 'Traccia le prestazioni e ottimizza i risultati',
    'plans.templateLibrary': 'Libreria di template',
    'plans.templateLibraryDesc': 'Template predisegnati per tutti i tipi di campagne',
    'plans.support': 'Supporto premium',
    'plans.supportDesc': 'Assistenza prioritaria e onboarding personalizzato',
    'plans.getStarted': 'Per iniziare',
    'plans.scanQr': 'Scansiona codici QR nel tuo ristorante',
    'plans.collectContacts': 'Raccogli i contatti dei tuoi clienti',
    'plans.createCampaigns': 'Crea campagne mirate',
    'plans.trackResults': 'Traccia i tuoi risultati in tempo reale',

    // Home page
    'home.heroTitle': 'Rivoluziona il marketing del tuo ristorante',
    'home.heroSubtitle': 'Cattura contatti, crea campagne e aumenta le vendite con DopplerDine',
    'home.startFree': 'Inizia gratis',
    'home.learnMore': 'Scopri di più',
    'home.whyChoose': 'Perché scegliere DopplerDine?',
    'home.feature1Title': 'Raccolta intelligente di contatti',
    'home.feature1Desc': 'Trasforma ogni visita in un\'opportunità con i nostri codici QR personalizzati',
    'home.feature2Title': 'Campagne automatizzate',
    'home.feature2Desc': 'Invia messaggi personalizzati al momento giusto',
    'home.feature3Title': 'Analytics avanzate',
    'home.feature3Desc': 'Traccia e ottimizza le tue prestazioni marketing',
    'home.howItWorks': 'Come funziona',
    'home.step1': 'Genera i tuoi codici QR',
    'home.step1Desc': 'Crea codici QR personalizzati per i tuoi tavoli e menu',
    'home.step2': 'Raccogli contatti',
    'home.step2Desc': 'I clienti scansionano e condividono le loro informazioni',
    'home.step3': 'Lancia le tue campagne',
    'home.step3Desc': 'Invia promozioni mirate via SMS ed email',
    'home.step4': 'Analizza i risultati',
    'home.step4Desc': 'Ottimizza le tue campagne con dati precisi',

    // Index page
    'index.welcome': 'Benvenuto su DopplerDine',
    'index.description': 'La piattaforma di marketing digitale progettata specificamente per i ristoranti',
    'index.getStarted': 'Inizia',
    'index.viewPricing': 'Visualizza Prezzi',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Panoramica della tua attività e metriche di performance',
    'dashboard.overview': 'Panoramica',
    'dashboard.overviewTitle': 'Panoramica',
    'dashboard.overviewSubtitle': 'Dashboard principale del tuo DopplerDine',
    'dashboard.scanQr': 'Scansiona QR',
    'dashboard.newCampaign': 'Nuova Campagna',
    'dashboard.analytics': 'Analytics',
    
    // Dashboard KPIs
    'dashboard.totalContacts': 'Contatti Totali',
    'dashboard.thisWeek': 'questa settimana',
    'dashboard.activeCampaigns': 'Campagne Attive',
    'dashboard.total': 'totale',
    'dashboard.conversionRate': 'Tasso di Conversione',
    'dashboard.last30Days': 'Ultimi 30 giorni',
    'dashboard.uniqueQr': 'QR Unico',
    'dashboard.yourAccessCode': 'Il tuo codice di accesso',
    
    // Dashboard sections
    'dashboard.recentCampaigns': 'Campagne Recenti',
    'dashboard.recentCampaignsDesc': 'Le tue ultime campagne marketing',
    'dashboard.recentContacts': 'Contatti Recenti',
    'dashboard.recentContactsDesc': 'Nuovi contatti aggiunti di recente',
    'dashboard.noCampaignsYet': 'Nessuna campagna ancora',
    'dashboard.noContactsYet': 'Nessun contatto ancora',
    
    // Quick Actions
    'dashboard.quickActions': 'Azioni Rapide',
    'dashboard.quickActionsDesc': 'Scorciatoie alle funzioni principali',
    'dashboard.captureContact': 'Cattura Contatto',
    'dashboard.captureContactDesc': 'Scansiona un codice QR per aggiungere un contatto',
    'dashboard.newCampaignAction': 'Nuova Campagna',
    'dashboard.newCampaignDesc': 'Crea una campagna marketing',
    'dashboard.manageContacts': 'Gestisci Contatti',
    'dashboard.manageContactsDesc': 'Visualizza e modifica i tuoi contatti',
    
    // Campaign Status
    'campaign.status.draft': 'Bozza',
    'campaign.status.scheduled': 'Programmato',
    'campaign.status.sending': 'Invio in corso',
    'campaign.status.sent': 'Inviato',
    'campaign.status.completed': 'Completato',
    'campaign.status.failed': 'Fallito',
    'campaign.status.active': 'Attivo',

    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Monitora le prestazioni delle tue campagne e contatti',
    'analytics.last7days': 'Ultimi 7 giorni',
    'analytics.last30days': 'Ultimi 30 giorni',
    'analytics.last90days': 'Ultimi 90 giorni',
    'analytics.lastYear': 'Ultimo anno',
    'analytics.refresh': 'Aggiorna',
    'analytics.totalCampaigns': 'Campagne Totali',
    'analytics.totalContacts': 'Contatti Totali',
    'analytics.messagesSent': 'Messaggi Inviati',
    'analytics.totalCost': 'Costo Totale',
    'analytics.selectedPeriod': 'Periodo selezionato',
    'analytics.newContactsAdded': 'Nuovi contatti aggiunti',
    'analytics.successRate': 'Tasso di successo',
    'analytics.campaignExpenses': 'Spese campagne',
    'analytics.sendTrend': 'Tendenza Invio',
    'analytics.sentVsDelivered': 'Inviati vs Consegnati',
    'analytics.sent': 'Inviati',
    'analytics.delivered': 'Consegnati',
    'analytics.campaignsByType': 'Campagne per Tipo',
    'analytics.typeDistribution': 'Distribuzione per tipo',
    'analytics.campaignStatus': 'Stato Campagne',
    'analytics.currentState': 'Stato attuale',
    'analytics.recentActivity': 'Attività Recente',
    'analytics.lastActions': 'Ultime azioni',
    'analytics.noActivity': 'Nessuna attività recente',
    'analytics.campaign': 'Campagna',
    'analytics.contact': 'Contatto',
    'analytics.performance': 'Performance',
    'analytics.detailedMetrics': 'Metriche dettagliate',
    'analytics.deliveryRate': 'Tasso di consegna',
    'analytics.costPerMessage': 'Costo per messaggio',
    'analytics.messagesPerContact': 'Messaggi per contatto',

    // Campaigns
    'campaigns.title': 'Campagne',
    'campaigns.subtitle': 'Crea e gestisci le tue campagne marketing',
    'campaigns.newCampaign': 'Nuova campagna',
    'campaigns.createNew': 'Crea nuova campagna',
    'campaigns.configurePromo': 'Configura la tua campagna promozionale automatizzata',
    'campaigns.templateOptional': 'Usa template (opzionale)',
    'campaigns.chooseTemplate': 'Scegli template esistente',
    'campaigns.createFromScratch': 'Crea da zero',
    'campaigns.campaignName': 'Nome campagna',
    'campaigns.campaignType': 'Tipo di campagna',
    'campaigns.selectType': 'Seleziona tipo',
    'campaigns.templateVariables': 'Variabili template',
    'campaigns.promoMessage': 'Messaggio promozionale',
    'campaigns.writeMessage': 'Scrivi il tuo messaggio promozionale...',
    'campaigns.charactersForSms': 'caratteri per SMS',
    'campaigns.previewVariables': 'Anteprima con variabili applicate sotto',
    'campaigns.finalMessage': 'Anteprima messaggio finale:',
    'campaigns.scheduledAt': 'Data e ora invio (opzionale)',
    'campaigns.leaveEmpty': 'Lascia vuoto per inviare immediatamente',
    'campaigns.sendViaTwilio': 'Invio via Twilio',
    'campaigns.twilioConfigured': 'Configurazione Twilio già impostata',
    'campaigns.creating': 'Creazione...',
    'campaigns.createCampaign': 'Crea campagna',
    'campaigns.cancel': 'Annulla',
    'campaigns.myCampaigns': 'Le mie campagne',
    'campaigns.manageTrack': 'Gestisci e monitora le tue campagne marketing',
    'campaigns.noCampaigns': 'Nessuna campagna',
    'campaigns.createFirst': 'Crea la tua prima campagna per iniziare a coinvolgere i tuoi clienti.',
    'campaigns.error': 'Errore',
    'campaigns.fillRequired': 'Compila tutti i campi obbligatori',
    'campaigns.success': 'Successo',
    'campaigns.created': 'Campagna creata con successo',
    'campaigns.cannotCreate': 'Impossibile creare la campagna',
    'campaigns.sent': 'Campagna inviata con successo',
    'campaigns.cannotSend': 'Impossibile inviare la campagna',
    'campaigns.deleted': 'Campagna eliminata con successo',
    'campaigns.cannotDelete': 'Impossibile eliminare la campagna',

    // Contacts
    'contacts.title': 'Contatti',
    'contacts.subtitle': 'Gestisci il tuo database di contatti clienti',
    'contacts.scanQr': 'Scansiona QR',
    'contacts.newContact': 'Nuovo Contatto',
    'contacts.total': 'Totale',
    'contacts.viaQr': 'Via Codice QR',
    'contacts.withEmail': 'Con Email',
    'contacts.thisWeek': 'Questa Settimana',
    'contacts.searchPlaceholder': 'Cerca per nome, telefono o email...',
    'contacts.allSources': 'Tutte le fonti',
    'contacts.manual': 'Manuale',
    'contacts.import': 'Importazione',
    'contacts.export': 'Esporta',
    'contacts.noContacts': 'Nessun contatto trovato',
    'contacts.selectAll': 'Seleziona tutti',
    'contacts.unselectAll': 'Deseleziona tutti',
    'contacts.addedOn': 'Aggiunto il',
    'contacts.confirmDelete': 'Conferma eliminazione',
    'contacts.deleteConfirm': 'Sei sicuro di voler eliminare il contatto',
    'contacts.cannotUndo': 'Questa azione non può essere annullata.',
    'contacts.delete': 'Elimina',
    'contacts.adjustFilters': 'Prova ad aggiustare i filtri o termini di ricerca',
    'contacts.startScanning': 'Inizia scansionando codici QR o aggiungendo contatti manualmente',
    'contacts.addContact': 'Aggiungi Contatto',

    // Templates
    'templates.title': 'Modelli',
    'templates.subtitle': 'Crea e gestisci i tuoi modelli di messaggi',
    'templates.newTemplate': 'Nuovo Modello',
    'templates.totalTemplates': 'Modelli Totali',
    'templates.categories': 'Categorie',
    'templates.mostUsed': 'Più Usato',
    'templates.general': 'Generale',
    'templates.none': 'Nessuno',
    'templates.editTemplate': 'Modifica Modello',
    'templates.createNewTemplate': 'Crea Nuovo Modello',
    'templates.useVariables': 'Usa {{variabile}} per contenuto dinamico',
    'templates.templateName': 'Nome Modello',
    'templates.templateNameExample': 'Es: Promozione Lunedì',
    'templates.category': 'Categoria',
    'templates.selectCategory': 'Seleziona categoria',
    'templates.templateMessage': 'Messaggio Modello',
    'templates.messageExample': 'Ciao {{nome}}, scopri la nostra offerta speciale...',
    'templates.variablesDetected': 'Variabili rilevate:',
    'templates.modifying': 'Modifica...',
    'templates.creating': 'Creazione...',
    'templates.modify': 'Modifica',
    'templates.create': 'Crea',
    'templates.myTemplates': 'I Miei Modelli',
    'templates.manageTemplates': 'Gestisci i tuoi modelli di messaggi',
    'templates.noTemplates': 'Nessun modello',
    'templates.createFirstTemplate': 'Crea il tuo primo modello per risparmiare tempo nella creazione di campagne.',
    'templates.createTemplate': 'Crea Modello',
    'templates.loadProTemplates': 'Carica Modelli Pro',
    'templates.variables': 'variabili',
    'templates.variable': 'variabile',
    'templates.copy': 'Copia',
    'templates.error': 'Errore',
    'templates.fillRequired': 'Compila tutti i campi obbligatori',
    'templates.success': 'Successo',
    'templates.templateModified': 'Modello modificato con successo',
    'templates.templateCreated': 'Modello creato con successo',
    'templates.cannotSave': 'Impossibile salvare il modello',
    'templates.templateDeleted': 'Modello eliminato con successo',
    'templates.cannotDelete': 'Impossibile eliminare il modello',
    'templates.copied': 'Copiato',
    'templates.copiedToClipboard': 'Copiato negli appunti',
    'templates.defaultTemplatesAdded': 'Modelli predefiniti aggiunti con successo',
    'templates.cannotLoadDefaults': 'Impossibile caricare i modelli predefiniti',

    // Template Categories
    'templateCategories.general': 'Generale',
    'templateCategories.promotion': 'Promozione',
    'templateCategories.welcome': 'Benvenuto',
    'templateCategories.reminder': 'Promemoria',
    'templateCategories.event': 'Evento',
    'templateCategories.special_offer': 'Offerta Speciale',
    'templateCategories.feedback': 'Feedback',

    // QR Form
    'qrForm.title': 'Modulo Contatto QR',
    'qrForm.fillForm': 'Compila questo modulo per ricevere le nostre offerte esclusive',
    'qrForm.name': 'Nome completo',
    'qrForm.namePlaceholder': 'Il tuo nome completo',
    'qrForm.phone': 'Telefono',
    'qrForm.phonePlaceholder': 'Il tuo numero di telefono',
    'qrForm.email': 'Email (opzionale)',
    'qrForm.emailPlaceholder': 'tua@email.com',
    'qrForm.submitButton': 'Ricevi offerte',
    'qrForm.submitting': 'Invio...',
    'qrForm.successTitle': 'Grazie!',
    'qrForm.successMessage': 'Le tue informazioni sono state salvate con successo. Riceverai presto le nostre migliori offerte!',
    'qrForm.errorTitle': 'Errore',
    'qrForm.errorMessage': 'Si è verificato un errore. Riprova.',
    'qrForm.fillRequired': 'Compila tutti i campi obbligatori',
    'qrForm.scanInstructions': 'Scansiona il codice QR con il tuo telefono per accedere al modulo di contatto',
    'qrForm.qrCodeGenerated': 'Codice QR generato con successo',
    'qrForm.generateButton': 'Genera Codice QR',
    'qrForm.downloadQr': 'Scarica QR',
    'qrForm.printQr': 'Stampa QR',
    'qrForm.newQr': 'Nuovo QR',
    'qrForm.qrTips': 'Consigli di utilizzo:',
    'qrForm.tip1': 'Posiziona il codice QR sui tuoi tavoli',
    'qrForm.tip2': 'Aggiungilo ai tuoi menu',
    'qrForm.tip3': 'Mostralo all\'ingresso del tuo ristorante',
    
    // QR Generator
    'qrGenerator.loadError': 'Impossibile caricare il codice QR',
    'qrGenerator.shareDescription': 'Condividi questo codice QR perché i clienti possano lasciare i loro dati',
    'qrGenerator.directLink': 'Link diretto:',
    'qrGenerator.downloadQr': 'Scarica QR',
    'qrGenerator.share': 'Condividi',
    'qrGenerator.howToUse': 'Come usare:',
    'qrGenerator.instruction1': '1. Stampa o mostra il codice QR ai clienti',
    'qrGenerator.instruction2': '2. I clienti scansionano con la fotocamera del telefono',
    'qrGenerator.instruction3': '3. Compilano il modulo',
    'qrGenerator.instruction4': '4. I dati appaiono automaticamente nei tuoi contatti',
    'qrGenerator.linkCopied': 'Link copiato!',
    'qrGenerator.linkCopiedDesc': 'Il link del modulo è stato copiato negli appunti.',
    'qrGenerator.loading': 'Caricamento codice QR...',
    'qrGenerator.cannotGenerate': 'Impossibile generare il codice QR.',

    // NotFound
    'notFound.title': 'Pagina non trovata',
    'notFound.message': 'La pagina che stai cercando non esiste.',
    'notFound.backHome': 'Torna alla home',
  },
  
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.plans': 'Preise',
    'nav.generateQr': 'QR scannen',
    'nav.dashboard': 'Dashboard',
    'nav.contacts': 'Kontakte',
    'nav.campaigns': 'Kampagnen',
    'nav.templates': 'Vorlagen',
    'nav.login': 'Anmelden',
    'nav.logout': 'Abmelden',
    
    // Auth
    'auth.hello': 'Hallo',
    'auth.loggedAs': 'Angemeldet als',
    'auth.user': 'Benutzer',
    'auth.loginSubtitle': 'Melden Sie sich an oder erstellen Sie Ihr Konto, um zu beginnen',
    'auth.loginTab': 'Anmelden',
    'auth.signupTab': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.ownerName': 'Name des Inhabers',
    'auth.restaurantName': 'Name des Restaurants',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.emailPlaceholder': 'ihre@email.com',
    'auth.passwordPlaceholder': '••••••••',
    'auth.namePlaceholder': 'Ihr Name',
    'auth.restaurantPlaceholder': 'Name Ihres Restaurants',
    'auth.loginButton': 'Anmelden',
    'auth.signupButton': 'Konto erstellen',
    
    // Plans page
    'plans.badge': 'Premium Marketing System',
    'plans.title': 'Revolutionieren Sie Ihr Restaurant Marketing',
    'plans.subtitle': 'Erfassen Sie Kontakte, bauen Sie Beziehungen auf und steigern Sie Ihre Verkäufe mit unserer kompletten digitalen Marketing-Plattform für Restaurants.',
    'plans.whyChoose': 'Warum unsere Plattform wählen?',
    'plans.captureMore': 'Mehr Kunden erfassen',
    'plans.captureDesc': 'Verwandeln Sie Besucher in Kontakte mit strategischen QR-Codes',
    'plans.directComm': 'Direkte Kommunikation',
    'plans.directCommDesc': 'Senden Sie personalisierte SMS-Kampagnen an Ihre Kunden',
    'plans.measurableResults': 'Messbare Ergebnisse',
    'plans.measurableDesc': 'Verfolgen Sie Metriken und optimieren Sie Ihre Marketing-Kampagnen',
    'plans.singlePlan': 'Ein Plan, Vollständige Features',
    'plans.transformDesc': 'Alles was Sie brauchen, um Ihr Restaurant zu transformieren',
    'plans.mostPopular': 'Am Beliebtesten',
    'plans.professional': 'Professioneller Plan',
    'plans.forRestaurants': 'Für Restaurants, die wachsen wollen',
    'plans.perMonth': '/Monat',
    'plans.startNow': 'Jetzt Starten',
    'plans.cancelAnytime': 'Jederzeit kündbar • 24/7 Support • Keine versteckten Gebühren',
    'plans.smartCollection': 'Intelligente Kontaktsammlung',
    'plans.smartCollectionDesc': 'Erfassen Sie automatisch Kundeninformationen über QR-Codes',
    'plans.targetedCampaigns': 'Gezielte Kampagnen',
    'plans.targetedCampaignsDesc': 'Personalisierte SMS und E-Mails basierend auf Präferenzen',
    'plans.automation': 'Erweiterte Automatisierung',
    'plans.automationDesc': 'Automatische Sequenzen zur Kundenbindung',
    'plans.analytics': 'Detaillierte Analytics',
    'plans.analyticsDesc': 'Verfolgen Sie die Leistung und optimieren Sie Ihre Ergebnisse',
    'plans.templateLibrary': 'Vorlagenbibliothek',
    'plans.templateLibraryDesc': 'Vorgefertigte Vorlagen für alle Kampagnentypen',
    'plans.support': 'Premium Support',
    'plans.supportDesc': 'Prioritätshilfe und personalisiertes Onboarding',
    'plans.getStarted': 'Erste Schritte',
    'plans.scanQr': 'Scannen Sie QR-Codes in Ihrem Restaurant',
    'plans.collectContacts': 'Sammeln Sie die Kontakte Ihrer Kunden',
    'plans.createCampaigns': 'Erstellen Sie gezielte Kampagnen',
    'plans.trackResults': 'Verfolgen Sie Ihre Ergebnisse in Echtzeit',

    // Home page
    'home.heroTitle': 'Revolutionieren Sie Ihr Restaurant Marketing',
    'home.heroSubtitle': 'Erfassen Sie Kontakte, erstellen Sie Kampagnen und steigern Sie Ihre Verkäufe mit DopplerDine',
    'home.startFree': 'Kostenlos starten',
    'home.learnMore': 'Mehr erfahren',
    'home.whyChoose': 'Warum DopplerDine wählen?',
    'home.feature1Title': 'Intelligente Kontaktsammlung',
    'home.feature1Desc': 'Verwandeln Sie jeden Besuch in eine Gelegenheit mit unseren benutzerdefinierten QR-Codes',
    'home.feature2Title': 'Automatisierte Kampagnen',
    'home.feature2Desc': 'Senden Sie personalisierte Nachrichten zum richtigen Zeitpunkt',
    'home.feature3Title': 'Erweiterte Analytics',
    'home.feature3Desc': 'Verfolgen und optimieren Sie Ihre Marketing-Performance',
    'home.howItWorks': 'Wie es funktioniert',
    'home.step1': 'Generieren Sie Ihre QR-Codes',
    'home.step1Desc': 'Erstellen Sie benutzerdefinierte QR-Codes für Ihre Tische und Menüs',
    'home.step2': 'Kontakte sammeln',
    'home.step2Desc': 'Kunden scannen und teilen ihre Informationen',
    'home.step3': 'Starten Sie Ihre Kampagnen',
    'home.step3Desc': 'Senden Sie gezielte Promotionen per SMS und E-Mail',
    'home.step4': 'Ergebnisse analysieren',
    'home.step4Desc': 'Optimieren Sie Ihre Kampagnen mit präzisen Daten',

    // Index page
    'index.welcome': 'Willkommen bei DopplerDine',
    'index.description': 'Die digitale Marketing-Plattform speziell für Restaurants entwickelt',
    'index.getStarted': 'Loslegen',
    'index.viewPricing': 'Preise ansehen',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Überblick über Ihr Unternehmen und Leistungsmetriken',
    'dashboard.overview': 'Überblick',
    'dashboard.overviewTitle': 'Überblick',
    'dashboard.overviewSubtitle': 'Haupt-Dashboard Ihres DopplerDine',
    'dashboard.scanQr': 'QR scannen',
    'dashboard.newCampaign': 'Neue Kampagne',
    'dashboard.analytics': 'Analytics',
    
    // Dashboard KPIs
    'dashboard.totalContacts': 'Kontakte Gesamt',
    'dashboard.thisWeek': 'diese Woche',
    'dashboard.activeCampaigns': 'Aktive Kampagnen',
    'dashboard.total': 'gesamt',
    'dashboard.conversionRate': 'Konversionsrate',
    'dashboard.last30Days': 'Letzten 30 Tage',
    'dashboard.uniqueQr': 'Einzigartiger QR',
    'dashboard.yourAccessCode': 'Ihr Zugangscode',
    
    // Dashboard sections
    'dashboard.recentCampaigns': 'Aktuelle Kampagnen',
    'dashboard.recentCampaignsDesc': 'Ihre neuesten Marketing-Kampagnen',
    'dashboard.recentContacts': 'Aktuelle Kontakte',
    'dashboard.recentContactsDesc': 'Kürzlich hinzugefügte neue Kontakte',
    'dashboard.noCampaignsYet': 'Noch keine Kampagnen',
    'dashboard.noContactsYet': 'Noch keine Kontakte',
    
    // Quick Actions
    'dashboard.quickActions': 'Schnellaktionen',
    'dashboard.quickActionsDesc': 'Verknüpfungen zu Hauptfunktionen',
    'dashboard.captureContact': 'Kontakt Erfassen',
    'dashboard.captureContactDesc': 'QR-Code scannen um Kontakt hinzuzufügen',
    'dashboard.newCampaignAction': 'Neue Kampagne',
    'dashboard.newCampaignDesc': 'Marketing-Kampagne erstellen',
    'dashboard.manageContacts': 'Kontakte Verwalten',
    'dashboard.manageContactsDesc': 'Kontakte anzeigen und bearbeiten',
    
    // Campaign Status
    'campaign.status.draft': 'Entwurf',
    'campaign.status.scheduled': 'Geplant',
    'campaign.status.sending': 'Wird gesendet',
    'campaign.status.sent': 'Gesendet',
    'campaign.status.completed': 'Abgeschlossen',
    'campaign.status.failed': 'Fehlgeschlagen',
    'campaign.status.active': 'Aktiv',

    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Verfolgen Sie die Leistung Ihrer Kampagnen und Kontakte',
    'analytics.last7days': 'Letzten 7 Tage',
    'analytics.last30days': 'Letzten 30 Tage',
    'analytics.last90days': 'Letzten 90 Tage',
    'analytics.lastYear': 'Letztes Jahr',
    'analytics.refresh': 'Aktualisieren',
    'analytics.totalCampaigns': 'Gesamte Kampagnen',
    'analytics.totalContacts': 'Gesamte Kontakte',
    'analytics.messagesSent': 'Gesendete Nachrichten',
    'analytics.totalCost': 'Gesamtkosten',
    'analytics.selectedPeriod': 'Ausgewählter Zeitraum',
    'analytics.newContactsAdded': 'Neue Kontakte hinzugefügt',
    'analytics.successRate': 'Erfolgsrate',
    'analytics.campaignExpenses': 'Kampagnenausgaben',
    'analytics.sendTrend': 'Sendetrend',
    'analytics.sentVsDelivered': 'Gesendet vs Zugestellt',
    'analytics.sent': 'Gesendet',
    'analytics.delivered': 'Zugestellt',
    'analytics.campaignsByType': 'Kampagnen nach Typ',
    'analytics.typeDistribution': 'Typ-Verteilung',
    'analytics.campaignStatus': 'Kampagnenstatus',
    'analytics.currentState': 'Aktueller Status',
    'analytics.recentActivity': 'Letzte Aktivität',
    'analytics.lastActions': 'Letzte Aktionen',
    'analytics.noActivity': 'Keine aktuelle Aktivität',
    'analytics.campaign': 'Kampagne',
    'analytics.contact': 'Kontakt',
    'analytics.performance': 'Leistung',
    'analytics.detailedMetrics': 'Detaillierte Metriken',
    'analytics.deliveryRate': 'Zustellungsrate',
    'analytics.costPerMessage': 'Kosten pro Nachricht',
    'analytics.messagesPerContact': 'Nachrichten pro Kontakt',

    // Campaigns
    'campaigns.title': 'Kampagnen',
    'campaigns.subtitle': 'Erstellen und verwalten Sie Ihre Marketing-Kampagnen',
    'campaigns.newCampaign': 'Neue Kampagne',
    'campaigns.createNew': 'Neue Kampagne erstellen',
    'campaigns.configurePromo': 'Konfigurieren Sie Ihre automatisierte Werbekampagne',
    'campaigns.templateOptional': 'Vorlage verwenden (optional)',
    'campaigns.chooseTemplate': 'Bestehende Vorlage auswählen',
    'campaigns.createFromScratch': 'Von Grund auf erstellen',
    'campaigns.campaignName': 'Kampagnenname',
    'campaigns.campaignType': 'Kampagnentyp',
    'campaigns.selectType': 'Typ auswählen',
    'campaigns.templateVariables': 'Vorlagenvariablen',
    'campaigns.promoMessage': 'Werbenachricht',
    'campaigns.writeMessage': 'Schreiben Sie Ihre Werbenachricht...',
    'campaigns.charactersForSms': 'Zeichen für SMS',
    'campaigns.previewVariables': 'Vorschau mit angewendeten Variablen unten',
    'campaigns.finalMessage': 'Finale Nachrichtenvorschau:',
    'campaigns.scheduledAt': 'Sendedatum und -zeit (optional)',
    'campaigns.leaveEmpty': 'Leer lassen für sofortiges Senden',
    'campaigns.sendViaTwilio': 'Senden über Twilio',
    'campaigns.twilioConfigured': 'Twilio-Konfiguration bereits eingerichtet',
    'campaigns.creating': 'Erstellen...',
    'campaigns.createCampaign': 'Kampagne erstellen',
    'campaigns.cancel': 'Abbrechen',
    'campaigns.myCampaigns': 'Meine Kampagnen',
    'campaigns.manageTrack': 'Verwalten und verfolgen Sie Ihre Marketing-Kampagnen',
    'campaigns.noCampaigns': 'Keine Kampagnen',
    'campaigns.createFirst': 'Erstellen Sie Ihre erste Kampagne, um Ihre Kunden zu erreichen.',
    'campaigns.error': 'Fehler',
    'campaigns.fillRequired': 'Bitte füllen Sie alle Pflichtfelder aus',
    'campaigns.success': 'Erfolg',
    'campaigns.created': 'Kampagne erfolgreich erstellt',
    'campaigns.cannotCreate': 'Kampagne kann nicht erstellt werden',
    'campaigns.sent': 'Kampagne erfolgreich gesendet',
    'campaigns.cannotSend': 'Kampagne kann nicht gesendet werden',
    'campaigns.deleted': 'Kampagne erfolgreich gelöscht',
    'campaigns.cannotDelete': 'Kampagne kann nicht gelöscht werden',

    // Contacts
    'contacts.title': 'Kontakte',
    'contacts.subtitle': 'Verwalten Sie Ihre Kundenkontakt-Datenbank',
    'contacts.scanQr': 'QR scannen',
    'contacts.newContact': 'Neuer Kontakt',
    'contacts.total': 'Gesamt',
    'contacts.viaQr': 'Via QR-Code',
    'contacts.withEmail': 'Mit E-Mail',
    'contacts.thisWeek': 'Diese Woche',
    'contacts.searchPlaceholder': 'Nach Name, Telefon oder E-Mail suchen...',
    'contacts.allSources': 'Alle Quellen',
    'contacts.manual': 'Manuell',
    'contacts.import': 'Import',
    'contacts.export': 'Exportieren',
    'contacts.noContacts': 'Keine Kontakte gefunden',
    'contacts.selectAll': 'Alle auswählen',
    'contacts.unselectAll': 'Alle abwählen',
    'contacts.addedOn': 'Hinzugefügt am',
    'contacts.confirmDelete': 'Löschen bestätigen',
    'contacts.deleteConfirm': 'Sind Sie sicher, dass Sie den Kontakt löschen möchten',
    'contacts.cannotUndo': 'Diese Aktion kann nicht rückgängig gemacht werden.',
    'contacts.delete': 'Löschen',
    'contacts.adjustFilters': 'Versuchen Sie, die Filter oder Suchbegriffe anzupassen',
    'contacts.startScanning': 'Beginnen Sie mit dem Scannen von QR-Codes oder fügen Sie Kontakte manuell hinzu',
    'contacts.addContact': 'Kontakt hinzufügen',

    // Templates
    'templates.title': 'Vorlagen',
    'templates.subtitle': 'Erstellen und verwalten Sie Ihre Nachrichtenvorlagen',
    'templates.newTemplate': 'Neue Vorlage',
    'templates.totalTemplates': 'Vorlagen Gesamt',
    'templates.categories': 'Kategorien',
    'templates.mostUsed': 'Am meisten verwendet',
    'templates.general': 'Allgemein',
    'templates.none': 'Keine',
    'templates.editTemplate': 'Vorlage bearbeiten',
    'templates.createNewTemplate': 'Neue Vorlage erstellen',
    'templates.useVariables': 'Verwenden Sie {{variable}} für dynamischen Inhalt',
    'templates.templateName': 'Vorlagenname',
    'templates.templateNameExample': 'Z.B.: Montag-Promotion',
    'templates.category': 'Kategorie',
    'templates.selectCategory': 'Kategorie auswählen',
    'templates.templateMessage': 'Vorlagennachricht',
    'templates.messageExample': 'Hallo {{name}}, entdecken Sie unser Sonderangebot...',
    'templates.variablesDetected': 'Erkannte Variablen:',
    'templates.modifying': 'Bearbeiten...',
    'templates.creating': 'Erstellen...',
    'templates.modify': 'Bearbeiten',
    'templates.create': 'Erstellen',
    'templates.myTemplates': 'Meine Vorlagen',
    'templates.manageTemplates': 'Verwalten Sie Ihre Nachrichtenvorlagen',
    'templates.noTemplates': 'Keine Vorlagen',
    'templates.createFirstTemplate': 'Erstellen Sie Ihre erste Vorlage, um Zeit bei der Kampagnenerstellung zu sparen.',
    'templates.createTemplate': 'Vorlage erstellen',
    'templates.loadProTemplates': 'Pro-Vorlagen laden',
    'templates.variables': 'Variablen',
    'templates.variable': 'Variable',
    'templates.copy': 'Kopieren',
    'templates.error': 'Fehler',
    'templates.fillRequired': 'Bitte füllen Sie alle Pflichtfelder aus',
    'templates.success': 'Erfolg',
    'templates.templateModified': 'Vorlage erfolgreich bearbeitet',
    'templates.templateCreated': 'Vorlage erfolgreich erstellt',
    'templates.cannotSave': 'Vorlage kann nicht gespeichert werden',
    'templates.templateDeleted': 'Vorlage erfolgreich gelöscht',
    'templates.cannotDelete': 'Vorlage kann nicht gelöscht werden',
    'templates.copied': 'Kopiert',
    'templates.copiedToClipboard': 'In die Zwischenablage kopiert',
    'templates.defaultTemplatesAdded': 'Standard-Vorlagen erfolgreich hinzugefügt',
    'templates.cannotLoadDefaults': 'Standard-Vorlagen können nicht geladen werden',

    // Template Categories
    'templateCategories.general': 'Allgemein',
    'templateCategories.promotion': 'Promotion',
    'templateCategories.welcome': 'Willkommen',
    'templateCategories.reminder': 'Erinnerung',
    'templateCategories.event': 'Ereignis',
    'templateCategories.special_offer': 'Sonderangebot',
    'templateCategories.feedback': 'Feedback',

    // QR Form
    'qrForm.title': 'QR-Kontaktformular',
    'qrForm.fillForm': 'Füllen Sie dieses Formular aus, um unsere exklusiven Angebote zu erhalten',
    'qrForm.name': 'Vollständiger Name',
    'qrForm.namePlaceholder': 'Ihr vollständiger Name',
    'qrForm.phone': 'Telefon',
    'qrForm.phonePlaceholder': 'Ihre Telefonnummer',
    'qrForm.email': 'E-Mail (optional)',
    'qrForm.emailPlaceholder': 'ihre@email.com',
    'qrForm.submitButton': 'Angebote erhalten',
    'qrForm.submitting': 'Senden...',
    'qrForm.successTitle': 'Danke!',
    'qrForm.successMessage': 'Ihre Informationen wurden erfolgreich gespeichert. Sie erhalten bald unsere besten Angebote!',
    'qrForm.errorTitle': 'Fehler',
    'qrForm.errorMessage': 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',
    'qrForm.fillRequired': 'Bitte füllen Sie alle Pflichtfelder aus',
    'qrForm.scanInstructions': 'Scannen Sie den QR-Code mit Ihrem Telefon, um auf das Kontaktformular zuzugreifen',
    'qrForm.qrCodeGenerated': 'QR-Code erfolgreich generiert',
    'qrForm.generateButton': 'QR-Code generieren',
    'qrForm.downloadQr': 'QR herunterladen',
    'qrForm.printQr': 'QR drucken',
    'qrForm.newQr': 'Neuer QR',
    'qrForm.qrTips': 'Nutzungstipps:',
    'qrForm.tip1': 'Platzieren Sie den QR-Code auf Ihren Tischen',
    'qrForm.tip2': 'Fügen Sie ihn zu Ihren Menüs hinzu',
    'qrForm.tip3': 'Zeigen Sie ihn am Eingang Ihres Restaurants',
    
    // QR Generator
    'qrGenerator.loadError': 'QR-Code konnte nicht geladen werden',
    'qrGenerator.shareDescription': 'Teilen Sie diesen QR-Code, damit Kunden ihre Daten hinterlassen können',
    'qrGenerator.directLink': 'Direkter Link:',
    'qrGenerator.downloadQr': 'QR herunterladen',
    'qrGenerator.share': 'Teilen',
    'qrGenerator.howToUse': 'Verwendung:',
    'qrGenerator.instruction1': '1. Drucken oder zeigen Sie den QR-Code den Kunden',
    'qrGenerator.instruction2': '2. Kunden scannen mit ihrer Handy-Kamera',
    'qrGenerator.instruction3': '3. Sie füllen das Formular aus',
    'qrGenerator.instruction4': '4. Daten erscheinen automatisch in Ihren Kontakten',
    'qrGenerator.linkCopied': 'Link kopiert!',
    'qrGenerator.linkCopiedDesc': 'Der Formular-Link wurde in die Zwischenablage kopiert.',
    'qrGenerator.loading': 'QR-Code wird geladen...',
    'qrGenerator.cannotGenerate': 'QR-Code konnte nicht generiert werden.',

    // NotFound
    'notFound.title': 'Seite nicht gefunden',
    'notFound.message': 'Die Seite, die Sie suchen, existiert nicht.',
    'notFound.backHome': 'Zurück zur Startseite',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'fr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations[typeof language]];
    return translation || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}