import { createContext, useContext, ReactNode, useState, useEffect } from 'react';

type Language = 'fr' | 'en' | 'it' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations
const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.plans': 'Tarifs',
    'nav.generateQr': 'Générer QR',
    'nav.dashboard': 'Tableau de bord',
    'nav.contacts': 'Contacts',
    'nav.campaigns': 'Campagnes',
    'nav.templates': 'Modèles',
    'nav.login': 'Se connecter',
    'nav.logout': 'Se déconnecter',
    
    // Auth
    'auth.hello': 'Bonjour',
    'auth.loggedAs': 'Connecté en tant que',
    'auth.user': 'Utilisateur',
    
    // Plans page
    'plans.badge': 'Système Premium de Marketing',
    'plans.title': 'Révolutionnez le Marketing de Votre Restaurant',
    'plans.subtitle': 'Capturez des contacts, construisez des relations et augmentez vos ventes avec notre plateforme complète de marketing digital pour restaurants.',
    'plans.whyChoose': 'Pourquoi choisir notre plateforme ?',
    'plans.captureMore': 'Capturez Plus de Clients',
    'plans.captureDesc': 'Transformez les visiteurs en contacts avec des QR codes stratégiques',
    'plans.directComm': 'Communication Directe',
    'plans.directCommDesc': 'Envoyez des campagnes personnalisées par SMS à vos clients',
    'plans.measurableResults': 'Résultats Mesurables',
    'plans.measurableDesc': 'Suivez les métriques et optimisez vos campagnes marketing',
    'plans.singlePlan': 'Plan Unique, Fonctionnalités Complètes',
    'plans.transformDesc': 'Tout ce dont vous avez besoin pour transformer votre restaurant',
    'plans.mostPopular': 'Le Plus Populaire',
    'plans.professional': 'Plan Professionnel',
    'plans.forRestaurants': 'Pour les restaurants qui veulent grandir',
    'plans.perMonth': '/mois',
    'plans.startNow': 'Commencer Maintenant',
    'plans.cancelAnytime': 'Annulez à tout moment • Support 24/7 • Pas de frais cachés',
    'plans.joinRestaurants': 'Rejoignez les restaurants qui grandissent déjà',
    'plans.contactIncrease': 'Augmentation de la capture de contacts',
    'plans.openRate': "Taux d'ouverture des campagnes SMS",
    'plans.customerReturn': 'Retour des clients',
    'plans.readyTransform': 'Prêt à transformer votre restaurant ?',
    'plans.seeResults': 'Commencez aujourd\'hui et voyez les résultats en 30 jours ou moins',
    'plans.startTransformation': 'Démarrer Ma Transformation',
    
    // Features
    'features.qrCode': 'QR Code personnalisé pour votre restaurant',
    'features.unlimitedCapture': 'Capture illimitée de contacts clients',
    'features.smsCompaigns': 'Campagnes SMS professionnelles',
    'features.templates': 'Modèles de messages personnalisables',
    'features.analytics': 'Analytics détaillés des campagnes',
    'features.contactManagement': 'Gestion complète des contacts',
    'features.prioritySupport': 'Support technique prioritaire',
    'features.autoUpdates': 'Mises à jour automatiques',
    
    // Footer
    'footer.features': 'Fonctionnalités',
    'footer.contactCollection': 'Collecte de contacts',
    'footer.automatedCampaigns': 'Campagnes automatisées',
    'footer.referralProgram': 'Programme de parrainage',
    'footer.detailedAnalytics': 'Analytics détaillés',
    'footer.support': 'Support',
    'footer.documentation': 'Documentation',
    'footer.contact': 'Contact',
    'footer.faq': 'FAQ',
    'footer.onlineHelp': 'Aide en ligne',
    'footer.allRights': 'Tous droits réservés.',
    'footer.description': 'Augmentez votre chiffre d\'affaires les jours de faible affluence grâce à notre solution de fidélisation et de marketing ciblé.',
    
    // Home page
    'home.heroTitle': 'Boostez votre restaurant les jours calmes',
    'home.heroSubtitle': 'Collectez des contacts via QR code et envoyez des promotions ciblées pour augmenter votre chiffre d\'affaires jusqu\'à 40%.',
    'home.tryNow': 'Essayer maintenant',
    'home.seeDemo': 'Voir la démo',
    'home.openRate': 'Taux d\'ouverture SMS',
    'home.revenueIncrease': 'Augmentation du CA',
    'home.quickSetup': 'Configuration rapide',
    'home.support': 'Support client',
    'home.innovative': 'Solution innovante',
    'home.featuresTitle': 'Tout ce dont vous avez besoin',
    'home.featuresSubtitle': 'Une solution complète pour transformer vos jours de faible affluence en opportunités de croissance.',
    'home.howItWorks': 'Comment ça marche',
    'home.simpleSteps': 'Simple et efficace en 3 étapes',
    'home.ctaTitle': 'Prêt à booster votre restaurant ?',
    'home.ctaSubtitle': 'Rejoignez des centaines de restaurateurs qui ont déjà augmenté leur chiffre d\'affaires.',
    'home.testFree': 'Tester gratuitement',
    'home.scheduleDemo': 'Planifier une démo',
    
    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.subtitle': 'Aperçu de votre entreprise et métriques de performance',
    'dashboard.overview': 'Aperçu',
    'dashboard.overviewTitle': 'Aperçu',
    'dashboard.overviewSubtitle': 'Tableau de bord principal de votre DopplerDine',
    'dashboard.scanQr': 'Scanner QR',
    'dashboard.newCampaign': 'Nouvelle Campagne',
    
    // Auth
    'auth.loginSubtitle': 'Connectez-vous ou créez votre compte pour commencer',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Acompanhe o desempenho das suas campanhas e contatos',
    'analytics.last7days': 'Últimos 7 dias',
    'analytics.last30days': 'Últimos 30 dias', 
    'analytics.last90days': 'Últimos 90 dias',
    'analytics.lastYear': 'Último ano',
    'analytics.refresh': 'Atualizar',
    'analytics.totalCampaigns': 'Total Campanhas',
    'analytics.totalContacts': 'Total Contatos',
    'analytics.messagesSent': 'Mensagens Enviadas',
    'analytics.totalCost': 'Custo Total',
    'analytics.selectedPeriod': 'No período selecionado',
    'analytics.newContactsAdded': 'Novos contatos adicionados',
    'analytics.successRate': 'Taxa de sucesso',
    'analytics.campaignExpenses': 'Gastos com campanhas',
    'analytics.sendTrend': 'Tendência de Envios',
    'analytics.sentVsDelivered': 'Últimos 7 dias - Enviadas vs Entregues',
    'analytics.sent': 'Enviadas',
    'analytics.delivered': 'Entregues',
    'analytics.campaignsByType': 'Campanhas por Tipo',
    'analytics.typeDistribution': 'Distribuição dos tipos de campanha',
    'analytics.campaignStatus': 'Status das Campanhas',
    'analytics.currentState': 'Estado atual das campanhas',
    'analytics.recentActivity': 'Atividade Recente',
    'analytics.lastActions': 'Últimas ações realizadas',
    'analytics.noActivity': 'Nenhuma atividade recente',
    'analytics.performance': 'Detalhes de Performance',
    'analytics.detailedMetrics': 'Métricas detalhadas de sucesso das campanhas',
    'analytics.deliveryRate': 'Taxa de Entrega',
    'analytics.costPerMessage': 'Custo por Mensagem (R$)',
    'analytics.messagesPerContact': 'Mensagens por Contato',
    'analytics.campaign': 'Campanha',
    'analytics.contact': 'Contato',
    
    // Campaigns
    'campaigns.title': 'Campagnes',
    'campaigns.subtitle': 'Gérez vos campagnes de marketing automatisées',
    'campaigns.newCampaign': 'Nouvelle campagne',
    'campaigns.createNew': 'Créer une nouvelle campagne',
    'campaigns.configure': 'Configurez votre campagne de promotion automatisée',
    'campaigns.useTemplate': 'Utiliser un template (optionnel)',
    'campaigns.chooseTemplate': 'Choisir un template existant',
    'campaigns.createFromScratch': 'Créer depuis zéro',
    'campaigns.templateSelected': 'Template sélectionné. Vous pouvez modifier le message ci-dessous.',
    'campaigns.campaignName': 'Nom de la campagne',
    'campaigns.campaignType': 'Type de campagne',
    'campaigns.selectType': 'Sélectionner un type',
    'campaigns.templateVariables': 'Variables du template',
    'campaigns.variablesDescription': 'Ces variables seront remplacées dans le message final.',
    'campaigns.promotionalMessage': 'Message promotionnel',
    'campaigns.writeMessage': 'Rédigez votre message promotionnel...',
    'campaigns.charactersForSMS': 'caractères pour SMS',
    'campaigns.previewWithVariables': 'Aperçu avec variables appliquées ci-dessous',
    'campaigns.finalMessagePreview': 'Aperçu du message final:',
    'campaigns.scheduledDate': 'Date et heure d\'envoi (optionnel)',
    'campaigns.sendImmediately': 'Laissez vide pour envoyer immédiatement',
    'campaigns.twilioSending': 'Envio via Twilio',
    'campaigns.twilioConfigured': 'Configuração do Twilio já configurada',
    'campaigns.smsMessages': 'Mensagens SMS serão enviadas diretamente',
    'campaigns.whatsappMessages': 'Mensagens WhatsApp serão enviadas diretamente',
    'campaigns.twilioApiConfigured': 'API Twilio configurada nos secrets',
    'campaigns.creating': 'Création...',
    'campaigns.createCampaign': 'Créer la campagne',
    'campaigns.cancel': 'Annuler',
    'campaigns.myCampaigns': 'Mes campagnes',
    'campaigns.manageCampaigns': 'Gérez et suivez vos campagnes marketing',
    'campaigns.noCampaigns': 'Aucune campagne',
    'campaigns.createFirstCampaign': 'Créez votre première campagne pour commencer à engager vos clients.',
    'campaigns.send': 'Envoyer',
    'campaigns.active': 'Actif',
    'campaigns.sent': 'Envoyé',
    'campaigns.scheduled': 'Programmé',
    'campaigns.draft': 'Brouillon',
    'campaigns.scheduledFor': 'Programmé pour',
    'campaigns.error': 'Erreur',
    'campaigns.fillRequired': 'Veuillez remplir tous les champs obligatoires',
    'campaigns.success': 'Succès',
    'campaigns.campaignCreated': 'Campagne créée avec succès',
    'campaigns.campaignSent': 'Campagne envoyée avec succès',
    'campaigns.campaignDeleted': 'Campagne supprimée avec succès',
    'campaigns.cannotCreate': 'Impossible de créer la campagne',
    'campaigns.cannotSend': 'Impossible d\'envoyer la campagne',
    'campaigns.cannotDelete': 'Impossible de supprimer la campagne',
    
    // Contacts
    'contacts.title': 'Contatos',
    'contacts.subtitle': 'Gerencie sua base de clientes',
    'contacts.scanQR': 'Escanear QR',
    'contacts.newContact': 'Novo Contato',
    'contacts.total': 'Total',
    'contacts.viaQRCode': 'Via QR Code',
    'contacts.withEmail': 'Com Email',
    'contacts.thisWeek': 'Esta Semana',
    'contacts.searchPlaceholder': 'Buscar por nome, telefone ou email...',
    'contacts.allSources': 'Todas as origens',
    'contacts.manual': 'Manual',
    'contacts.import': 'Importação',
    'contacts.export': 'Exportar',
    'contacts.contactsFound': 'contatos',
    'contacts.noContactsFound': 'Nenhum contato encontrado',
    'contacts.selectAll': 'Selecionar todos',
    'contacts.deselectAll': 'Desmarcar todos',
    'contacts.addedOn': 'Adicionado em',
    'contacts.confirmDelete': 'Confirmar exclusão',
    'contacts.deleteConfirmation': 'Tem certeza que deseja excluir o contato',
    'contacts.actionCannotBeUndone': 'Esta ação não pode ser desfeita.',
    'contacts.cancel': 'Cancelar',
    'contacts.delete': 'Excluir',
    'contacts.noContactsFoundDesc': 'Nenhum contato encontrado',
    'contacts.adjustFilters': 'Tente ajustar os filtros ou termos de busca',
    'contacts.startScanning': 'Comece escaneando QR codes ou adicionando contatos manualmente',
    'contacts.scanQRCode': 'Escanear QR Code',
    'contacts.addContact': 'Adicionar Contato',
    
    // Public Form
    'publicForm.loading': 'Carregando...',
    'publicForm.error': 'Erro',
    'publicForm.couldNotLoad': 'Não foi possível carregar as informações do restaurante.',
    'publicForm.invalidQR': 'QR Code inválido',
    'publicForm.invalidOrExpired': 'Este QR code não é válido ou expirou.',
    'publicForm.unexpectedError': 'Ocorreu um erro inesperado.',
    'publicForm.leaveData': 'Deixe seus dados para receber ofertas exclusivas!',
    'publicForm.fullName': 'Nome completo',
    'publicForm.yourName': 'Seu nome',
    'publicForm.whatsappPhone': 'WhatsApp/Telefone',
    'publicForm.emailOptional': 'Email (opcional)',
    'publicForm.commentsOptional': 'Comentários (opcional)',
    'publicForm.leaveComment': 'Deixe um comentário...',
    'publicForm.saving': 'Salvando...',
    'publicForm.saveData': 'Salvar meus dados',
    'publicForm.dataSecure': 'Seus dados estão seguros e serão usados apenas para ofertas especiais do',
    'publicForm.success': 'Sucesso!',
    'publicForm.thankYou': 'Obrigado',
    'publicForm.dataSaved': 'Seus dados foram salvos com sucesso.',
    'publicForm.cannotSave': 'Não foi possível salvar seus dados. Tente novamente.',
    'publicForm.restaurantNotFound': 'Restaurante não encontrado',
    
    // QR Form
    'qrForm.title': 'QR Scanner',
    'qrForm.subtitle': 'Escaneie QR codes para adicionar novos contatos',
    'qrForm.cameraScanner': 'Câmera Scanner',
    'qrForm.permissionDenied': 'Permissão de câmera negada',
    'qrForm.clickToStart': 'Clique em "Iniciar Scanner" para começar',
    'qrForm.pointToQR': 'Aponte para um QR code',
    'qrForm.stopScanner': 'Parar Scanner',
    'qrForm.startScanner': 'Iniciar Scanner',
    'qrForm.reset': 'Resetar',
    'qrForm.qrDetected': 'QR Code detectado:',
    'qrForm.positionQR': 'Posicione o QR code no centro da câmera',
    'qrForm.contactDataFilled': 'QR codes com dados de contato serão preenchidos automaticamente',
    'qrForm.otherQRSaved': 'Outros QR codes serão salvos nas observações',
    'qrForm.contactData': 'Dados do Contato',
    'qrForm.scanToFill': 'Escaneie um QR code para preencher os dados',
    'qrForm.nameRequired': 'Nome',
    'qrForm.customerName': 'Nome do cliente',
    'qrForm.phone': 'Telefone',
    'qrForm.email': 'Email',
    'qrForm.tags': 'Tags',
    'qrForm.addTag': 'Adicionar tag',
    'qrForm.notes': 'Observações',
    'qrForm.customerNotes': 'Observações sobre o cliente...',
    'qrForm.saving': 'Salvando...',
    'qrForm.saveContact': 'Salvar Contato',
    'qrForm.requiredFields': 'Campos obrigatórios',
    'qrForm.namePhoneRequired': 'Nome e telefone são obrigatórios.',
    'qrForm.contactAdded': 'Contato adicionado!',
    'qrForm.contactAddedToList': 'foi adicionado aos seus contatos.',
    'qrForm.scanningTips': 'Dicas para melhor escaneamento',
    'qrForm.goodLighting': 'Boa iluminação',
    'qrForm.useWellLit': 'Use em ambientes bem iluminados',
    'qrForm.adequateDistance': 'Distância adequada',
    'qrForm.maintain10to30cm': 'Mantenha 10-30cm de distância',
    'qrForm.cleanQR': 'QR code limpo',
    'qrForm.ensureReadable': 'Certifique-se que esteja legível',
    'qrForm.qrScanned': 'QR Code escaneado!',
    'qrForm.fillDataBelow': 'Preencha os dados do contato abaixo.',
    
    // Templates
    'templates.title': 'Templates de Messages',
    'templates.subtitle': 'Créez et gérez vos templates de messages réutilisables',
    'templates.newTemplate': 'Nouveau template',
    'templates.totalTemplates': 'Total Templates',
    'templates.categories': 'Catégories',
    'templates.mostUsed': 'Plus Utilisé',
    'templates.general': 'Général',
    'templates.none': 'Aucun',
    'templates.editTemplate': 'Modifier le template',
    'templates.createNewTemplate': 'Créer un nouveau template',
    'templates.useVariables': 'Utilisez des variables avec la syntaxe: {{ nomVariable }}',
    'templates.templateName': 'Nom du template',
    'templates.templateNameExample': 'Ex: Promotion Lundi',
    'templates.category': 'Catégorie',
    'templates.selectCategory': 'Sélectionner une catégorie',
    'templates.templateMessage': 'Message du template',
    'templates.messageExample': 'Ex: Bonjour {{nom}}, profitez de notre offre spéciale {{offre}} valable jusqu\'au {{date}} !',
    'templates.variablesDetected': 'Variables détectées:',
    'templates.modifying': 'Modification...',
    'templates.creating': 'Création...',
    'templates.modify': 'Modifier',
    'templates.create': 'Créer',
    'templates.cancel': 'Annuler',
    'templates.myTemplates': 'Mes Templates',
    'templates.manageTemplates': 'Gérez vos templates de messages réutilisables',
    'templates.noTemplates': 'Aucun template',
    'templates.createFirstTemplate': 'Créez votre premier template ou utilisez nos templates professionnels.',
    'templates.createTemplate': 'Créer un template',
    'templates.loadProTemplates': 'Charger templates pro',
    'templates.variables': 'Variables:',
    'templates.copy': 'Copier',
    'templates.copied': 'Copié',
    'templates.copiedToClipboard': 'Template copié dans le presse-papier',
    'templates.error': 'Erreur',
    'templates.fillRequired': 'Veuillez remplir tous les champs obligatoires',
    'templates.success': 'Succès',
    'templates.templateModified': 'Template modifié avec succès',
    'templates.templateCreated': 'Template créé avec succès',
    'templates.templateDeleted': 'Template supprimé avec succès',
    'templates.defaultTemplatesAdded': 'Templates par défaut ajoutés avec succès',
    'templates.cannotSave': 'Impossible de sauvegarder le template',
    'templates.cannotDelete': 'Impossible de supprimer le template',
    'templates.cannotLoadDefaults': 'Impossible de charger les templates par défaut',
    
    // Template Categories
    'templateCategories.general': 'Général',
    'templateCategories.promotion': 'Promotion',
    'templateCategories.welcome': 'Bienvenue',
    'templateCategories.reminder': 'Rappel',
    'templateCategories.event': 'Événement',
    'templateCategories.special_offer': 'Offre spéciale',
    'templateCategories.feedback': 'Avis client',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.plans': 'Pricing',
    'nav.generateQr': 'Generate QR',
    'nav.dashboard': 'Dashboard',
    'nav.contacts': 'Contacts',
    'nav.campaigns': 'Campaigns',
    'nav.templates': 'Templates',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    
    // Auth
    'auth.hello': 'Hello',
    'auth.loggedAs': 'Logged in as',
    'auth.user': 'User',
    
    // Plans page
    'plans.badge': 'Premium Marketing System',
    'plans.title': 'Revolutionize Your Restaurant Marketing',
    'plans.subtitle': 'Capture contacts, build relationships and increase your sales with our complete digital marketing platform for restaurants.',
    'plans.whyChoose': 'Why choose our platform?',
    'plans.captureMore': 'Capture More Customers',
    'plans.captureDesc': 'Transform visitors into contacts with strategic QR codes',
    'plans.directComm': 'Direct Communication',
    'plans.directCommDesc': 'Send personalized SMS campaigns to your customers',
    'plans.measurableResults': 'Measurable Results',
    'plans.measurableDesc': 'Track metrics and optimize your marketing campaigns',
    'plans.singlePlan': 'Single Plan, Complete Features',
    'plans.transformDesc': 'Everything you need to transform your restaurant',
    'plans.mostPopular': 'Most Popular',
    'plans.professional': 'Professional Plan',
    'plans.forRestaurants': 'For restaurants that want to grow',
    'plans.perMonth': '/month',
    'plans.startNow': 'Start Now',
    'plans.cancelAnytime': 'Cancel anytime • 24/7 Support • No hidden fees',
    'plans.joinRestaurants': 'Join restaurants that are already growing',
    'plans.contactIncrease': 'Increase in contact capture',
    'plans.openRate': 'SMS campaign open rate',
    'plans.customerReturn': 'Customer return',
    'plans.readyTransform': 'Ready to transform your restaurant?',
    'plans.seeResults': 'Start today and see results in 30 days or less',
    'plans.startTransformation': 'Start My Transformation',
    
    // Features
    'features.qrCode': 'Custom QR Code for your restaurant',
    'features.unlimitedCapture': 'Unlimited customer contact capture',
    'features.smsCompaigns': 'Professional SMS campaigns',
    'features.templates': 'Customizable message templates',
    'features.analytics': 'Detailed campaign analytics',
    'features.contactManagement': 'Complete contact management',
    'features.prioritySupport': 'Priority technical support',
    'features.autoUpdates': 'Automatic updates',
    
    // Footer
    'footer.features': 'Features',
    'footer.contactCollection': 'Contact collection',
    'footer.automatedCampaigns': 'Automated campaigns',
    'footer.referralProgram': 'Referral program',
    'footer.detailedAnalytics': 'Detailed analytics',
    'footer.support': 'Support',
    'footer.documentation': 'Documentation',
    'footer.contact': 'Contact',
    'footer.faq': 'FAQ',
    'footer.onlineHelp': 'Online help',
    'footer.allRights': 'All rights reserved.',
    'footer.description': 'Increase your revenue on low-traffic days with our customer loyalty and targeted marketing solution.',
    
    // Home page
    'home.heroTitle': 'Boost your restaurant on slow days',
    'home.heroSubtitle': 'Collect contacts via QR code and send targeted promotions to increase your revenue by up to 40%.',
    'home.tryNow': 'Try now',
    'home.seeDemo': 'See demo',
    'home.openRate': 'SMS open rate',
    'home.revenueIncrease': 'Revenue increase',
    'home.quickSetup': 'Quick setup',
    'home.support': 'Customer support',
    'home.innovative': 'Innovative solution',
    'home.featuresTitle': 'Everything you need',
    'home.featuresSubtitle': 'A complete solution to transform your low-traffic days into growth opportunities.',
    'home.howItWorks': 'How it works',
    'home.simpleSteps': 'Simple and effective in 3 steps',
    'home.ctaTitle': 'Ready to boost your restaurant?',
    'home.ctaSubtitle': 'Join hundreds of restaurateurs who have already increased their revenue.',
    'home.testFree': 'Test for free',
    'home.scheduleDemo': 'Schedule demo',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of your business and performance metrics',
    'dashboard.overview': 'Overview',
    'dashboard.overviewTitle': 'Overview',
    'dashboard.overviewSubtitle': 'Main dashboard of your DopplerDine',
    'dashboard.scanQr': 'Scan QR',
    'dashboard.newCampaign': 'New Campaign',
    
    // Auth
    'auth.loginSubtitle': 'Log in or create your account to get started',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Track the performance of your campaigns and contacts',
    'analytics.last7days': 'Last 7 days',
    'analytics.last30days': 'Last 30 days',
    'analytics.last90days': 'Last 90 days',
    'analytics.lastYear': 'Last year',
    'analytics.refresh': 'Refresh',
    'analytics.totalCampaigns': 'Total Campaigns',
    'analytics.totalContacts': 'Total Contacts',
    'analytics.messagesSent': 'Messages Sent',
    'analytics.totalCost': 'Total Cost',
    'analytics.selectedPeriod': 'In selected period',
    'analytics.newContactsAdded': 'New contacts added',
    'analytics.successRate': 'Success rate',
    'analytics.campaignExpenses': 'Campaign expenses',
    'analytics.sendTrend': 'Send Trend',
    'analytics.sentVsDelivered': 'Last 7 days - Sent vs Delivered',
    'analytics.sent': 'Sent',
    'analytics.delivered': 'Delivered',
    'analytics.campaignsByType': 'Campaigns by Type',
    'analytics.typeDistribution': 'Campaign type distribution',
    'analytics.campaignStatus': 'Campaign Status',
    'analytics.currentState': 'Current state of campaigns',
    'analytics.recentActivity': 'Recent Activity',
    'analytics.lastActions': 'Latest actions performed',
    'analytics.noActivity': 'No recent activity',
    'analytics.performance': 'Performance Details',
    'analytics.detailedMetrics': 'Detailed campaign success metrics',
    'analytics.deliveryRate': 'Delivery Rate',
    'analytics.costPerMessage': 'Cost per Message ($)',
    'analytics.messagesPerContact': 'Messages per Contact',
    'analytics.campaign': 'Campaign',
    'analytics.contact': 'Contact',
    
    // Campaigns
    'campaigns.title': 'Campaigns',
    'campaigns.subtitle': 'Manage your automated marketing campaigns',
    'campaigns.newCampaign': 'New campaign',
    'campaigns.createNew': 'Create new campaign',
    'campaigns.configure': 'Configure your automated promotion campaign',
    'campaigns.useTemplate': 'Use template (optional)',
    'campaigns.chooseTemplate': 'Choose existing template',
    'campaigns.createFromScratch': 'Create from scratch',
    'campaigns.templateSelected': 'Template selected. You can modify the message below.',
    'campaigns.campaignName': 'Campaign name',
    'campaigns.campaignType': 'Campaign type',
    'campaigns.selectType': 'Select type',
    'campaigns.templateVariables': 'Template variables',
    'campaigns.variablesDescription': 'These variables will be replaced in the final message.',
    'campaigns.promotionalMessage': 'Promotional message',
    'campaigns.writeMessage': 'Write your promotional message...',
    'campaigns.charactersForSMS': 'characters for SMS',
    'campaigns.previewWithVariables': 'Preview with variables applied below',
    'campaigns.finalMessagePreview': 'Final message preview:',
    'campaigns.scheduledDate': 'Send date and time (optional)',
    'campaigns.sendImmediately': 'Leave empty to send immediately',
    'campaigns.twilioSending': 'Sending via Twilio',
    'campaigns.twilioConfigured': 'Twilio configuration already set up',
    'campaigns.smsMessages': 'SMS messages will be sent directly',
    'campaigns.whatsappMessages': 'WhatsApp messages will be sent directly',
    'campaigns.twilioApiConfigured': 'Twilio API configured in secrets',
    'campaigns.creating': 'Creating...',
    'campaigns.createCampaign': 'Create campaign',
    'campaigns.cancel': 'Cancel',
    'campaigns.myCampaigns': 'My campaigns',
    'campaigns.manageCampaigns': 'Manage and track your marketing campaigns',
    'campaigns.noCampaigns': 'No campaigns',
    'campaigns.createFirstCampaign': 'Create your first campaign to start engaging your customers.',
    'campaigns.send': 'Send',
    'campaigns.active': 'Active',
    'campaigns.sent': 'Sent',
    'campaigns.scheduled': 'Scheduled',
    'campaigns.draft': 'Draft',
    'campaigns.scheduledFor': 'Scheduled for',
    'campaigns.error': 'Error',
    'campaigns.fillRequired': 'Please fill all required fields',
    'campaigns.success': 'Success',
    'campaigns.campaignCreated': 'Campaign created successfully',
    'campaigns.campaignSent': 'Campaign sent successfully',
    'campaigns.campaignDeleted': 'Campaign deleted successfully',
    'campaigns.cannotCreate': 'Unable to create campaign',
    'campaigns.cannotSend': 'Unable to send campaign',
    'campaigns.cannotDelete': 'Unable to delete campaign',
    
    // Contacts
    'contacts.title': 'Contacts',
    'contacts.subtitle': 'Manage your customer base',
    'contacts.scanQR': 'Scan QR',
    'contacts.newContact': 'New Contact',
    'contacts.total': 'Total',
    'contacts.viaQRCode': 'Via QR Code',
    'contacts.withEmail': 'With Email',
    'contacts.thisWeek': 'This Week',
    'contacts.searchPlaceholder': 'Search by name, phone or email...',
    'contacts.allSources': 'All sources',
    'contacts.manual': 'Manual',
    'contacts.import': 'Import',
    'contacts.export': 'Export',
    'contacts.contactsFound': 'contacts',
    'contacts.noContactsFound': 'No contacts found',
    'contacts.selectAll': 'Select all',
    'contacts.deselectAll': 'Deselect all',
    'contacts.addedOn': 'Added on',
    'contacts.confirmDelete': 'Confirm deletion',
    'contacts.deleteConfirmation': 'Are you sure you want to delete the contact',
    'contacts.actionCannotBeUndone': 'This action cannot be undone.',
    'contacts.cancel': 'Cancel',
    'contacts.delete': 'Delete',
    'contacts.noContactsFoundDesc': 'No contacts found',
    'contacts.adjustFilters': 'Try adjusting filters or search terms',
    'contacts.startScanning': 'Start by scanning QR codes or adding contacts manually',
    'contacts.scanQRCode': 'Scan QR Code',
    'contacts.addContact': 'Add Contact',
    
    // Public Form
    'publicForm.loading': 'Loading...',
    'publicForm.error': 'Error',
    'publicForm.couldNotLoad': 'Could not load restaurant information.',
    'publicForm.invalidQR': 'Invalid QR Code',
    'publicForm.invalidOrExpired': 'This QR code is not valid or has expired.',
    'publicForm.unexpectedError': 'An unexpected error occurred.',
    'publicForm.leaveData': 'Leave your details to receive exclusive offers!',
    'publicForm.fullName': 'Full name',
    'publicForm.yourName': 'Your name',
    'publicForm.whatsappPhone': 'WhatsApp/Phone',
    'publicForm.emailOptional': 'Email (optional)',
    'publicForm.commentsOptional': 'Comments (optional)',
    'publicForm.leaveComment': 'Leave a comment...',
    'publicForm.saving': 'Saving...',
    'publicForm.saveData': 'Save my data',
    'publicForm.dataSecure': 'Your data is secure and will be used only for special offers from',
    'publicForm.success': 'Success!',
    'publicForm.thankYou': 'Thank you',
    'publicForm.dataSaved': 'Your data has been saved successfully.',
    'publicForm.cannotSave': 'Could not save your data. Please try again.',
    'publicForm.restaurantNotFound': 'Restaurant not found',
    
    // QR Form
    'qrForm.title': 'QR Scanner',
    'qrForm.subtitle': 'Scan QR codes to add new contacts',
    'qrForm.cameraScanner': 'Camera Scanner',
    'qrForm.permissionDenied': 'Camera permission denied',
    'qrForm.clickToStart': 'Click "Start Scanner" to begin',
    'qrForm.pointToQR': 'Point to a QR code',
    'qrForm.stopScanner': 'Stop Scanner',
    'qrForm.startScanner': 'Start Scanner',
    'qrForm.reset': 'Reset',
    'qrForm.qrDetected': 'QR Code detected:',
    'qrForm.positionQR': 'Position the QR code in the center of the camera',
    'qrForm.contactDataFilled': 'QR codes with contact data will be filled automatically',
    'qrForm.otherQRSaved': 'Other QR codes will be saved in notes',
    'qrForm.contactData': 'Contact Data',
    'qrForm.scanToFill': 'Scan a QR code to fill the data',
    'qrForm.nameRequired': 'Name',
    'qrForm.customerName': 'Customer name',
    'qrForm.phone': 'Phone',
    'qrForm.email': 'Email',
    'qrForm.tags': 'Tags',
    'qrForm.addTag': 'Add tag',
    'qrForm.notes': 'Notes',
    'qrForm.customerNotes': 'Notes about the customer...',
    'qrForm.saving': 'Saving...',
    'qrForm.saveContact': 'Save Contact',
    'qrForm.requiredFields': 'Required fields',
    'qrForm.namePhoneRequired': 'Name and phone are required.',
    'qrForm.contactAdded': 'Contact added!',
    'qrForm.contactAddedToList': 'was added to your contacts.',
    'qrForm.scanningTips': 'Tips for better scanning',
    'qrForm.goodLighting': 'Good lighting',
    'qrForm.useWellLit': 'Use in well-lit environments',
    'qrForm.adequateDistance': 'Adequate distance',
    'qrForm.maintain10to30cm': 'Maintain 10-30cm distance',
    'qrForm.cleanQR': 'Clean QR code',
    'qrForm.ensureReadable': 'Make sure it is readable',
    'qrForm.qrScanned': 'QR Code scanned!',
    'qrForm.fillDataBelow': 'Fill in the contact data below.',
    
    // Templates
    'templates.title': 'Message Templates',
    'templates.subtitle': 'Create and manage your reusable message templates',
    'templates.newTemplate': 'New template',
    'templates.totalTemplates': 'Total Templates',
    'templates.categories': 'Categories',
    'templates.mostUsed': 'Most Used',
    'templates.general': 'General',
    'templates.none': 'None',
    'templates.editTemplate': 'Edit template',
    'templates.createNewTemplate': 'Create new template',
    'templates.useVariables': 'Use variables with syntax: {{ variableName }}',
    'templates.templateName': 'Template name',
    'templates.templateNameExample': 'E.g.: Monday Promotion',
    'templates.category': 'Category',
    'templates.selectCategory': 'Select category',
    'templates.templateMessage': 'Template message',
    'templates.messageExample': 'E.g.: Hello {{name}}, enjoy our special offer {{offer}} valid until {{date}}!',
    'templates.variablesDetected': 'Variables detected:',
    'templates.modifying': 'Modifying...',
    'templates.creating': 'Creating...',
    'templates.modify': 'Modify',
    'templates.create': 'Create',
    'templates.cancel': 'Cancel',
    'templates.myTemplates': 'My Templates',
    'templates.manageTemplates': 'Manage your reusable message templates',
    'templates.noTemplates': 'No templates',
    'templates.createFirstTemplate': 'Create your first template or use our professional templates.',
    'templates.createTemplate': 'Create template',
    'templates.loadProTemplates': 'Load pro templates',
    'templates.variables': 'Variables:',
    'templates.copy': 'Copy',
    'templates.copied': 'Copied',
    'templates.copiedToClipboard': 'Template copied to clipboard',
    'templates.error': 'Error',
    'templates.fillRequired': 'Please fill all required fields',
    'templates.success': 'Success',
    'templates.templateModified': 'Template modified successfully',
    'templates.templateCreated': 'Template created successfully',
    'templates.templateDeleted': 'Template deleted successfully',
    'templates.defaultTemplatesAdded': 'Default templates added successfully',
    'templates.cannotSave': 'Unable to save template',
    'templates.cannotDelete': 'Unable to delete template',
    'templates.cannotLoadDefaults': 'Unable to load default templates',
    
    // Template Categories
    'templateCategories.general': 'General',
    'templateCategories.promotion': 'Promotion',
    'templateCategories.welcome': 'Welcome',
    'templateCategories.reminder': 'Reminder',
    'templateCategories.event': 'Event',
    'templateCategories.special_offer': 'Special Offer',
    'templateCategories.feedback': 'Feedback',
    
    // Not Found
    'notFound.title': '404',
    'notFound.message': 'Oops! Page not found',
    'notFound.returnHome': 'Return to Home',
  },
  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.plans': 'Prezzi',
    'nav.generateQr': 'Genera QR',
    'nav.dashboard': 'Dashboard',
    'nav.contacts': 'Contatti',
    'nav.campaigns': 'Campagne',
    'nav.templates': 'Modelli',
    'nav.login': 'Accedi',
    'nav.logout': 'Esci',
    
    // Auth
    'auth.hello': 'Ciao',
    'auth.loggedAs': 'Connesso come',
    'auth.user': 'Utente',
    
    // Plans page
    'plans.badge': 'Sistema di Marketing Premium',
    'plans.title': 'Rivoluziona il Marketing del Tuo Ristorante',
    'plans.subtitle': 'Cattura contatti, costruisci relazioni e aumenta le tue vendite con la nostra piattaforma completa di marketing digitale per ristoranti.',
    'plans.whyChoose': 'Perché scegliere la nostra piattaforma?',
    'plans.captureMore': 'Cattura Più Clienti',
    'plans.captureDesc': 'Trasforma i visitatori in contatti con QR code strategici',
    'plans.directComm': 'Comunicazione Diretta',
    'plans.directCommDesc': 'Invia campagne SMS personalizzate ai tuoi clienti',
    'plans.measurableResults': 'Risultati Misurabili',
    'plans.measurableDesc': 'Traccia le metriche e ottimizza le tue campagne marketing',
    'plans.singlePlan': 'Piano Unico, Funzionalità Complete',
    'plans.transformDesc': 'Tutto ciò di cui hai bisogno per trasformare il tuo ristorante',
    'plans.mostPopular': 'Più Popolare',
    'plans.professional': 'Piano Professionale',
    'plans.forRestaurants': 'Per i ristoranti che vogliono crescere',
    'plans.perMonth': '/mese',
    'plans.startNow': 'Inizia Ora',
    'plans.cancelAnytime': 'Cancella in qualsiasi momento • Support 24/7 • Nessun costo nascosto',
    'plans.joinRestaurants': 'Unisciti ai ristoranti che stanno già crescendo',
    'plans.contactIncrease': 'Aumento nella cattura di contatti',
    'plans.openRate': 'Tasso di apertura campagne SMS',
    'plans.customerReturn': 'Ritorno dei clienti',
    'plans.readyTransform': 'Pronto a trasformare il tuo ristorante?',
    'plans.seeResults': 'Inizia oggi e vedi i risultati in 30 giorni o meno',
    'plans.startTransformation': 'Inizia La Mia Trasformazione',
    
    // Features
    'features.qrCode': 'QR Code personalizzato per il tuo ristorante',
    'features.unlimitedCapture': 'Cattura illimitata di contatti clienti',
    'features.smsCompaigns': 'Campagne SMS professionali',
    'features.templates': 'Modelli di messaggi personalizzabili',
    'features.analytics': 'Analytics dettagliate delle campagne',
    'features.contactManagement': 'Gestione completa dei contatti',
    'features.prioritySupport': 'Supporto tecnico prioritario',
    'features.autoUpdates': 'Aggiornamenti automatici',
    
    // Footer
    'footer.features': 'Funzionalità',
    'footer.contactCollection': 'Raccolta contatti',
    'footer.automatedCampaigns': 'Campagne automatizzate',
    'footer.referralProgram': 'Programma di referral',
    'footer.detailedAnalytics': 'Analytics dettagliate',
    'footer.support': 'Supporto',
    'footer.documentation': 'Documentazione',
    'footer.contact': 'Contatto',
    'footer.faq': 'FAQ',
    'footer.onlineHelp': 'Aiuto online',
    'footer.allRights': 'Tutti i diritti riservati.',
    'footer.description': 'Aumenta i tuoi ricavi nei giorni di basso traffico con la nostra soluzione di fidelizzazione e marketing mirato.',
    
    // Home page
    'home.heroTitle': 'Potenzia il tuo ristorante nei giorni tranquilli',
    'home.heroSubtitle': 'Raccogli contatti tramite QR code e invia promozioni mirate per aumentare i tuoi ricavi fino al 40%.',
    'home.tryNow': 'Prova ora',
    'home.seeDemo': 'Vedi demo',
    'home.openRate': 'Tasso apertura SMS',
    'home.revenueIncrease': 'Aumento ricavi',
    'home.quickSetup': 'Configurazione rapida',
    'home.support': 'Supporto clienti',
    'home.innovative': 'Soluzione innovativa',
    'home.featuresTitle': 'Tutto quello di cui hai bisogno',
    'home.featuresSubtitle': 'Una soluzione completa per trasformare i tuoi giorni di basso traffico in opportunità di crescita.',
    'home.howItWorks': 'Come funziona',
    'home.simpleSteps': 'Semplice ed efficace in 3 passaggi',
    'home.ctaTitle': 'Pronto a potenziare il tuo ristorante?',
    'home.ctaSubtitle': 'Unisciti a centinaia di ristoratori che hanno già aumentato i loro ricavi.',
    'home.testFree': 'Testa gratis',
    'home.scheduleDemo': 'Programma demo',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Panoramica della tua attività e metriche di performance',
    'dashboard.overview': 'Panoramica',
    'dashboard.overviewTitle': 'Panoramica',
    'dashboard.overviewSubtitle': 'Dashboard principale del tuo DopplerDine',
    'dashboard.scanQr': 'Scansiona QR',
    'dashboard.newCampaign': 'Nuova Campagna',
    
    // Auth
    'auth.loginSubtitle': 'Accedi o crea il tuo account per iniziare',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Monitora le prestazioni delle tue campagne e contatti',
    'analytics.last7days': 'Ultimi 7 giorni',
    'analytics.last30days': 'Ultimi 30 giorni',
    'analytics.last90days': 'Ultimi 90 giorni',
    'analytics.lastYear': 'Ultimo anno',
    'analytics.refresh': 'Aggiorna',
    'analytics.totalCampaigns': 'Totale Campagne',
    'analytics.totalContacts': 'Totale Contatti',
    'analytics.messagesSent': 'Messaggi Inviati',
    'analytics.totalCost': 'Costo Totale',
    'analytics.selectedPeriod': 'Nel periodo selezionato',
    'analytics.newContactsAdded': 'Nuovi contatti aggiunti',
    'analytics.successRate': 'Tasso di successo',
    'analytics.campaignExpenses': 'Spese campagne',
    'analytics.sendTrend': 'Tendenza Invii',
    'analytics.sentVsDelivered': 'Ultimi 7 giorni - Inviati vs Consegnati',
    'analytics.sent': 'Inviati',
    'analytics.delivered': 'Consegnati',
    'analytics.campaignsByType': 'Campagne per Tipo',
    'analytics.typeDistribution': 'Distribuzione dei tipi di campagna',
    'analytics.campaignStatus': 'Stato delle Campagne',
    'analytics.currentState': 'Stato attuale delle campagne',
    'analytics.recentActivity': 'Attività Recente',
    'analytics.lastActions': 'Ultime azioni eseguite',
    'analytics.noActivity': 'Nessuna attività recente',
    'analytics.performance': 'Dettagli Prestazioni',
    'analytics.detailedMetrics': 'Metriche dettagliate di successo delle campagne',
    'analytics.deliveryRate': 'Tasso di Consegna',
    'analytics.costPerMessage': 'Costo per Messaggio (€)',
    'analytics.messagesPerContact': 'Messaggi per Contatto',
    'analytics.campaign': 'Campagna',
    'analytics.contact': 'Contatto',
    
    // Campaigns
    'campaigns.title': 'Campagne',
    'campaigns.subtitle': 'Gestisci le tue campagne di marketing automatizzate',
    'campaigns.newCampaign': 'Nuova campagna',
    'campaigns.createNew': 'Crea nuova campagna',
    'campaigns.configure': 'Configura la tua campagna promozionale automatizzata',
    'campaigns.useTemplate': 'Usa template (opzionale)',
    'campaigns.chooseTemplate': 'Scegli template esistente',
    'campaigns.createFromScratch': 'Crea da zero',
    'campaigns.templateSelected': 'Template selezionato. Puoi modificare il messaggio qui sotto.',
    'campaigns.campaignName': 'Nome campagna',
    'campaigns.campaignType': 'Tipo campagna',
    'campaigns.selectType': 'Seleziona tipo',
    'campaigns.templateVariables': 'Variabili template',
    'campaigns.variablesDescription': 'Queste variabili saranno sostituite nel messaggio finale.',
    'campaigns.promotionalMessage': 'Messaggio promozionale',
    'campaigns.writeMessage': 'Scrivi il tuo messaggio promozionale...',
    'campaigns.charactersForSMS': 'caratteri per SMS',
    'campaigns.previewWithVariables': 'Anteprima con variabili applicate sotto',
    'campaigns.finalMessagePreview': 'Anteprima messaggio finale:',
    'campaigns.scheduledDate': 'Data e ora invio (opzionale)',
    'campaigns.sendImmediately': 'Lascia vuoto per inviare immediatamente',
    'campaigns.twilioSending': 'Invio tramite Twilio',
    'campaigns.twilioConfigured': 'Configurazione Twilio già impostata',
    'campaigns.smsMessages': 'I messaggi SMS saranno inviati direttamente',
    'campaigns.whatsappMessages': 'I messaggi WhatsApp saranno inviati direttamente',
    'campaigns.twilioApiConfigured': 'API Twilio configurata nei segreti',
    'campaigns.creating': 'Creazione...',
    'campaigns.createCampaign': 'Crea campagna',
    'campaigns.cancel': 'Annulla',
    'campaigns.myCampaigns': 'Le mie campagne',
    'campaigns.manageCampaigns': 'Gestisci e monitora le tue campagne marketing',
    'campaigns.noCampaigns': 'Nessuna campagna',
    'campaigns.createFirstCampaign': 'Crea la tua prima campagna per iniziare a coinvolgere i tuoi clienti.',
    'campaigns.send': 'Invia',
    'campaigns.active': 'Attiva',
    'campaigns.sent': 'Inviata',
    'campaigns.scheduled': 'Programmata',
    'campaigns.draft': 'Bozza',
    'campaigns.scheduledFor': 'Programmata per',
    'campaigns.error': 'Errore',
    'campaigns.fillRequired': 'Compila tutti i campi obbligatori',
    'campaigns.success': 'Successo',
    'campaigns.campaignCreated': 'Campagna creata con successo',
    'campaigns.campaignSent': 'Campagna inviata con successo',
    'campaigns.campaignDeleted': 'Campagna eliminata con successo',
    'campaigns.cannotCreate': 'Impossibile creare la campagna',
    'campaigns.cannotSend': 'Impossibile inviare la campagna',
    'campaigns.cannotDelete': 'Impossibile eliminare la campagna',
    
    // Contacts
    'contacts.title': 'Contatti',
    'contacts.subtitle': 'Gestisci la tua base clienti',
    'contacts.scanQR': 'Scansiona QR',
    'contacts.newContact': 'Nuovo Contatto',
    'contacts.total': 'Totale',
    'contacts.viaQRCode': 'Via QR Code',
    'contacts.withEmail': 'Con Email',
    'contacts.thisWeek': 'Questa Settimana',
    'contacts.searchPlaceholder': 'Cerca per nome, telefono o email...',
    'contacts.allSources': 'Tutte le fonti',
    'contacts.manual': 'Manuale',
    'contacts.import': 'Importazione',
    'contacts.export': 'Esporta',
    'contacts.contactsFound': 'contatti',
    'contacts.noContactsFound': 'Nessun contatto trovato',
    'contacts.selectAll': 'Seleziona tutti',
    'contacts.deselectAll': 'Deseleziona tutti',
    'contacts.addedOn': 'Aggiunto il',
    'contacts.confirmDelete': 'Conferma eliminazione',
    'contacts.deleteConfirmation': 'Sei sicuro di voler eliminare il contatto',
    'contacts.actionCannotBeUndone': 'Questa azione non può essere annullata.',
    'contacts.cancel': 'Annulla',
    'contacts.delete': 'Elimina',
    'contacts.noContactsFoundDesc': 'Nessun contatto trovato',
    'contacts.adjustFilters': 'Prova ad aggiustare i filtri o i termini di ricerca',
    'contacts.startScanning': 'Inizia scansionando QR code o aggiungendo contatti manualmente',
    'contacts.scanQRCode': 'Scansiona QR Code',
    'contacts.addContact': 'Aggiungi Contatto',
    
    // Public Form
    'publicForm.loading': 'Caricamento...',
    'publicForm.error': 'Errore',
    'publicForm.couldNotLoad': 'Impossibile caricare le informazioni del ristorante.',
    'publicForm.invalidQR': 'QR Code non valido',
    'publicForm.invalidOrExpired': 'Questo QR code non è valido o è scaduto.',
    'publicForm.unexpectedError': 'Si è verificato un errore imprevisto.',
    'publicForm.leaveData': 'Lascia i tuoi dati per ricevere offerte esclusive!',
    'publicForm.fullName': 'Nome completo',
    'publicForm.yourName': 'Il tuo nome',
    'publicForm.whatsappPhone': 'WhatsApp/Telefono',
    'publicForm.emailOptional': 'Email (opzionale)',
    'publicForm.commentsOptional': 'Commenti (opzionale)',
    'publicForm.leaveComment': 'Lascia un commento...',
    'publicForm.saving': 'Salvataggio...',
    'publicForm.saveData': 'Salva i miei dati',
    'publicForm.dataSecure': 'I tuoi dati sono sicuri e saranno utilizzati solo per offerte speciali di',
    'publicForm.success': 'Successo!',
    'publicForm.thankYou': 'Grazie',
    'publicForm.dataSaved': 'I tuoi dati sono stati salvati con successo.',
    'publicForm.cannotSave': 'Impossibile salvare i tuoi dati. Riprova.',
    'publicForm.restaurantNotFound': 'Ristorante non trovato',
    
    // QR Form
    'qrForm.title': 'Scanner QR',
    'qrForm.subtitle': 'Scansiona QR code per aggiungere nuovi contatti',
    'qrForm.cameraScanner': 'Scanner Fotocamera',
    'qrForm.permissionDenied': 'Permesso fotocamera negato',
    'qrForm.clickToStart': 'Clicca "Avvia Scanner" per iniziare',
    'qrForm.pointToQR': 'Punta verso un QR code',
    'qrForm.stopScanner': 'Ferma Scanner',
    'qrForm.startScanner': 'Avvia Scanner',
    'qrForm.reset': 'Reimposta',
    'qrForm.qrDetected': 'QR Code rilevato:',
    'qrForm.positionQR': 'Posiziona il QR code al centro della fotocamera',
    'qrForm.contactDataFilled': 'I QR code con dati di contatto saranno compilati automaticamente',
    'qrForm.otherQRSaved': 'Altri QR code saranno salvati nelle note',
    'qrForm.contactData': 'Dati Contatto',
    'qrForm.scanToFill': 'Scansiona un QR code per compilare i dati',
    'qrForm.nameRequired': 'Nome',
    'qrForm.customerName': 'Nome cliente',
    'qrForm.phone': 'Telefono',
    'qrForm.email': 'Email',
    'qrForm.tags': 'Tag',
    'qrForm.addTag': 'Aggiungi tag',
    'qrForm.notes': 'Note',
    'qrForm.customerNotes': 'Note sul cliente...',
    'qrForm.saving': 'Salvataggio...',
    'qrForm.saveContact': 'Salva Contatto',
    'qrForm.requiredFields': 'Campi obbligatori',
    'qrForm.namePhoneRequired': 'Nome e telefono sono obbligatori.',
    'qrForm.contactAdded': 'Contatto aggiunto!',
    'qrForm.contactAddedToList': 'è stato aggiunto ai tuoi contatti.',
    'qrForm.scanningTips': 'Consigli per una migliore scansione',
    'qrForm.goodLighting': 'Buona illuminazione',
    'qrForm.useWellLit': 'Usa in ambienti ben illuminati',
    'qrForm.adequateDistance': 'Distanza adeguata',
    'qrForm.maintain10to30cm': 'Mantieni 10-30cm di distanza',
    'qrForm.cleanQR': 'QR code pulito',
    'qrForm.ensureReadable': 'Assicurati che sia leggibile',
    'qrForm.qrScanned': 'QR Code scansionato!',
    'qrForm.fillDataBelow': 'Compila i dati del contatto qui sotto.',
    
    // Templates
    'templates.title': 'Template Messaggi',
    'templates.subtitle': 'Crea e gestisci i tuoi template di messaggi riutilizzabili',
    'templates.newTemplate': 'Nuovo template',
    'templates.totalTemplates': 'Totale Template',
    'templates.categories': 'Categorie',
    'templates.mostUsed': 'Più Utilizzato',
    'templates.general': 'Generale',
    'templates.none': 'Nessuno',
    'templates.editTemplate': 'Modifica template',
    'templates.createNewTemplate': 'Crea nuovo template',
    'templates.useVariables': 'Usa variabili con sintassi: {{ nomeVariabile }}',
    'templates.templateName': 'Nome template',
    'templates.templateNameExample': 'Es.: Promozione Lunedì',
    'templates.category': 'Categoria',
    'templates.selectCategory': 'Seleziona categoria',
    'templates.templateMessage': 'Messaggio template',
    'templates.messageExample': 'Es.: Ciao {{nome}}, approfitta della nostra offerta speciale {{offerta}} valida fino al {{data}}!',
    'templates.variablesDetected': 'Variabili rilevate:',
    'templates.modifying': 'Modifica...',
    'templates.creating': 'Creazione...',
    'templates.modify': 'Modifica',
    'templates.create': 'Crea',
    'templates.cancel': 'Annulla',
    'templates.myTemplates': 'I Miei Template',
    'templates.manageTemplates': 'Gestisci i tuoi template di messaggi riutilizzabili',
    'templates.noTemplates': 'Nessun template',
    'templates.createFirstTemplate': 'Crea il tuo primo template o usa i nostri template professionali.',
    'templates.createTemplate': 'Crea template',
    'templates.loadProTemplates': 'Carica template pro',
    'templates.variables': 'Variabili:',
    'templates.copy': 'Copia',
    'templates.copied': 'Copiato',
    'templates.copiedToClipboard': 'Template copiato negli appunti',
    'templates.error': 'Errore',
    'templates.fillRequired': 'Compila tutti i campi obbligatori',
    'templates.success': 'Successo',
    'templates.templateModified': 'Template modificato con successo',
    'templates.templateCreated': 'Template creato con successo',
    'templates.templateDeleted': 'Template eliminato con successo',
    'templates.defaultTemplatesAdded': 'Template predefiniti aggiunti con successo',
    'templates.cannotSave': 'Impossibile salvare il template',
    'templates.cannotDelete': 'Impossibile eliminare il template',
    'templates.cannotLoadDefaults': 'Impossibile caricare i template predefiniti',
    
    // Template Categories
    'templateCategories.general': 'Generale',
    'templateCategories.promotion': 'Promozione',
    'templateCategories.welcome': 'Benvenuto',
    'templateCategories.reminder': 'Promemoria',
    'templateCategories.event': 'Evento',
    'templateCategories.special_offer': 'Offerta Speciale',
    'templateCategories.feedback': 'Feedback',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.plans': 'Preise',
    'nav.generateQr': 'QR Generieren',
    'nav.dashboard': 'Dashboard',
    'nav.contacts': 'Kontakte',
    'nav.campaigns': 'Kampagnen',
    'nav.templates': 'Vorlagen',
    'nav.login': 'Anmelden',
    'nav.logout': 'Abmelden',
    
    // Auth
    'auth.hello': 'Hallo',
    'auth.loggedAs': 'Angemeldet als',
    'auth.user': 'Benutzer',
    
    // Plans page
    'plans.badge': 'Premium Marketing System',
    'plans.title': 'Revolutionieren Sie Ihr Restaurant Marketing',
    'plans.subtitle': 'Erfassen Sie Kontakte, bauen Sie Beziehungen auf und steigern Sie Ihre Verkäufe mit unserer kompletten digitalen Marketing-Plattform für Restaurants.',
    'plans.whyChoose': 'Warum unsere Plattform wählen?',
    'plans.captureMore': 'Mehr Kunden Erfassen',
    'plans.captureDesc': 'Verwandeln Sie Besucher in Kontakte mit strategischen QR-Codes',
    'plans.directComm': 'Direkte Kommunikation',
    'plans.directCommDesc': 'Senden Sie personalisierte SMS-Kampagnen an Ihre Kunden',
    'plans.measurableResults': 'Messbare Ergebnisse',
    'plans.measurableDesc': 'Verfolgen Sie Metriken und optimieren Sie Ihre Marketing-Kampagnen',
    'plans.singlePlan': 'Ein Plan, Vollständige Funktionen',
    'plans.transformDesc': 'Alles was Sie brauchen, um Ihr Restaurant zu transformieren',
    'plans.mostPopular': 'Am Beliebtesten',
    'plans.professional': 'Professional Plan',
    'plans.forRestaurants': 'Für Restaurants, die wachsen wollen',
    'plans.perMonth': '/Monat',
    'plans.startNow': 'Jetzt Starten',
    'plans.cancelAnytime': 'Jederzeit kündbar • 24/7 Support • Keine versteckten Gebühren',
    'plans.joinRestaurants': 'Schließen Sie sich Restaurants an, die bereits wachsen',
    'plans.contactIncrease': 'Steigerung der Kontakterfassung',
    'plans.openRate': 'SMS-Kampagnen Öffnungsrate',
    'plans.customerReturn': 'Kundenrückkehr',
    'plans.readyTransform': 'Bereit, Ihr Restaurant zu transformieren?',
    'plans.seeResults': 'Starten Sie heute und sehen Sie Ergebnisse in 30 Tagen oder weniger',
    'plans.startTransformation': 'Meine Transformation Starten',
    
    // Features
    'features.qrCode': 'Benutzerdefinierter QR-Code für Ihr Restaurant',
    'features.unlimitedCapture': 'Unbegrenzte Kundenkontakt-Erfassung',
    'features.smsCompaigns': 'Professionelle SMS-Kampagnen',
    'features.templates': 'Anpassbare Nachrichten-Vorlagen',
    'features.analytics': 'Detaillierte Kampagnen-Analytics',
    'features.contactManagement': 'Vollständige Kontaktverwaltung',
    'features.prioritySupport': 'Priority technischer Support',
    'features.autoUpdates': 'Automatische Updates',
    
    // Footer
    'footer.features': 'Funktionen',
    'footer.contactCollection': 'Kontaktsammlung',
    'footer.automatedCampaigns': 'Automatisierte Kampagnen',
    'footer.referralProgram': 'Empfehlungsprogramm',
    'footer.detailedAnalytics': 'Detaillierte Analytics',
    'footer.support': 'Support',
    'footer.documentation': 'Dokumentation',
    'footer.contact': 'Kontakt',
    'footer.faq': 'FAQ',
    'footer.onlineHelp': 'Online-Hilfe',
    'footer.allRights': 'Alle Rechte vorbehalten.',
    'footer.description': 'Steigern Sie Ihren Umsatz an schwächeren Tagen mit unserer Kundenbindungs- und gezielten Marketing-Lösung.',
    
    // Home page
    'home.heroTitle': 'Boosten Sie Ihr Restaurant an ruhigen Tagen',
    'home.heroSubtitle': 'Sammeln Sie Kontakte über QR-Code und senden Sie gezielte Aktionen, um Ihren Umsatz um bis zu 40% zu steigern.',
    'home.tryNow': 'Jetzt testen',
    'home.seeDemo': 'Demo ansehen',
    'home.openRate': 'SMS-Öffnungsrate',
    'home.revenueIncrease': 'Umsatzsteigerung',
    'home.quickSetup': 'Schnelle Einrichtung',
    'home.support': 'Kundensupport',
    'home.innovative': 'Innovative Lösung',
    'home.featuresTitle': 'Alles was Sie brauchen',
    'home.featuresSubtitle': 'Eine komplette Lösung, um Ihre schwachen Tage in Wachstumschancen zu verwandeln.',
    'home.howItWorks': 'Wie es funktioniert',
    'home.simpleSteps': 'Einfach und effektiv in 3 Schritten',
    'home.ctaTitle': 'Bereit, Ihr Restaurant zu boosten?',
    'home.ctaSubtitle': 'Schließen Sie sich Hunderten von Gastronomen an, die bereits ihre Umsätze gesteigert haben.',
    'home.testFree': 'Kostenlos testen',
    'home.scheduleDemo': 'Demo planen',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Überblick über Ihr Unternehmen und Leistungsmetriken',
    'dashboard.overview': 'Überblick',
    'dashboard.overviewTitle': 'Überblick',
    'dashboard.overviewSubtitle': 'Haupt-Dashboard Ihres DopplerDine',
    'dashboard.scanQr': 'QR scannen',
    'dashboard.newCampaign': 'Neue Kampagne',
    
    // Auth
    'auth.loginSubtitle': 'Melden Sie sich an oder erstellen Sie Ihr Konto, um zu beginnen',
    
    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Verfolgen Sie die Leistung Ihrer Kampagnen und Kontakte',
    'analytics.last7days': 'Letzten 7 Tage',
    'analytics.last30days': 'Letzten 30 Tage',
    'analytics.last90days': 'Letzten 90 Tage',
    'analytics.lastYear': 'Letztes Jahr',
    'analytics.refresh': 'Aktualisieren',
    'analytics.totalCampaigns': 'Gesamte Kampagnen',
    'analytics.totalContacts': 'Gesamte Kontakte',
    'analytics.messagesSent': 'Gesendete Nachrichten',
    'analytics.totalCost': 'Gesamtkosten',
    'analytics.selectedPeriod': 'Im gewählten Zeitraum',
    'analytics.newContactsAdded': 'Neue Kontakte hinzugefügt',
    'analytics.successRate': 'Erfolgsrate',
    'analytics.campaignExpenses': 'Kampagnenausgaben',
    'analytics.sendTrend': 'Versendtrend',
    'analytics.sentVsDelivered': 'Letzten 7 Tage - Gesendet vs Zugestellt',
    'analytics.sent': 'Gesendet',
    'analytics.delivered': 'Zugestellt',
    'analytics.campaignsByType': 'Kampagnen nach Typ',
    'analytics.typeDistribution': 'Verteilung der Kampagnentypen',
    'analytics.campaignStatus': 'Kampagnenstatus',
    'analytics.currentState': 'Aktueller Zustand der Kampagnen',
    'analytics.recentActivity': 'Kürzliche Aktivität',
    'analytics.lastActions': 'Zuletzt durchgeführte Aktionen',
    'analytics.noActivity': 'Keine kürzliche Aktivität',
    'analytics.performance': 'Leistungsdetails',
    'analytics.detailedMetrics': 'Detaillierte Erfolgsmetriken der Kampagnen',
    'analytics.deliveryRate': 'Zustellungsrate',
    'analytics.costPerMessage': 'Kosten pro Nachricht (€)',
    'analytics.messagesPerContact': 'Nachrichten pro Kontakt',
    'analytics.campaign': 'Kampagne',
    'analytics.contact': 'Kontakt',
    
    // Campaigns
    'campaigns.title': 'Kampagnen',
    'campaigns.subtitle': 'Verwalten Sie Ihre automatisierten Marketing-Kampagnen',
    'campaigns.newCampaign': 'Neue Kampagne',
    'campaigns.createNew': 'Neue Kampagne erstellen',
    'campaigns.configure': 'Konfigurieren Sie Ihre automatisierte Werbekampagne',
    'campaigns.useTemplate': 'Vorlage verwenden (optional)',
    'campaigns.chooseTemplate': 'Bestehende Vorlage auswählen',
    'campaigns.createFromScratch': 'Von Grund auf erstellen',
    'campaigns.templateSelected': 'Vorlage ausgewählt. Sie können die Nachricht unten bearbeiten.',
    'campaigns.campaignName': 'Kampagnenname',
    'campaigns.campaignType': 'Kampagnentyp',
    'campaigns.selectType': 'Typ auswählen',
    'campaigns.templateVariables': 'Vorlagenvariablen',
    'campaigns.variablesDescription': 'Diese Variablen werden in der finalen Nachricht ersetzt.',
    'campaigns.promotionalMessage': 'Werbenachricht',
    'campaigns.writeMessage': 'Schreiben Sie Ihre Werbenachricht...',
    'campaigns.charactersForSMS': 'Zeichen für SMS',
    'campaigns.previewWithVariables': 'Vorschau mit angewendeten Variablen unten',
    'campaigns.finalMessagePreview': 'Finale Nachrichtenvorschau:',
    'campaigns.scheduledDate': 'Sendedatum und -zeit (optional)',
    'campaigns.sendImmediately': 'Leer lassen für sofortigen Versand',
    'campaigns.twilioSending': 'Versand über Twilio',
    'campaigns.twilioConfigured': 'Twilio-Konfiguration bereits eingerichtet',
    'campaigns.smsMessages': 'SMS-Nachrichten werden direkt gesendet',
    'campaigns.whatsappMessages': 'WhatsApp-Nachrichten werden direkt gesendet',
    'campaigns.twilioApiConfigured': 'Twilio-API in Geheimnissen konfiguriert',
    'campaigns.creating': 'Erstellen...',
    'campaigns.createCampaign': 'Kampagne erstellen',
    'campaigns.cancel': 'Abbrechen',
    'campaigns.myCampaigns': 'Meine Kampagnen',
    'campaigns.manageCampaigns': 'Verwalten und verfolgen Sie Ihre Marketing-Kampagnen',
    'campaigns.noCampaigns': 'Keine Kampagnen',
    'campaigns.createFirstCampaign': 'Erstellen Sie Ihre erste Kampagne, um Ihre Kunden zu erreichen.',
    'campaigns.send': 'Senden',
    'campaigns.active': 'Aktiv',
    'campaigns.sent': 'Gesendet',
    'campaigns.scheduled': 'Geplant',
    'campaigns.draft': 'Entwurf',
    'campaigns.scheduledFor': 'Geplant für',
    'campaigns.error': 'Fehler',
    'campaigns.fillRequired': 'Bitte füllen Sie alle Pflichtfelder aus',
    'campaigns.success': 'Erfolg',
    'campaigns.campaignCreated': 'Kampagne erfolgreich erstellt',
    'campaigns.campaignSent': 'Kampagne erfolgreich gesendet',
    'campaigns.campaignDeleted': 'Kampagne erfolgreich gelöscht',
    'campaigns.cannotCreate': 'Kampagne kann nicht erstellt werden',
    'campaigns.cannotSend': 'Kampagne kann nicht gesendet werden',
    'campaigns.cannotDelete': 'Kampagne kann nicht gelöscht werden',
    
    // Contacts
    'contacts.title': 'Kontakte',
    'contacts.subtitle': 'Verwalten Sie Ihren Kundenstamm',
    'contacts.scanQR': 'QR scannen',
    'contacts.newContact': 'Neuer Kontakt',
    'contacts.total': 'Gesamt',
    'contacts.viaQRCode': 'Via QR-Code',
    'contacts.withEmail': 'Mit E-Mail',
    'contacts.thisWeek': 'Diese Woche',
    'contacts.searchPlaceholder': 'Suchen nach Name, Telefon oder E-Mail...',
    'contacts.allSources': 'Alle Quellen',
    'contacts.manual': 'Manuell',
    'contacts.import': 'Import',
    'contacts.export': 'Exportieren',
    'contacts.contactsFound': 'Kontakte',
    'contacts.noContactsFound': 'Keine Kontakte gefunden',
    'contacts.selectAll': 'Alle auswählen',
    'contacts.deselectAll': 'Alle abwählen',
    'contacts.addedOn': 'Hinzugefügt am',
    'contacts.confirmDelete': 'Löschung bestätigen',
    'contacts.deleteConfirmation': 'Sind Sie sicher, dass Sie den Kontakt löschen möchten',
    'contacts.actionCannotBeUndone': 'Diese Aktion kann nicht rückgängig gemacht werden.',
    'contacts.cancel': 'Abbrechen',
    'contacts.delete': 'Löschen',
    'contacts.noContactsFoundDesc': 'Keine Kontakte gefunden',
    'contacts.adjustFilters': 'Versuchen Sie, Filter oder Suchbegriffe anzupassen',
    'contacts.startScanning': 'Beginnen Sie mit dem Scannen von QR-Codes oder dem manuellen Hinzufügen von Kontakten',
    'contacts.scanQRCode': 'QR-Code scannen',
    'contacts.addContact': 'Kontakt hinzufügen',
    
    // Public Form
    'publicForm.loading': 'Laden...',
    'publicForm.error': 'Fehler',
    'publicForm.couldNotLoad': 'Restaurantinformationen konnten nicht geladen werden.',
    'publicForm.invalidQR': 'Ungültiger QR-Code',
    'publicForm.invalidOrExpired': 'Dieser QR-Code ist nicht gültig oder abgelaufen.',
    'publicForm.unexpectedError': 'Ein unerwarteter Fehler ist aufgetreten.',
    'publicForm.leaveData': 'Hinterlassen Sie Ihre Daten für exklusive Angebote!',
    'publicForm.fullName': 'Vollständiger Name',
    'publicForm.yourName': 'Ihr Name',
    'publicForm.whatsappPhone': 'WhatsApp/Telefon',
    'publicForm.emailOptional': 'E-Mail (optional)',
    'publicForm.commentsOptional': 'Kommentare (optional)',
    'publicForm.leaveComment': 'Hinterlassen Sie einen Kommentar...',
    'publicForm.saving': 'Speichern...',
    'publicForm.saveData': 'Meine Daten speichern',
    'publicForm.dataSecure': 'Ihre Daten sind sicher und werden nur für spezielle Angebote von',
    'publicForm.success': 'Erfolg!',
    'publicForm.thankYou': 'Danke',
    'publicForm.dataSaved': 'Ihre Daten wurden erfolgreich gespeichert.',
    'publicForm.cannotSave': 'Daten konnten nicht gespeichert werden. Bitte versuchen Sie es erneut.',
    'publicForm.restaurantNotFound': 'Restaurant nicht gefunden',
    
    // QR Form
    'qrForm.title': 'QR-Scanner',
    'qrForm.subtitle': 'QR-Codes scannen, um neue Kontakte hinzuzufügen',
    'qrForm.cameraScanner': 'Kamera-Scanner',
    'qrForm.permissionDenied': 'Kameraberechtigung verweigert',
    'qrForm.clickToStart': 'Klicken Sie auf "Scanner starten", um zu beginnen',
    'qrForm.pointToQR': 'Auf einen QR-Code zeigen',
    'qrForm.stopScanner': 'Scanner stoppen',
    'qrForm.startScanner': 'Scanner starten',
    'qrForm.reset': 'Zurücksetzen',
    'qrForm.qrDetected': 'QR-Code erkannt:',
    'qrForm.positionQR': 'Positionieren Sie den QR-Code in der Mitte der Kamera',
    'qrForm.contactDataFilled': 'QR-Codes mit Kontaktdaten werden automatisch ausgefüllt',
    'qrForm.otherQRSaved': 'Andere QR-Codes werden in den Notizen gespeichert',
    'qrForm.contactData': 'Kontaktdaten',
    'qrForm.scanToFill': 'Scannen Sie einen QR-Code, um die Daten zu füllen',
    'qrForm.nameRequired': 'Name',
    'qrForm.customerName': 'Kundenname',
    'qrForm.phone': 'Telefon',
    'qrForm.email': 'E-Mail',
    'qrForm.tags': 'Tags',
    'qrForm.addTag': 'Tag hinzufügen',
    'qrForm.notes': 'Notizen',
    'qrForm.customerNotes': 'Notizen über den Kunden...',
    'qrForm.saving': 'Speichern...',
    'qrForm.saveContact': 'Kontakt speichern',
    'qrForm.requiredFields': 'Pflichtfelder',
    'qrForm.namePhoneRequired': 'Name und Telefon sind erforderlich.',
    'qrForm.contactAdded': 'Kontakt hinzugefügt!',
    'qrForm.contactAddedToList': 'wurde zu Ihren Kontakten hinzugefügt.',
    'qrForm.scanningTips': 'Tipps für besseres Scannen',
    'qrForm.goodLighting': 'Gute Beleuchtung',
    'qrForm.useWellLit': 'In gut beleuchteten Umgebungen verwenden',
    'qrForm.adequateDistance': 'Angemessene Entfernung',
    'qrForm.maintain10to30cm': '10-30cm Abstand halten',
    'qrForm.cleanQR': 'Sauberer QR-Code',
    'qrForm.ensureReadable': 'Stellen Sie sicher, dass er lesbar ist',
    'qrForm.qrScanned': 'QR-Code gescannt!',
    'qrForm.fillDataBelow': 'Füllen Sie die Kontaktdaten unten aus.',
    
    // Templates
    'templates.title': 'Nachrichten-Vorlagen',
    'templates.subtitle': 'Erstellen und verwalten Sie Ihre wiederverwendbaren Nachrichten-Vorlagen',
    'templates.newTemplate': 'Neue Vorlage',
    'templates.totalTemplates': 'Gesamte Vorlagen',
    'templates.categories': 'Kategorien',
    'templates.mostUsed': 'Am meisten verwendet',
    'templates.general': 'Allgemein',
    'templates.none': 'Keine',
    'templates.editTemplate': 'Vorlage bearbeiten',
    'templates.createNewTemplate': 'Neue Vorlage erstellen',
    'templates.useVariables': 'Verwenden Sie Variablen mit Syntax: {{ variableName }}',
    'templates.templateName': 'Vorlagenname',
    'templates.templateNameExample': 'Z.B.: Montag-Promotion',
    'templates.category': 'Kategorie',
    'templates.selectCategory': 'Kategorie auswählen',
    'templates.templateMessage': 'Vorlagennachricht',
    'templates.messageExample': 'Z.B.: Hallo {{name}}, genießen Sie unser spezielles Angebot {{offer}} gültig bis {{date}}!',
    'templates.variablesDetected': 'Erkannte Variablen:',
    'templates.modifying': 'Bearbeiten...',
    'templates.creating': 'Erstellen...',
    'templates.modify': 'Bearbeiten',
    'templates.create': 'Erstellen',
    'templates.cancel': 'Abbrechen',
    'templates.myTemplates': 'Meine Vorlagen',
    'templates.manageTemplates': 'Verwalten Sie Ihre wiederverwendbaren Nachrichten-Vorlagen',
    'templates.noTemplates': 'Keine Vorlagen',
    'templates.createFirstTemplate': 'Erstellen Sie Ihre erste Vorlage oder verwenden Sie unsere professionellen Vorlagen.',
    'templates.createTemplate': 'Vorlage erstellen',
    'templates.loadProTemplates': 'Pro-Vorlagen laden',
    'templates.variables': 'Variablen:',
    'templates.copy': 'Kopieren',
    'templates.copied': 'Kopiert',
    'templates.copiedToClipboard': 'Vorlage in Zwischenablage kopiert',
    'templates.error': 'Fehler',
    'templates.fillRequired': 'Bitte füllen Sie alle Pflichtfelder aus',
    'templates.success': 'Erfolg',
    'templates.templateModified': 'Vorlage erfolgreich bearbeitet',
    'templates.templateCreated': 'Vorlage erfolgreich erstellt',
    'templates.templateDeleted': 'Vorlage erfolgreich gelöscht',
    'templates.defaultTemplatesAdded': 'Standard-Vorlagen erfolgreich hinzugefügt',
    'templates.cannotSave': 'Vorlage kann nicht gespeichert werden',
    'templates.cannotDelete': 'Vorlage kann nicht gelöscht werden',
    'templates.cannotLoadDefaults': 'Standard-Vorlagen können nicht geladen werden',
    
    // Template Categories
    'templateCategories.general': 'Allgemein',
    'templateCategories.promotion': 'Promotion',
    'templateCategories.welcome': 'Willkommen',
    'templateCategories.reminder': 'Erinnerung',
    'templateCategories.event': 'Veranstaltung',
    'templateCategories.special_offer': 'Sonderangebot',
    'templateCategories.feedback': 'Feedback',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('fr');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && ['fr', 'en', 'it', 'de'].includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};