import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'pt' | 'en' | 'fr' | 'it' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.generateQr': 'Gerar QR',
    'nav.dashboard': 'Dashboard',
    'nav.contacts': 'Contatos', 
    'nav.campaigns': 'Campanhas',
    'nav.templates': 'Templates',
    'nav.analytics': 'Analytics',
    'nav.plans': 'Planos',
    'nav.login': 'Entrar',
    'nav.logout': 'Sair',

    // Auth
    'auth.hello': 'Olá',
    'auth.loggedAs': 'Logado como',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Visão geral do seu restaurante',
    'dashboard.totalContacts': 'Total de Contatos',
    'dashboard.activeCampaigns': 'Campanhas Ativas',
    'dashboard.messagesSent': 'Mensagens Enviadas',
    'dashboard.monthlyGrowth': 'Crescimento Mensal',
    'dashboard.quickActions': 'Ações Rápidas',
    'dashboard.newCampaign': 'Nova Campanha',
    'dashboard.newCampaignDesc': 'Criar campanha de marketing',
    'dashboard.manageContacts': 'Gerenciar Contatos',
    'dashboard.manageContactsDesc': 'Ver e editar seus contatos',
    'dashboard.recentContacts': 'Contatos Recentes',
    'dashboard.noContactsYet': 'Nenhum contato ainda',
    'dashboard.recentCampaigns': 'Campanhas Recentes',
    'dashboard.noCampaignsYet': 'Nenhuma campanha ainda',
    'dashboard.overview': 'Visão Geral',
    'dashboard.overviewTitle': 'Visão Geral',
    'dashboard.overviewSubtitle': 'Acompanhe o desempenho do seu negócio',
    'dashboard.scanQr': 'Escanear QR',
    'dashboard.thisWeek': 'esta semana',
    'dashboard.total': 'total',
    'dashboard.conversionRate': 'Taxa de Conversão',
    'dashboard.last30Days': 'Últimos 30 dias',
    'dashboard.uniqueQr': 'QR Único',
    'dashboard.yourAccessCode': 'Seu código de acesso',
    'dashboard.recentCampaignsDesc': 'Suas campanhas mais recentes',
    'dashboard.recentContactsDesc': 'Contatos adicionados recentemente',
    'dashboard.quickActionsDesc': 'Ações rápidas para gerenciar seu negócio',
    'dashboard.captureContact': 'Capturar Contato',
    'dashboard.captureContactDesc': 'Escaneie QR codes para adicionar contatos',
    'dashboard.newCampaignAction': 'Nova Campanha',

    // Campaign Status

    // Campaign Status
    'campaign.status.draft': 'Rascunho',
    'campaign.status.scheduled': 'Agendada',
    'campaign.status.sending': 'Enviando',
    'campaign.status.sent': 'Enviada',
    'campaign.status.completed': 'Concluída',
    'campaign.status.failed': 'Falhou',
    'campaign.status.active': 'Ativa',

    // Footer
    'footer.description': 'Plataforma completa de marketing para restaurantes com coleta de contatos e campanhas automatizadas.',
    'footer.features': 'Funcionalidades',
    'footer.contactCollection': 'Coleta de Contatos',
    'footer.automatedCampaigns': 'Campanhas Automatizadas',
    'footer.referralProgram': 'Programa de Indicação',
    'footer.detailedAnalytics': 'Analytics Detalhado',
    'footer.support': 'Suporte',
    'footer.documentation': 'Documentação',
    'footer.contact': 'Contato',
    'footer.faq': 'FAQ',
    'footer.onlineHelp': 'Ajuda Online',
    'footer.allRights': 'Todos os direitos reservados.',

    // Contact Sources
    'contact.source.qr': 'QR Code',
    'contact.source.manual': 'Manual',
    'contact.source.import': 'Importação',
    'contact.source.api': 'API',

    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Acompanhe o desempenho das suas campanhas e contatos',
    'analytics.refresh': 'Atualizar',
    'analytics.timeRange.7d': 'Últimos 7 dias',
    'analytics.timeRange.30d': 'Últimos 30 dias',
    'analytics.timeRange.90d': 'Últimos 90 dias',
    'analytics.timeRange.365d': 'Último ano',
    'analytics.campaigns': 'Campanhas',
    'analytics.sent': 'Enviadas',
    'analytics.contacts': 'Contatos',
    'analytics.cost': 'Custo',
    'analytics.inPeriod': 'No período',
    'analytics.success': 'sucesso',
    'analytics.newContacts': 'Novos contatos',
    'analytics.sendTrend': 'Tendência de Envios',
    'analytics.campaignTypes': 'Tipos de Campanha',
    'analytics.distributionByType': 'Distribuição por tipo',
    'analytics.performanceMetrics': 'Métricas de Performance',
    'analytics.keySuccessIndicators': 'Indicadores chave de sucesso',
    'analytics.deliveryRate': 'Taxa de Entrega',
    'analytics.costPerMessage': 'Custo por Mensagem (R$)',
    'analytics.messagesPerContact': 'Mensagens por Contato',
    'analytics.recentActivity': 'Atividade Recente',
    'analytics.lastActions': 'Últimas ações realizadas',
    'analytics.noRecentActivity': 'Nenhuma atividade recente',
    'analytics.sent.chart': 'Enviadas',
    'analytics.delivered.chart': 'Entregues',
    'analytics.campaign.label': 'Campanha',
    'analytics.contact.label': 'Contato',
    'analytics.status.draft': 'Rascunho',
    'analytics.status.scheduled': 'Agendada',
    'analytics.status.sending': 'Enviando',
    'analytics.status.completed': 'Concluída',
    'analytics.status.failed': 'Falhou',
    'analytics.type.sms': 'SMS',
    'analytics.type.email': 'Email',
    'analytics.type.whatsapp': 'WhatsApp',
    'analytics.last7days': 'Últimos 7 dias',
    'analytics.last30days': 'Últimos 30 dias',
    'analytics.last90days': 'Últimos 90 dias',
    'analytics.lastYear': 'Último ano',
    'analytics.totalCampaigns': 'Total de Campanhas',
    'analytics.selectedPeriod': 'No período selecionado',
    'analytics.totalContacts': 'Total de Contatos',
    'analytics.newContactsAdded': 'Novos contatos adicionados',
    'analytics.messagesSent': 'Mensagens Enviadas',
    'analytics.successRate': 'Taxa de sucesso',
    'analytics.totalCost': 'Custo Total',
    'analytics.campaignExpenses': 'Gastos com campanhas',
    'analytics.sentVsDelivered': 'Enviadas vs Entregues',
    'analytics.campaignsByType': 'Campanhas por Tipo',
    'analytics.typeDistribution': 'Distribuição por tipo',
    'analytics.campaignStatus': 'Status das Campanhas',
    'analytics.currentState': 'Estado atual',
    'analytics.noActivity': 'Nenhuma atividade recente',
    'analytics.campaign': 'Campanha',
    'analytics.contact': 'Contato',
    'analytics.performance': 'Performance',
    'analytics.detailedMetrics': 'Métricas detalhadas',
    'dashboard.analytics': 'Analytics',

    // QR Generator
    'qr.title': 'Gerar QR Code',
    'qr.description': 'Crie um QR Code personalizado para coletar contatos',
    'qr.configureForm': 'Configurar Formulário',
    'qr.businessName': 'Nome do Negócio',
    'qr.businessNamePlaceholder': 'Digite o nome do seu negócio',
    'qr.campaignType': 'Tipo de Campanha',
    'qr.promotionalTitle': 'Título Promocional',
    'qr.promotionalTitlePlaceholder': 'Ex: Ganhe 10% de desconto!',
    'qr.promotionalMessage': 'Mensagem Promocional',
    'qr.promotionalMessagePlaceholder': 'Descreva sua promoção...',
    'qr.thankYouMessage': 'Mensagem de Agradecimento',
    'qr.thankYouMessagePlaceholder': 'Obrigado! Em breve entraremos em contato.',
    'qr.generateQR': 'Gerar QR Code',
    'qr.downloadQR': 'Baixar QR Code',
    'qr.shareLink': 'Compartilhar Link',
    'qr.linkCopied': 'Link copiado para a área de transferência!',
    'qr.instructions': 'Cole este QR Code em seus materiais promocionais (mesas, flyers, etc.) para coletar contatos automaticamente.',
    'qr.loading': 'Gerando QR Code...',
    'qr.error': 'Erro ao gerar QR Code',
    'qr.tryAgain': 'Tentar novamente',
    'qr.campaignType.feedback': 'Feedback',
    'qr.campaignType.promotion': 'Promoção',
    'qr.campaignType.newsletter': 'Newsletter',
    'qr.campaignType.loyalty': 'Fidelidade',
    'qr.campaignType.event': 'Evento',

    // Home Page
    'home.innovative': 'Inovador',
    'home.heroTitle': 'Transforme seu Restaurante em uma Máquina de Marketing',
    'home.heroSubtitle': 'Colete contatos automaticamente e envie campanhas personalizadas para aumentar sua receita em até 40%',
    'home.tryNow': 'Experimente Agora',
    'home.seeDemo': 'Ver Demo',
    'home.openRate': 'Taxa de abertura',
    'home.revenueIncrease': 'Aumento de receita',
    'home.quickSetup': 'Configuração rápida',
    'home.support': 'Suporte',
    'home.featuresTitle': 'Funcionalidades Poderosas',
    'home.featuresSubtitle': 'Tudo que você precisa para transformar visitantes em clientes fiéis',
    'home.features.qrCodeTitle': 'QR Code Inteligente',
    'home.features.qrCodeDesc': 'Gere QR codes personalizados para coletar contatos automaticamente',
    'home.features.smsTitle': 'Campanhas SMS',
    'home.features.smsDesc': 'Envie mensagens direcionadas com alta taxa de conversão',
    'home.features.referralTitle': 'Programa de Indicação',
    'home.features.referralDesc': 'Transforme seus clientes em promotores da sua marca',
    'home.features.analyticsTitle': 'Analytics Avançado',
    'home.features.analyticsDesc': 'Acompanhe métricas detalhadas de suas campanhas',
    'home.features.rewardsTitle': 'Sistema de Recompensas',
    'home.features.rewardsDesc': 'Fidelize clientes com ofertas personalizadas',
    'home.features.targetingTitle': 'Segmentação Inteligente',
    'home.features.targetingDesc': 'Alcance o público certo na hora certa',
    'home.howItWorks': 'Como Funciona',
    'home.simpleSteps': 'Apenas 3 Passos Simples',
    'home.step1.title': 'Gere o QR Code',
    'home.step1.desc': 'Configure sua campanha e gere um QR code personalizado',
    'home.step2.title': 'Colete Contatos',
    'home.step2.desc': 'Clientes escaneiam e fornecem suas informações',
    'home.step3.title': 'Envie Campanhas',
    'home.step3.desc': 'Crie e envie campanhas direcionadas automaticamente',
    'home.ctaTitle': 'Pronto para Aumentar suas Vendas?',
    'home.ctaSubtitle': 'Junte-se a centenas de restaurantes que já aumentaram sua receita',
    'home.testFree': 'Testar Gratuitamente',
    'home.scheduleDemo': 'Agendar Demo',

    // Index Page
    'index.welcome': 'Bem-vindo',
    'index.subtitle': 'Plataforma de marketing para restaurantes',

    // Contacts Page
    'contacts.title': 'Contatos',
    'contacts.subtitle': 'Gerencie sua base de clientes',
    'contacts.scanQr': 'Escanear QR',
    'contacts.newContact': 'Novo Contato',
    'contacts.stats.total': 'Total',
    'contacts.stats.viaQr': 'Via QR Code',
    'contacts.stats.withEmail': 'Com Email',
    'contacts.stats.thisWeek': 'Esta Semana',
    'contacts.search.placeholder': 'Buscar por nome, telefone ou email...',
    'contacts.filter.allSources': 'Todas as origens',
    'contacts.filter.qrCode': 'QR Code',
    'contacts.filter.manual': 'Manual',
    'contacts.filter.import': 'Importação',
    'contacts.export': 'Exportar',
    'contacts.contactsCount': 'contatos',
    'contacts.noContactsFound': 'Nenhum contato encontrado',
    'contacts.selectAll': 'Selecionar todos',
    'contacts.unselectAll': 'Desmarcar todos',
    'contacts.addedOn': 'Adicionado em',
    'contacts.confirmDelete': 'Confirmar exclusão',
    'contacts.deleteConfirmMessage': 'Tem certeza que deseja excluir o contato',
    'contacts.deleteWarning': 'Esta ação não pode ser desfeita.',
    'contacts.cancel': 'Cancelar',
    'contacts.delete': 'Excluir',
    'contacts.noContactsFoundMessage': 'Nenhum contato encontrado',
    'contacts.adjustFilters': 'Tente ajustar os filtros ou termos de busca',
    'contacts.getStarted': 'Comece escaneando QR codes ou adicionando contatos manualmente',
    'contacts.scanQrCode': 'Escanear QR Code',
    'contacts.addContact': 'Adicionar Contato',

    // Campaigns Page
    'campaigns.title': 'Campanhas',
    'campaigns.subtitle': 'Crie e gerencie suas campanhas de marketing',
    'campaigns.newCampaign': 'Nova Campanha',
    'campaigns.createNew': 'Criar Nova Campanha',
    'campaigns.configurePromo': 'Configure sua campanha promocional',
    'campaigns.useTemplate': 'Usar um template (opcional)',
    'campaigns.chooseTemplate': 'Escolher um template existante',
    'campaigns.createFromScratch': 'Criar do zero',
    'campaigns.templateSelected': 'Template selecionado. Você pode modificar a mensagem abaixo.',
    'campaigns.campaignName': 'Nome da campanha',
    'campaigns.campaignNamePlaceholder': 'Ex: Segunda Boost',
    'campaigns.campaignType': 'Tipo de campanha',
    'campaigns.selectType': 'Selecionar um tipo',
    'campaigns.templateVariables': 'Variáveis do template',
    'campaigns.variableValue': 'Valor para',
    'campaigns.variablesReplaced': 'Essas variáveis serão substituídas na mensagem final.',
    'campaigns.promoMessage': 'Mensagem promocional',
    'campaigns.promoPlaceholder': 'Escreva sua mensagem promocional...',
    'campaigns.charactersForSms': 'caracteres para SMS',
    'campaigns.previewWithVariables': 'Visualização com variáveis aplicadas abaixo',
    'campaigns.finalMessagePreview': 'Visualização da mensagem final:',
    'campaigns.sendDateTime': 'Data e hora de envio (opcional)',
    'campaigns.leaveEmptyImmediate': 'Deixe vazio para enviar imediatamente',
    'campaigns.sendingViaTwilio': 'Envio via Twilio',
    'campaigns.twilioConfigured': 'Configuração do Twilio já configurada',
    'campaigns.messagesWillBeSent': 'Mensagens',
    'campaigns.sentDirectly': 'serão enviadas diretamente',
    'campaigns.twilioApiConfigured': 'API Twilio configurada nos secrets',
    'campaigns.creating': 'Criando...',
    'campaigns.createCampaign': 'Criar campanha',
    'campaigns.cancel': 'Cancelar',
    'campaigns.myCampaigns': 'Minhas campanhas',
    'campaigns.manageAndTrack': 'Gerencie e acompanhe suas campanhas de marketing',
    'campaigns.noCampaigns': 'Nenhuma campanha',
    'campaigns.createFirstCampaign': 'Crie sua primeira campanha para começar a engajar seus clientes.',
    'campaigns.createACampaign': 'Criar uma campanha',
    'campaigns.status.active': 'Ativo',
    'campaigns.status.sent': 'Enviado',
    'campaigns.status.scheduled': 'Programado',
    'campaigns.status.draft': 'Rascunho',
    'campaigns.scheduledFor': 'Programado para',
    'campaigns.send': 'Enviar',
    'campaigns.totalSent': 'Total enviados',
    'campaigns.success': 'Sucesso',
    'campaigns.failures': 'Falhas',
    'campaigns.sentOn': 'Enviado em',
    'campaigns.fillRequiredFields': 'Preencha todos os campos obrigatórios',
    'campaigns.campaignCreated': 'Campanha criada com sucesso',
    'campaigns.campaignSent': 'Campanha enviada com sucesso',
    'campaigns.cannotCreate': 'Não foi possível criar a campanha',
    'campaigns.cannotSend': 'Não foi possível enviar a campanha',
    'campaigns.campaignDeleted': 'Campanha deletada com sucesso',
    'campaigns.cannotDelete': 'Não foi possível deletar a campanha',
    
    // Campaign Stats
    'campaigns.stats.activeCampaigns': 'Campanhas Ativas',
    'campaigns.stats.messagesSent': 'Mensagens Enviadas',
    'campaigns.stats.successRate': 'Taxa de Sucesso',
    'campaigns.stats.totalCampaigns': 'Total de Campanhas',

    // QR Form Errors

    // QR Form Errors

    // QR Form Errors
    'qrForm.errorTitle': 'Erro',

    // QR Form

    // QR Form
    'qrForm.title': 'Escaneamento QR',
    'qrForm.subtitle': 'Escaneie QR codes e adicione contatos automaticamente',
    'qrForm.cameraScanner': 'Scanner de Câmera',
    'qrForm.contactData': 'Dados do Contato',
    'qrForm.scanToFill': 'Escaneie um QR code para preencher automaticamente',
    'qrForm.clickToStart': 'Clique para iniciar',
    'qrForm.startScanner': 'Iniciar Scanner',
    'qrForm.stopScanner': 'Parar Scanner',
    'qrForm.permissionDenied': 'Permissão de câmera negada',
    'qrForm.pointToQR': 'Aponte para o QR code',
    'qrForm.positionQR': 'Posicione o QR code dentro da área destacada',
    'qrForm.contactDataFilled': 'Dados de contato serão preenchidos automaticamente',
    'qrForm.otherQRSaved': 'Outros QR codes serão salvos nas observações',
    'qrForm.qrScanned': 'QR Code Escaneado',
    'qrForm.fillDataBelow': 'Preencha ou edite os dados abaixo',
    'qrForm.qrDetected': 'QR Code detectado:',
    'qrForm.requiredFields': 'Campos obrigatórios',
    'qrForm.namePhoneRequired': 'Nome e telefone são obrigatórios',
    'qrForm.contactAdded': 'Contato adicionado!',
    'qrForm.contactAddedToList': 'foi adicionado à sua lista de contatos',
    'qrForm.nameRequired': 'Nome (obrigatório)',
    'qrForm.customerName': 'Nome do cliente',
    'qrForm.phone': 'Telefone',
    'qrForm.email': 'Email',
    'qrForm.tags': 'Tags',
    'qrForm.addTag': 'Adicionar tag',
    'qrForm.notes': 'Observações',
    'qrForm.customerNotes': 'Observações sobre o cliente',
    'qrForm.saving': 'Salvando...',
    'qrForm.saveContact': 'Salvar Contato',
    'qrForm.reset': 'Reiniciar',
    'qrForm.scanningTips': 'Dicas de Escaneamento',
    'qrForm.goodLighting': 'Boa Iluminação',
    'qrForm.useWellLit': 'Use ambientes bem iluminados',
    'qrForm.adequateDistance': 'Distância Adequada',
    'qrForm.maintain10to30cm': 'Mantenha 10-30cm de distância',
    'qrForm.cleanQR': 'QR Code Limpo',
    'qrForm.ensureReadable': 'Certifique-se que esteja legível',

    // QR Generator  
    'qrGenerator.loading': 'Carregando...',
    'qrGenerator.loadError': 'Erro ao carregar dados do perfil',
    'qrGenerator.cannotGenerate': 'Não foi possível gerar o QR Code',
    'qrGenerator.shareDescription': 'Compartilhe este QR Code para coletar contatos',
    'qrGenerator.directLink': 'Link Direto',
    'qrGenerator.downloadQr': 'Baixar QR',
    'qrGenerator.share': 'Compartilhar',
    'qrGenerator.linkCopied': 'Link copiado!',
    'qrGenerator.linkCopiedDesc': 'O link foi copiado para a área de transferência',
    'qrGenerator.howToUse': 'Como usar:',
    'qrGenerator.instruction1': '1. Imprima ou exiba este QR Code em seu estabelecimento',
    'qrGenerator.instruction2': '2. Clientes escaneiam o código com a câmera do celular',
    'qrGenerator.instruction3': '3. Eles preenchem o formulário de contato',
    'qrGenerator.instruction4': '4. Você recebe os dados automaticamente no sistema',

    // QR Generator

    // QR Generator

    // QR Generator
  },

  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.generateQr': 'Générer QR',
    'nav.dashboard': 'Tableau de bord',
    'nav.contacts': 'Contacts',
    'nav.campaigns': 'Campagnes',
    'nav.templates': 'Modèles',
    'nav.analytics': 'Analytics',
    'nav.plans': 'Plans',
    'nav.login': 'Se connecter',
    'nav.logout': 'Se déconnecter',

    // Auth
    'auth.hello': 'Bonjour',
    'auth.loggedAs': 'Connecté en tant que',

    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.subtitle': 'Vue d\'ensemble de votre restaurant',
    'dashboard.totalContacts': 'Total Contacts',
    'dashboard.activeCampaigns': 'Campagnes Actives',
    'dashboard.messagesSent': 'Messages Envoyés',
    'dashboard.monthlyGrowth': 'Croissance Mensuelle',
    'dashboard.quickActions': 'Actions Rapides',
    'dashboard.newCampaign': 'Nouvelle Campagne',
    'dashboard.newCampaignDesc': 'Créer une campagne marketing',
    'dashboard.manageContacts': 'Gérer Contacts',
    'dashboard.manageContactsDesc': 'Voir et modifier vos contacts',
    'dashboard.recentContacts': 'Contacts Récents',
    'dashboard.noContactsYet': 'Aucun contact pour le moment',
    'dashboard.recentCampaigns': 'Campagnes Récentes',
    'dashboard.noCampaignsYet': 'Aucune campagne pour le moment',

    // Campaign Status
    'campaign.status.draft': 'Brouillon',
    'campaign.status.scheduled': 'Programmé',
    'campaign.status.sending': 'Envoi en cours',
    'campaign.status.sent': 'Envoyé',
    'campaign.status.completed': 'Terminé',
    'campaign.status.failed': 'Échec',
    'campaign.status.active': 'Actif',

    // Footer
    'footer.description': 'Plateforme complète de marketing pour restaurants avec collecte de contacts et campagnes automatisées.',
    'footer.features': 'Fonctionnalités',
    'footer.contactCollection': 'Collecte de contacts',
    'footer.automatedCampaigns': 'Campagnes automatisées',
    'footer.referralProgram': 'Programme de parrainage',
    'footer.detailedAnalytics': 'Analyses détaillées',
    'footer.support': 'Support',
    'footer.documentation': 'Documentation',
    'footer.contact': 'Contact',
    'footer.faq': 'FAQ',
    'footer.onlineHelp': 'Aide en ligne',
    'footer.allRights': 'Tous droits réservés.',

    // Contact Sources
    'contact.source.qr': 'Code QR',
    'contact.source.manual': 'Manuel',
    'contact.source.import': 'Import',
    'contact.source.api': 'API',

    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Métriques et performances de vos campagnes',
    'analytics.refresh': 'Actualiser',
    'analytics.timeRange.7d': 'Derniers 7 jours',
    'analytics.timeRange.30d': 'Derniers 30 jours',
    'analytics.timeRange.90d': 'Derniers 90 jours',
    'analytics.timeRange.365d': 'Dernière année',
    'analytics.campaigns': 'Campagnes',
    'analytics.sent': 'Envoyées',
    'analytics.contacts': 'Contacts',
    'analytics.cost': 'Coût',
    'analytics.inPeriod': 'Dans la période',
    'analytics.success': 'succès',
    'analytics.newContacts': 'Nouveaux contacts',
    'analytics.sendTrend': 'Tendance d\'envoi',
    'analytics.campaignTypes': 'Types de campagne',
    'analytics.distributionByType': 'Répartition par type',
    'analytics.performanceMetrics': 'Métriques de performance',
    'analytics.keySuccessIndicators': 'Indicateurs clés de succès',
    'analytics.deliveryRate': 'Taux de livraison',
    'analytics.costPerMessage': 'Coût par message (€)',
    'analytics.messagesPerContact': 'Messages par contact',
    'analytics.recentActivity': 'Activité récente',
    'analytics.lastActions': 'Dernières actions effectuées',
    'analytics.noRecentActivity': 'Aucune activité récente',
    'analytics.sent.chart': 'Envoyées',
    'analytics.delivered.chart': 'Livrées',
    'analytics.campaign.label': 'Campagne',
    'analytics.contact.label': 'Contact',
    'analytics.status.draft': 'Brouillon',
    'analytics.status.scheduled': 'Programmé',
    'analytics.status.sending': 'Envoi en cours',
    'analytics.status.completed': 'Terminé',
    'analytics.status.failed': 'Échec',
    'analytics.type.sms': 'SMS',
    'analytics.type.email': 'Email',
    'analytics.type.whatsapp': 'WhatsApp',
    'analytics.last7days': 'Derniers 7 jours',
    'analytics.last30days': 'Derniers 30 jours',
    'analytics.last90days': 'Derniers 90 jours',
    'analytics.lastYear': 'Dernière année',
    'analytics.totalCampaigns': 'Total Campagnes',
    'analytics.selectedPeriod': 'Dans la période sélectionnée',
    'analytics.totalContacts': 'Total Contacts',
    'analytics.newContactsAdded': 'Nouveaux contacts ajoutés',
    'analytics.messagesSent': 'Messages Envoyés',
    'analytics.successRate': 'Taux de succès',
    'analytics.totalCost': 'Coût Total',
    'analytics.campaignExpenses': 'Dépenses de campagne',
    'analytics.sentVsDelivered': 'Envoyées vs Livrées',
    'analytics.campaignsByType': 'Campagnes par Type',
    'analytics.typeDistribution': 'Répartition par type',
    'analytics.campaignStatus': 'Statut des Campagnes',
    'analytics.currentState': 'État actuel',
    'analytics.noActivity': 'Aucune activité récente',
    'analytics.campaign': 'Campagne',
    'analytics.contact': 'Contact',
    'analytics.performance': 'Performance',
    'analytics.detailedMetrics': 'Métriques détaillées',
    'dashboard.analytics': 'Analytics',
    'dashboard.overview': 'Vue d\'ensemble',
    'dashboard.overviewTitle': 'Vue d\'ensemble',
    'dashboard.overviewSubtitle': 'Suivez les performances de votre entreprise',
    'dashboard.scanQr': 'Scanner QR',
    'dashboard.thisWeek': 'cette semaine',
    'dashboard.total': 'total',
    'dashboard.conversionRate': 'Taux de Conversion',
    'dashboard.last30Days': 'Derniers 30 jours',
    'dashboard.uniqueQr': 'QR Unique',
    'dashboard.yourAccessCode': 'Votre code d\'accès',
    'dashboard.recentCampaignsDesc': 'Vos campagnes les plus récentes',
    'dashboard.recentContactsDesc': 'Contacts ajoutés récemment',
    'dashboard.quickActionsDesc': 'Actions rapides pour gérer votre entreprise',
    'dashboard.captureContact': 'Capturer Contact',
    'dashboard.captureContactDesc': 'Scannez des QR codes pour ajouter des contacts',
    'dashboard.newCampaignAction': 'Nouvelle Campagne',

    // Campaign Status

    // QR Generator
    'qr.title': 'Générer un QR Code',
    'qr.description': 'Créez un QR Code personnalisé pour collecter des contacts',
    'qr.configureForm': 'Configurer le Formulaire',
    'qr.businessName': 'Nom de l\'Entreprise',
    'qr.businessNamePlaceholder': 'Saisissez le nom de votre entreprise',
    'qr.campaignType': 'Type de Campagne',
    'qr.promotionalTitle': 'Titre Promotionnel',
    'qr.promotionalTitlePlaceholder': 'Ex: Obtenez 10% de réduction!',
    'qr.promotionalMessage': 'Message Promotionnel',
    'qr.promotionalMessagePlaceholder': 'Décrivez votre promotion...',
    'qr.thankYouMessage': 'Message de Remerciement',
    'qr.thankYouMessagePlaceholder': 'Merci! Nous vous contacterons bientôt.',
    'qr.generateQR': 'Générer le QR Code',
    'qr.downloadQR': 'Télécharger le QR Code',
    'qr.shareLink': 'Partager le Lien',
    'qr.linkCopied': 'Lien copié dans le presse-papiers!',
    'qr.instructions': 'Collez ce QR Code sur vos supports promotionnels (tables, flyers, etc.) pour collecter automatiquement les contacts.',
    'qr.loading': 'Génération du QR Code...',
    'qr.error': 'Erreur lors de la génération du QR Code',
    'qr.tryAgain': 'Réessayer',
    'qr.campaignType.feedback': 'Commentaires',
    'qr.campaignType.promotion': 'Promotion',
    'qr.campaignType.newsletter': 'Newsletter',
    'qr.campaignType.loyalty': 'Fidélité',
    'qr.campaignType.event': 'Événement',

    // Home Page
    'home.innovative': 'Innovant',
    'home.heroTitle': 'Transformez votre Restaurant en Machine Marketing',
    'home.heroSubtitle': 'Collectez des contacts automatiquement et envoyez des campagnes personnalisées pour augmenter vos revenus jusqu\'à 40%',
    'home.tryNow': 'Essayer Maintenant',
    'home.seeDemo': 'Voir Démo',
    'home.openRate': 'Taux d\'ouverture',
    'home.revenueIncrease': 'Augmentation du chiffre d\'affaires',
    'home.quickSetup': 'Configuration rapide',
    'home.support': 'Support',
    'home.featuresTitle': 'Fonctionnalités Puissantes',
    'home.featuresSubtitle': 'Tout ce dont vous avez besoin pour transformer les visiteurs en clients fidèles',
    'home.features.qrCodeTitle': 'QR Code Intelligent',
    'home.features.qrCodeDesc': 'Générez des QR codes personnalisés pour collecter des contacts automatiquement',
    'home.features.smsTitle': 'Campagnes SMS',
    'home.features.smsDesc': 'Envoyez des messages ciblés avec un taux de conversion élevé',
    'home.features.referralTitle': 'Programme de Parrainage',
    'home.features.referralDesc': 'Transformez vos clients en promoteurs de votre marque',
    'home.features.analyticsTitle': 'Analytics Avancé',
    'home.features.analyticsDesc': 'Suivez les métriques détaillées de vos campagnes',
    'home.features.rewardsTitle': 'Système de Récompenses',
    'home.features.rewardsDesc': 'Fidélisez les clients avec des offres personnalisées',
    'home.features.targetingTitle': 'Ciblage Intelligent',
    'home.features.targetingDesc': 'Atteignez le bon public au bon moment',
    'home.howItWorks': 'Comment ça Marche',
    'home.simpleSteps': 'Seulement 3 Étapes Simples',
    'home.step1.title': 'Générer le QR Code',
    'home.step1.desc': 'Configurez votre campagne et générez un QR code personnalisé',
    'home.step2.title': 'Collecter les Contacts',
    'home.step2.desc': 'Les clients scannent et fournissent leurs informations',
    'home.step3.title': 'Envoyer les Campagnes',
    'home.step3.desc': 'Créez et envoyez des campagnes ciblées automatiquement',
    'home.ctaTitle': 'Prêt à Augmenter vos Ventes?',
    'home.ctaSubtitle': 'Rejoignez des centaines de restaurants qui ont déjà augmenté leurs revenus',
    'home.testFree': 'Tester Gratuitement',
    'home.scheduleDemo': 'Planifier une Démo',

    // Index Page
    'index.welcome': 'Bienvenue',
    'index.subtitle': 'Plateforme marketing pour restaurants',

    // Contacts Page
    'contacts.title': 'Contacts',
    'contacts.subtitle': 'Gérez votre base de clients',
    'contacts.scanQr': 'Scanner QR',
    'contacts.newContact': 'Nouveau Contact',
    'contacts.stats.total': 'Total',
    'contacts.stats.viaQr': 'Via QR Code',
    'contacts.stats.withEmail': 'Avec Email',
    'contacts.stats.thisWeek': 'Cette Semaine',
    'contacts.search.placeholder': 'Rechercher par nom, téléphone ou email...',
    'contacts.filter.allSources': 'Toutes les sources',
    'contacts.filter.qrCode': 'QR Code',
    'contacts.filter.manual': 'Manuel',
    'contacts.filter.import': 'Import',
    'contacts.export': 'Exporter',
    'contacts.contactsCount': 'contacts',
    'contacts.noContactsFound': 'Aucun contact trouvé',
    'contacts.selectAll': 'Tout sélectionner',
    'contacts.unselectAll': 'Tout désélectionner',
    'contacts.addedOn': 'Ajouté le',
    'contacts.confirmDelete': 'Confirmer la suppression',
    'contacts.deleteConfirmMessage': 'Êtes-vous sûr de vouloir supprimer le contact',
    'contacts.deleteWarning': 'Cette action ne peut pas être annulée.',
    'contacts.cancel': 'Annuler',
    'contacts.delete': 'Supprimer',
    'contacts.noContactsFoundMessage': 'Aucun contact trouvé',
    'contacts.adjustFilters': 'Essayez d\'ajuster les filtres ou les termes de recherche',
    'contacts.getStarted': 'Commencez par scanner des QR codes ou ajouter des contacts manuellement',
    'contacts.scanQrCode': 'Scanner QR Code',
    'contacts.addContact': 'Ajouter Contact',

    // Campaigns Page
    'campaigns.title': 'Campagnes',
    'campaigns.subtitle': 'Créez et gérez vos campagnes marketing',
    'campaigns.newCampaign': 'Nouvelle Campagne',
    'campaigns.createNew': 'Créer Nouvelle Campagne',
    'campaigns.configurePromo': 'Configurez votre campagne promotionnelle',
    'campaigns.useTemplate': 'Utiliser un template (optionnel)',
    'campaigns.chooseTemplate': 'Choisir un template existant',
    'campaigns.createFromScratch': 'Créer depuis zéro',
    'campaigns.templateSelected': 'Template sélectionné. Vous pouvez modifier le message ci-dessous.',
    'campaigns.campaignName': 'Nom de la campagne',
    'campaigns.campaignNamePlaceholder': 'Ex: Lundi Boost',
    'campaigns.campaignType': 'Type de campagne',
    'campaigns.selectType': 'Sélectionner un type',
    'campaigns.templateVariables': 'Variables du template',
    'campaigns.variableValue': 'Valeur pour',
    'campaigns.variablesReplaced': 'Ces variables seront remplacées dans le message final.',
    'campaigns.promoMessage': 'Message promotionnel',
    'campaigns.promoPlaceholder': 'Rédigez votre message promotionnel...',
    'campaigns.charactersForSms': 'caractères pour SMS',
    'campaigns.previewWithVariables': 'Aperçu avec variables appliquées ci-dessous',
    'campaigns.finalMessagePreview': 'Aperçu du message final:',
    'campaigns.sendDateTime': 'Date et heure d\'envoi (optionnel)',
    'campaigns.leaveEmptyImmediate': 'Laissez vide pour envoyer immédiatement',
    'campaigns.sendingViaTwilio': 'Envoi via Twilio',
    'campaigns.twilioConfigured': 'Configuration du Twilio déjà configurée',
    'campaigns.messagesWillBeSent': 'Messages',
    'campaigns.sentDirectly': 'seront envoyés directement',
    'campaigns.twilioApiConfigured': 'API Twilio configurée dans les secrets',
    'campaigns.creating': 'Création...',
    'campaigns.createCampaign': 'Créer la campagne',
    'campaigns.cancel': 'Annuler',
    'campaigns.myCampaigns': 'Mes campagnes',
    'campaigns.manageAndTrack': 'Gérez et suivez vos campagnes marketing',
    'campaigns.noCampaigns': 'Aucune campagne',
    'campaigns.createFirstCampaign': 'Créez votre première campagne pour commencer à engager vos clients.',
    'campaigns.createACampaign': 'Créer une campagne',
    'campaigns.status.active': 'Actif',
    'campaigns.status.sent': 'Envoyé',
    'campaigns.status.scheduled': 'Programmé',
    'campaigns.status.draft': 'Brouillon',
    'campaigns.scheduledFor': 'Programmé pour',
    'campaigns.send': 'Envoyer',
    'campaigns.totalSent': 'Total envoyés',
    'campaigns.success': 'Succès',
    'campaigns.failures': 'Échecs',
    'campaigns.sentOn': 'Envoyé le',
    'campaigns.error': 'Erreur',
    'campaigns.fillRequiredFields': 'Veuillez remplir tous les champs obligatoires',
    'campaigns.campaignCreated': 'Campagne créée avec succès',
    'campaigns.campaignSent': 'Campagne envoyée avec succès',
    'campaigns.cannotCreate': 'Impossible de créer la campagne',
    'campaigns.cannotSend': 'Impossible d\'envoyer la campagne',
    'campaigns.campaignDeleted': 'Campagne supprimée avec succès',
    'campaigns.cannotDelete': 'Impossible de supprimer la campagne',
    
    // Campaign Stats
    'campaigns.stats.activeCampaigns': 'Campagnes Actives',
    'campaigns.stats.messagesSent': 'Messages Envoyés',
    'campaigns.stats.successRate': 'Taux de Succès',
    'campaigns.stats.totalCampaigns': 'Total des Campagnes',

    // QR Form Errors

    // QR Form Errors

    // QR Form Errors
    'qrForm.errorTitle': 'Erreur',

    // QR Form

    // QR Form
    'qrForm.title': 'Scanner QR',
    'qrForm.subtitle': 'Scannez des QR codes et ajoutez des contacts automatiquement',
    'qrForm.cameraScanner': 'Scanner Caméra',
    'qrForm.contactData': 'Données de Contact',
    'qrForm.scanToFill': 'Scannez un QR code pour remplir automatiquement',
    'qrForm.clickToStart': 'Cliquez pour commencer',
    'qrForm.startScanner': 'Démarrer Scanner',
    'qrForm.stopScanner': 'Arrêter Scanner',
    'qrForm.permissionDenied': 'Permission caméra refusée',
    'qrForm.pointToQR': 'Pointez vers le QR code',
    'qrForm.positionQR': 'Positionnez le QR code dans la zone en surbrillance',
    'qrForm.contactDataFilled': 'Les données de contact seront remplies automatiquement',
    'qrForm.otherQRSaved': 'Les autres QR codes seront sauvés dans les notes',
    'qrForm.qrScanned': 'QR Code Scanné',
    'qrForm.fillDataBelow': 'Remplissez ou modifiez les données ci-dessous',
    'qrForm.qrDetected': 'QR Code détecté:',
    'qrForm.requiredFields': 'Champs obligatoires',
    'qrForm.namePhoneRequired': 'Le nom et le téléphone sont obligatoires',
    'qrForm.contactAdded': 'Contact ajouté!',
    'qrForm.contactAddedToList': 'a été ajouté à votre liste de contacts',
    'qrForm.nameRequired': 'Nom (obligatoire)',
    'qrForm.customerName': 'Nom du client',
    'qrForm.phone': 'Téléphone',
    'qrForm.email': 'Email',
    'qrForm.tags': 'Tags',
    'qrForm.addTag': 'Ajouter tag',
    'qrForm.notes': 'Notes',
    'qrForm.customerNotes': 'Notes sur le client',
    'qrForm.saving': 'Sauvegarde...',
    'qrForm.saveContact': 'Sauvegarder Contact',
    'qrForm.reset': 'Réinitialiser',
    'qrForm.scanningTips': 'Conseils de Scan',
    'qrForm.goodLighting': 'Bon Éclairage',
    'qrForm.useWellLit': 'Utilisez des environnements bien éclairés',
    'qrForm.adequateDistance': 'Distance Adéquate',
    'qrForm.maintain10to30cm': 'Maintenez 10-30cm de distance',
    'qrForm.cleanQR': 'QR Code Propre',
    'qrForm.ensureReadable': 'Assurez-vous qu\'il soit lisible',

    // QR Generator  
    'qrGenerator.loading': 'Chargement...',
    'qrGenerator.loadError': 'Erreur lors du chargement des données du profil',
    'qrGenerator.cannotGenerate': 'Impossible de générer le QR Code',
    'qrGenerator.shareDescription': 'Partagez ce QR Code pour collecter des contacts',
    'qrGenerator.directLink': 'Lien Direct',
    'qrGenerator.downloadQr': 'Télécharger QR',
    'qrGenerator.share': 'Partager',
    'qrGenerator.linkCopied': 'Lien copié!',
    'qrGenerator.linkCopiedDesc': 'Le lien a été copié dans le presse-papiers',
    'qrGenerator.howToUse': 'Comment utiliser:',
    'qrGenerator.instruction1': '1. Imprimez ou affichez ce QR Code dans votre établissement',
    'qrGenerator.instruction2': '2. Les clients scannent le code avec l\'appareil photo de leur téléphone',
    'qrGenerator.instruction3': '3. Ils remplissent le formulaire de contact',
    'qrGenerator.instruction4': '4. Vous recevez les données automatiquement dans le système',

    // QR Generator

    // QR Generator
  },

  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.generateQr': 'Generate QR',
    'nav.dashboard': 'Dashboard',
    'nav.contacts': 'Contacts',
    'nav.campaigns': 'Campaigns',
    'nav.templates': 'Templates',
    'nav.analytics': 'Analytics',
    'nav.plans': 'Plans',
    'nav.login': 'Login',
    'nav.logout': 'Logout',

    // Auth
    'auth.hello': 'Hello',
    'auth.loggedAs': 'Logged in as',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of your restaurant',
    'dashboard.totalContacts': 'Total Contacts',
    'dashboard.activeCampaigns': 'Active Campaigns',
    'dashboard.messagesSent': 'Messages Sent',
    'dashboard.monthlyGrowth': 'Monthly Growth',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.newCampaign': 'New Campaign',
    'dashboard.newCampaignDesc': 'Create a marketing campaign',
    'dashboard.manageContacts': 'Manage Contacts',
    'dashboard.manageContactsDesc': 'View and edit your contacts',
    'dashboard.recentContacts': 'Recent Contacts',
    'dashboard.noContactsYet': 'No contacts yet',
    'dashboard.recentCampaigns': 'Recent Campaigns',
    'dashboard.noCampaignsYet': 'No campaigns yet',

    // Campaign Status
    'campaign.status.draft': 'Draft',
    'campaign.status.scheduled': 'Scheduled',
    'campaign.status.sending': 'Sending',
    'campaign.status.sent': 'Sent',
    'campaign.status.completed': 'Completed',
    'campaign.status.failed': 'Failed',
    'campaign.status.active': 'Active',

    // Footer
    'footer.description': 'Complete marketing platform for restaurants with contact collection and automated campaigns.',
    'footer.features': 'Features',
    'footer.contactCollection': 'Contact Collection',
    'footer.automatedCampaigns': 'Automated Campaigns',
    'footer.referralProgram': 'Referral Program',
    'footer.detailedAnalytics': 'Detailed Analytics',
    'footer.support': 'Support',
    'footer.documentation': 'Documentation',
    'footer.contact': 'Contact',
    'footer.faq': 'FAQ',
    'footer.onlineHelp': 'Online Help',
    'footer.allRights': 'All rights reserved.',

    // Contact Sources
    'contact.source.qr': 'QR Code',
    'contact.source.manual': 'Manual',
    'contact.source.import': 'Import',
    'contact.source.api': 'API',

    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Track your campaigns and contacts performance',
    'analytics.refresh': 'Refresh',
    'analytics.timeRange.7d': 'Last 7 days',
    'analytics.timeRange.30d': 'Last 30 days',
    'analytics.timeRange.90d': 'Last 90 days',
    'analytics.timeRange.365d': 'Last year',
    'analytics.campaigns': 'Campaigns',
    'analytics.sent': 'Sent',
    'analytics.contacts': 'Contacts',
    'analytics.cost': 'Cost',
    'analytics.inPeriod': 'In period',
    'analytics.success': 'success',
    'analytics.newContacts': 'New contacts',
    'analytics.sendTrend': 'Send Trend',
    'analytics.campaignTypes': 'Campaign Types',
    'analytics.distributionByType': 'Distribution by type',
    'analytics.performanceMetrics': 'Performance Metrics',
    'analytics.keySuccessIndicators': 'Key success indicators',
    'analytics.deliveryRate': 'Delivery Rate',
    'analytics.costPerMessage': 'Cost per message ($)',
    'analytics.messagesPerContact': 'Messages per contact',
    'analytics.recentActivity': 'Recent Activity',
    'analytics.lastActions': 'Last actions performed',
    'analytics.noRecentActivity': 'No recent activity',
    'analytics.sent.chart': 'Sent',
    'analytics.delivered.chart': 'Delivered',
    'analytics.campaign.label': 'Campaign',
    'analytics.contact.label': 'Contact',
    'analytics.status.draft': 'Draft',
    'analytics.status.scheduled': 'Scheduled',
    'analytics.status.sending': 'Sending',
    'analytics.status.completed': 'Completed',
    'analytics.status.failed': 'Failed',
    'analytics.type.sms': 'SMS',
    'analytics.type.email': 'Email',
    'analytics.type.whatsapp': 'WhatsApp',
    'analytics.last7days': 'Last 7 days',
    'analytics.last30days': 'Last 30 days',
    'analytics.last90days': 'Last 90 days',
    'analytics.lastYear': 'Last year',
    'analytics.totalCampaigns': 'Total Campaigns',
    'analytics.selectedPeriod': 'In selected period',
    'analytics.totalContacts': 'Total Contacts',
    'analytics.newContactsAdded': 'New contacts added',
    'analytics.messagesSent': 'Messages Sent',
    'analytics.successRate': 'Success rate',
    'analytics.totalCost': 'Total Cost',
    'analytics.campaignExpenses': 'Campaign expenses',
    'analytics.sentVsDelivered': 'Sent vs Delivered',
    'analytics.campaignsByType': 'Campaigns by Type',
    'analytics.typeDistribution': 'Distribution by type',
    'analytics.campaignStatus': 'Campaign Status',
    'analytics.currentState': 'Current state',
    'analytics.noActivity': 'No recent activity',
    'analytics.campaign': 'Campaign',
    'analytics.contact': 'Contact',
    'analytics.performance': 'Performance',
    'analytics.detailedMetrics': 'Detailed metrics',
    'dashboard.analytics': 'Analytics',
    'dashboard.overview': 'Overview',
    'dashboard.overviewTitle': 'Overview',
    'dashboard.overviewSubtitle': 'Track your business performance',
    'dashboard.scanQr': 'Scan QR',
    'dashboard.thisWeek': 'this week',
    'dashboard.total': 'total',
    'dashboard.conversionRate': 'Conversion Rate',
    'dashboard.last30Days': 'Last 30 days',
    'dashboard.uniqueQr': 'Unique QR',
    'dashboard.yourAccessCode': 'Your access code',
    'dashboard.recentCampaignsDesc': 'Your most recent campaigns',
    'dashboard.recentContactsDesc': 'Recently added contacts',
    'dashboard.quickActionsDesc': 'Quick actions to manage your business',
    'dashboard.captureContact': 'Capture Contact',
    'dashboard.captureContactDesc': 'Scan QR codes to add contacts',
    'dashboard.newCampaignAction': 'New Campaign',

    // Campaign Status

    // QR Generator
    'qr.title': 'Generate QR Code',
    'qr.description': 'Create a custom QR Code to collect contacts',
    'qr.configureForm': 'Configure Form',
    'qr.businessName': 'Business Name',
    'qr.businessNamePlaceholder': 'Enter your business name',
    'qr.campaignType': 'Campaign Type',
    'qr.promotionalTitle': 'Promotional Title',
    'qr.promotionalTitlePlaceholder': 'Ex: Get 10% off!',
    'qr.promotionalMessage': 'Promotional Message',
    'qr.promotionalMessagePlaceholder': 'Describe your promotion...',
    'qr.thankYouMessage': 'Thank You Message',
    'qr.thankYouMessagePlaceholder': 'Thank you! We will contact you soon.',
    'qr.generateQR': 'Generate QR Code',
    'qr.downloadQR': 'Download QR Code',
    'qr.shareLink': 'Share Link',
    'qr.linkCopied': 'Link copied to clipboard!',
    'qr.instructions': 'Paste this QR Code on your promotional materials (tables, flyers, etc.) to automatically collect contacts.',
    'qr.loading': 'Generating QR Code...',
    'qr.error': 'Error generating QR Code',
    'qr.tryAgain': 'Try again',
    'qr.campaignType.feedback': 'Feedback',
    'qr.campaignType.promotion': 'Promotion',
    'qr.campaignType.newsletter': 'Newsletter',
    'qr.campaignType.loyalty': 'Loyalty',
    'qr.campaignType.event': 'Event',

    // Home Page
    'home.innovative': 'Innovative',
    'home.heroTitle': 'Transform your Restaurant into a Marketing Machine',
    'home.heroSubtitle': 'Collect contacts automatically and send personalized campaigns to increase your revenue by up to 40%',
    'home.tryNow': 'Try Now',
    'home.seeDemo': 'See Demo',
    'home.openRate': 'Open rate',
    'home.revenueIncrease': 'Revenue increase',
    'home.quickSetup': 'Quick setup',
    'home.support': 'Support',
    'home.featuresTitle': 'Powerful Features',
    'home.featuresSubtitle': 'Everything you need to turn visitors into loyal customers',
    'home.features.qrCodeTitle': 'Smart QR Code',
    'home.features.qrCodeDesc': 'Generate custom QR codes to collect contacts automatically',
    'home.features.smsTitle': 'SMS Campaigns',
    'home.features.smsDesc': 'Send targeted messages with high conversion rates',
    'home.features.referralTitle': 'Referral Program',
    'home.features.referralDesc': 'Turn your customers into brand promoters',
    'home.features.analyticsTitle': 'Advanced Analytics',
    'home.features.analyticsDesc': 'Track detailed metrics of your campaigns',
    'home.features.rewardsTitle': 'Rewards System',
    'home.features.rewardsDesc': 'Retain customers with personalized offers',
    'home.features.targetingTitle': 'Smart Targeting',
    'home.features.targetingDesc': 'Reach the right audience at the right time',
    'home.howItWorks': 'How It Works',
    'home.simpleSteps': 'Just 3 Simple Steps',
    'home.step1.title': 'Generate QR Code',
    'home.step1.desc': 'Set up your campaign and generate a custom QR code',
    'home.step2.title': 'Collect Contacts',
    'home.step2.desc': 'Customers scan and provide their information',
    'home.step3.title': 'Send Campaigns',
    'home.step3.desc': 'Create and send targeted campaigns automatically',
    'home.ctaTitle': 'Ready to Boost Your Sales?',
    'home.ctaSubtitle': 'Join hundreds of restaurants that have already increased their revenue',
    'home.testFree': 'Test for Free',
    'home.scheduleDemo': 'Schedule Demo',

    // Index Page
    'index.welcome': 'Welcome',
    'index.subtitle': 'Marketing platform for restaurants',

    // Contacts Page
    'contacts.title': 'Contacts',
    'contacts.subtitle': 'Manage your customer base',
    'contacts.scanQr': 'Scan QR',
    'contacts.newContact': 'New Contact',
    'contacts.stats.total': 'Total',
    'contacts.stats.viaQr': 'Via QR Code',
    'contacts.stats.withEmail': 'With Email',
    'contacts.stats.thisWeek': 'This Week',
    'contacts.search.placeholder': 'Search by name, phone or email...',
    'contacts.filter.allSources': 'All sources',
    'contacts.filter.qrCode': 'QR Code',
    'contacts.filter.manual': 'Manual',
    'contacts.filter.import': 'Import',
    'contacts.export': 'Export',
    'contacts.contactsCount': 'contacts',
    'contacts.noContactsFound': 'No contacts found',
    'contacts.selectAll': 'Select all',
    'contacts.unselectAll': 'Unselect all',
    'contacts.addedOn': 'Added on',
    'contacts.confirmDelete': 'Confirm deletion',
    'contacts.deleteConfirmMessage': 'Are you sure you want to delete the contact',
    'contacts.deleteWarning': 'This action cannot be undone.',
    'contacts.cancel': 'Cancel',
    'contacts.delete': 'Delete',
    'contacts.noContactsFoundMessage': 'No contacts found',
    'contacts.adjustFilters': 'Try adjusting filters or search terms',
    'contacts.getStarted': 'Start by scanning QR codes or adding contacts manually',
    'contacts.scanQrCode': 'Scan QR Code',
    'contacts.addContact': 'Add Contact',

    // Campaigns Page
    'campaigns.title': 'Campaigns',
    'campaigns.subtitle': 'Create and manage your marketing campaigns',
    'campaigns.newCampaign': 'New Campaign',
    'campaigns.createNew': 'Create New Campaign',
    'campaigns.configurePromo': 'Configure your promotional campaign',
    'campaigns.useTemplate': 'Use a template (optional)',
    'campaigns.chooseTemplate': 'Choose an existing template',
    'campaigns.createFromScratch': 'Create from scratch',
    'campaigns.templateSelected': 'Template selected. You can modify the message below.',
    'campaigns.campaignName': 'Campaign name',
    'campaigns.campaignNamePlaceholder': 'Ex: Monday Boost',
    'campaigns.campaignType': 'Campaign type',
    'campaigns.selectType': 'Select a type',
    'campaigns.templateVariables': 'Template variables',
    'campaigns.variableValue': 'Value for',
    'campaigns.variablesReplaced': 'These variables will be replaced in the final message.',
    'campaigns.promoMessage': 'Promotional message',
    'campaigns.promoPlaceholder': 'Write your promotional message...',
    'campaigns.charactersForSms': 'characters for SMS',
    'campaigns.previewWithVariables': 'Preview with variables applied below',
    'campaigns.finalMessagePreview': 'Final message preview:',
    'campaigns.sendDateTime': 'Send date and time (optional)',
    'campaigns.leaveEmptyImmediate': 'Leave empty to send immediately',
    'campaigns.sendingViaTwilio': 'Sending via Twilio',
    'campaigns.twilioConfigured': 'Twilio configuration already configured',
    'campaigns.messagesWillBeSent': 'Messages',
    'campaigns.sentDirectly': 'will be sent directly',
    'campaigns.twilioApiConfigured': 'Twilio API configured in secrets',
    'campaigns.creating': 'Creating...',
    'campaigns.createCampaign': 'Create campaign',
    'campaigns.cancel': 'Cancel',
    'campaigns.myCampaigns': 'My campaigns',
    'campaigns.manageAndTrack': 'Manage and track your marketing campaigns',
    'campaigns.noCampaigns': 'No campaigns',
    'campaigns.createFirstCampaign': 'Create your first campaign to start engaging your customers.',
    'campaigns.createACampaign': 'Create a campaign',
    'campaigns.status.active': 'Active',
    'campaigns.status.sent': 'Sent',
    'campaigns.status.scheduled': 'Scheduled',
    'campaigns.status.draft': 'Draft',
    'campaigns.scheduledFor': 'Scheduled for',
    'campaigns.send': 'Send',
    'campaigns.totalSent': 'Total sent',
    'campaigns.success': 'Success',
    'campaigns.failures': 'Failures',
    'campaigns.sentOn': 'Sent on',
    'campaigns.error': 'Error',
    'campaigns.fillRequiredFields': 'Please fill all required fields',
    'campaigns.campaignCreated': 'Campaign created successfully',
    'campaigns.campaignSent': 'Campaign sent successfully',
    'campaigns.cannotCreate': 'Unable to create campaign',
    'campaigns.cannotSend': 'Unable to send campaign',
    'campaigns.campaignDeleted': 'Campaign deleted successfully',
    'campaigns.cannotDelete': 'Unable to delete campaign',
    
    // Campaign Stats
    'campaigns.stats.activeCampaigns': 'Active Campaigns',
    'campaigns.stats.messagesSent': 'Messages Sent',
    'campaigns.stats.successRate': 'Success Rate',
    'campaigns.stats.totalCampaigns': 'Total Campaigns',

    // QR Form Errors

    // QR Form Errors

    // QR Form Errors
    'qrForm.errorTitle': 'Error',

    // QR Form

    // QR Form
    'qrForm.title': 'QR Scanning',
    'qrForm.subtitle': 'Scan QR codes and add contacts automatically',
    'qrForm.cameraScanner': 'Camera Scanner',
    'qrForm.contactData': 'Contact Data',
    'qrForm.scanToFill': 'Scan a QR code to fill automatically',
    'qrForm.clickToStart': 'Click to start',
    'qrForm.startScanner': 'Start Scanner',
    'qrForm.stopScanner': 'Stop Scanner',
    'qrForm.permissionDenied': 'Camera permission denied',
    'qrForm.pointToQR': 'Point to the QR code',
    'qrForm.positionQR': 'Position the QR code within the highlighted area',
    'qrForm.contactDataFilled': 'Contact data will be filled automatically',
    'qrForm.otherQRSaved': 'Other QR codes will be saved in notes',
    'qrForm.qrScanned': 'QR Code Scanned',
    'qrForm.fillDataBelow': 'Fill or edit the data below',
    'qrForm.qrDetected': 'QR Code detected:',
    'qrForm.requiredFields': 'Required fields',
    'qrForm.namePhoneRequired': 'Name and phone are required',
    'qrForm.contactAdded': 'Contact added!',
    'qrForm.contactAddedToList': 'was added to your contact list',
    'qrForm.nameRequired': 'Name (required)',
    'qrForm.customerName': 'Customer name',
    'qrForm.phone': 'Phone',
    'qrForm.email': 'Email',
    'qrForm.tags': 'Tags',
    'qrForm.addTag': 'Add tag',
    'qrForm.notes': 'Notes',
    'qrForm.customerNotes': 'Customer notes',
    'qrForm.saving': 'Saving...',
    'qrForm.saveContact': 'Save Contact',
    'qrForm.reset': 'Reset',
    'qrForm.scanningTips': 'Scanning Tips',
    'qrForm.goodLighting': 'Good Lighting',
    'qrForm.useWellLit': 'Use well-lit environments',
    'qrForm.adequateDistance': 'Adequate Distance',
    'qrForm.maintain10to30cm': 'Maintain 10-30cm distance',
    'qrForm.cleanQR': 'Clean QR Code',
    'qrForm.ensureReadable': 'Make sure it\'s readable',

    // QR Generator  
    'qrGenerator.loading': 'Loading...',
    'qrGenerator.loadError': 'Error loading profile data',
    'qrGenerator.cannotGenerate': 'Could not generate QR Code',
    'qrGenerator.shareDescription': 'Share this QR Code to collect contacts',
    'qrGenerator.directLink': 'Direct Link',
    'qrGenerator.downloadQr': 'Download QR',
    'qrGenerator.share': 'Share',
    'qrGenerator.linkCopied': 'Link copied!',
    'qrGenerator.linkCopiedDesc': 'The link has been copied to clipboard',
    'qrGenerator.howToUse': 'How to use:',
    'qrGenerator.instruction1': '1. Print or display this QR Code in your establishment',
    'qrGenerator.instruction2': '2. Customers scan the code with their phone camera',
    'qrGenerator.instruction3': '3. They fill out the contact form',
    'qrGenerator.instruction4': '4. You receive the data automatically in the system',

    // QR Generator

    // QR Generator
  },

  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.generateQr': 'Genera QR',
    'nav.dashboard': 'Dashboard',
    'nav.contacts': 'Contatti',
    'nav.campaigns': 'Campagne',
    'nav.templates': 'Template',
    'nav.analytics': 'Analytics',
    'nav.plans': 'Piani',
    'nav.login': 'Accedi',
    'nav.logout': 'Esci',

    // Auth
    'auth.hello': 'Ciao',
    'auth.loggedAs': 'Connesso come',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Panoramica del tuo ristorante',
    'dashboard.totalContacts': 'Contatti Totali',
    'dashboard.activeCampaigns': 'Campagne Attive',
    'dashboard.messagesSent': 'Messaggi Inviati',
    'dashboard.monthlyGrowth': 'Crescita Mensile',
    'dashboard.quickActions': 'Azioni Rapide',
    'dashboard.newCampaign': 'Nuova Campagna',
    'dashboard.newCampaignDesc': 'Crea una campagna marketing',
    'dashboard.manageContacts': 'Gestisci Contatti',
    'dashboard.manageContactsDesc': 'Visualizza e modifica i tuoi contatti',
    'dashboard.recentContacts': 'Contatti Recenti',
    'dashboard.noContactsYet': 'Nessun contatto ancora',
    'dashboard.recentCampaigns': 'Campagne Recenti',
    'dashboard.noCampaignsYet': 'Nessuna campagna ancora',

    // Campaign Status
    'campaign.status.draft': 'Bozza',
    'campaign.status.scheduled': 'Programmato',
    'campaign.status.sending': 'Invio in corso',
    'campaign.status.sent': 'Inviato',
    'campaign.status.completed': 'Completato',
    'campaign.status.failed': 'Fallito',
    'campaign.status.active': 'Attivo',

    // Footer
    'footer.description': 'Piattaforma completa di marketing per ristoranti con raccolta contatti e campagne automatizzate.',
    'footer.features': 'Funzionalità',
    'footer.contactCollection': 'Raccolta Contatti',
    'footer.automatedCampaigns': 'Campagne Automatizzate',
    'footer.referralProgram': 'Programma Referral',
    'footer.detailedAnalytics': 'Analisi Dettagliate',
    'footer.support': 'Supporto',
    'footer.documentation': 'Documentazione',
    'footer.contact': 'Contatto',
    'footer.faq': 'FAQ',
    'footer.onlineHelp': 'Aiuto Online',
    'footer.allRights': 'Tutti i diritti riservati.',

    // Contact Sources
    'contact.source.qr': 'Codice QR',
    'contact.source.manual': 'Manuale',
    'contact.source.import': 'Importazione',
    'contact.source.api': 'API',

    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Monitora le prestazioni delle tue campagne e contatti',
    'analytics.refresh': 'Aggiorna',
    'analytics.timeRange.7d': 'Ultimi 7 giorni',
    'analytics.timeRange.30d': 'Ultimi 30 giorni',
    'analytics.timeRange.90d': 'Ultimi 90 giorni',
    'analytics.timeRange.365d': 'Ultimo anno',
    'analytics.campaigns': 'Campagne',
    'analytics.sent': 'Inviate',
    'analytics.contacts': 'Contatti',
    'analytics.cost': 'Costo',
    'analytics.inPeriod': 'Nel periodo',
    'analytics.success': 'successo',
    'analytics.newContacts': 'Nuovi contatti',
    'analytics.sendTrend': 'Tendenza di Invio',
    'analytics.campaignTypes': 'Tipi di Campagna',
    'analytics.distributionByType': 'Distribuzione per tipo',
    'analytics.performanceMetrics': 'Metriche di Performance',
    'analytics.keySuccessIndicators': 'Indicatori chiave di successo',
    'analytics.deliveryRate': 'Tasso di Consegna',
    'analytics.costPerMessage': 'Costo per messaggio (€)',
    'analytics.messagesPerContact': 'Messaggi per contatto',
    'analytics.recentActivity': 'Attività Recente',
    'analytics.lastActions': 'Ultime azioni eseguite',
    'analytics.noRecentActivity': 'Nessuna attività recente',
    'analytics.sent.chart': 'Inviate',
    'analytics.delivered.chart': 'Consegnate',
    'analytics.campaign.label': 'Campagna',
    'analytics.contact.label': 'Contatto',
    'analytics.status.draft': 'Bozza',
    'analytics.status.scheduled': 'Programmato',
    'analytics.status.sending': 'Invio in corso',
    'analytics.status.completed': 'Completato',
    'analytics.status.failed': 'Fallito',
    'analytics.type.sms': 'SMS',
    'analytics.type.email': 'Email',
    'analytics.type.whatsapp': 'WhatsApp',
    'analytics.last7days': 'Ultimi 7 giorni',
    'analytics.last30days': 'Ultimi 30 giorni',
    'analytics.last90days': 'Ultimi 90 giorni',
    'analytics.lastYear': 'Ultimo anno',
    'analytics.totalCampaigns': 'Campagne Totali',
    'analytics.selectedPeriod': 'Nel periodo selezionato',
    'analytics.totalContacts': 'Contatti Totali',
    'analytics.newContactsAdded': 'Nuovi contatti aggiunti',
    'analytics.messagesSent': 'Messaggi Inviati',
    'analytics.successRate': 'Tasso di successo',
    'analytics.totalCost': 'Costo Totale',
    'analytics.campaignExpenses': 'Spese campagne',
    'analytics.sentVsDelivered': 'Inviate vs Consegnate',
    'analytics.campaignsByType': 'Campagne per Tipo',
    'analytics.typeDistribution': 'Distribuzione per tipo',
    'analytics.campaignStatus': 'Stato Campagne',
    'analytics.currentState': 'Stato attuale',
    'analytics.noActivity': 'Nessuna attività recente',
    'analytics.campaign': 'Campagna',
    'analytics.contact': 'Contatto',
    'analytics.performance': 'Performance',
    'analytics.detailedMetrics': 'Metriche dettagliate',
    'dashboard.analytics': 'Analytics',
    'dashboard.overview': 'Panoramica',
    'dashboard.overviewTitle': 'Panoramica',
    'dashboard.overviewSubtitle': 'Monitora le prestazioni della tua attività',
    'dashboard.scanQr': 'Scansiona QR',
    'dashboard.thisWeek': 'questa settimana',
    'dashboard.total': 'totale',
    'dashboard.conversionRate': 'Tasso di Conversione',
    'dashboard.last30Days': 'Ultimi 30 giorni',
    'dashboard.uniqueQr': 'QR Unico',
    'dashboard.yourAccessCode': 'Il tuo codice di accesso',
    'dashboard.recentCampaignsDesc': 'Le tue campagne più recenti',
    'dashboard.recentContactsDesc': 'Contatti aggiunti di recente',
    'dashboard.quickActionsDesc': 'Azioni rapide per gestire la tua attività',
    'dashboard.captureContact': 'Cattura Contatto',
    'dashboard.captureContactDesc': 'Scansiona QR code per aggiungere contatti',
    'dashboard.newCampaignAction': 'Nuova Campagna',

    // Campaign Status

    // QR Generator
    'qr.title': 'Genera QR Code',
    'qr.description': 'Crea un QR Code personalizzato per raccogliere contatti',
    'qr.configureForm': 'Configura Modulo',
    'qr.businessName': 'Nome Azienda',
    'qr.businessNamePlaceholder': 'Inserisci il nome della tua azienda',
    'qr.campaignType': 'Tipo di Campagna',
    'qr.promotionalTitle': 'Titolo Promozionale',
    'qr.promotionalTitlePlaceholder': 'Es: Ottieni il 10% di sconto!',
    'qr.promotionalMessage': 'Messaggio Promozionale',
    'qr.promotionalMessagePlaceholder': 'Descrivi la tua promozione...',
    'qr.thankYouMessage': 'Messaggio di Ringraziamento',
    'qr.thankYouMessagePlaceholder': 'Grazie! Ti contatteremo presto.',
    'qr.generateQR': 'Genera QR Code',
    'qr.downloadQR': 'Scarica QR Code',
    'qr.shareLink': 'Condividi Link',
    'qr.linkCopied': 'Link copiato negli appunti!',
    'qr.instructions': 'Incolla questo QR Code sui tuoi materiali promozionali (tavoli, volantini, ecc.) per raccogliere automaticamente i contatti.',
    'qr.loading': 'Generazione QR Code...',
    'qr.error': 'Errore nella generazione del QR Code',
    'qr.tryAgain': 'Riprova',
    'qr.campaignType.feedback': 'Feedback',
    'qr.campaignType.promotion': 'Promozione',
    'qr.campaignType.newsletter': 'Newsletter',
    'qr.campaignType.loyalty': 'Fedeltà',
    'qr.campaignType.event': 'Evento',

    // Home Page
    'home.innovative': 'Innovativo',
    'home.heroTitle': 'Trasforma il tuo Ristorante in una Macchina di Marketing',
    'home.heroSubtitle': 'Raccogli contatti automaticamente e invia campagne personalizzate per aumentare i ricavi fino al 40%',
    'home.tryNow': 'Prova Ora',
    'home.seeDemo': 'Vedi Demo',
    'home.openRate': 'Tasso di apertura',
    'home.revenueIncrease': 'Aumento dei ricavi',
    'home.quickSetup': 'Configurazione rapida',
    'home.support': 'Supporto',
    'home.featuresTitle': 'Funzionalità Potenti',
    'home.featuresSubtitle': 'Tutto ciò che serve per trasformare i visitatori in clienti fedeli',
    'home.features.qrCodeTitle': 'QR Code Intelligente',
    'home.features.qrCodeDesc': 'Genera QR code personalizzati per raccogliere contatti automaticamente',
    'home.features.smsTitle': 'Campagne SMS',
    'home.features.smsDesc': 'Invia messaggi mirati con alti tassi di conversione',
    'home.features.referralTitle': 'Programma Referral',
    'home.features.referralDesc': 'Trasforma i tuoi clienti in promotori del brand',
    'home.features.analyticsTitle': 'Analytics Avanzato',
    'home.features.analyticsDesc': 'Monitora metriche dettagliate delle tue campagne',
    'home.features.rewardsTitle': 'Sistema di Ricompense',
    'home.features.rewardsDesc': 'Fidelizza i clienti con offerte personalizzate',
    'home.features.targetingTitle': 'Targeting Intelligente',
    'home.features.targetingDesc': 'Raggiungi il pubblico giusto al momento giusto',
    'home.howItWorks': 'Come Funziona',
    'home.simpleSteps': 'Solo 3 Passaggi Semplici',
    'home.step1.title': 'Genera QR Code',
    'home.step1.desc': 'Configura la tua campagna e genera un QR code personalizzato',
    'home.step2.title': 'Raccogli Contatti',
    'home.step2.desc': 'I clienti scansionano e forniscono le loro informazioni',
    'home.step3.title': 'Invia Campagne',
    'home.step3.desc': 'Crea e invia campagne mirate automaticamente',
    'home.ctaTitle': 'Pronto ad Aumentare le Vendite?',
    'home.ctaSubtitle': 'Unisciti a centinaia di ristoranti che hanno già aumentato i ricavi',
    'home.testFree': 'Testa Gratuitamente',
    'home.scheduleDemo': 'Programma Demo',

    // Index Page
    'index.welcome': 'Benvenuto',
    'index.subtitle': 'Piattaforma marketing per ristoranti',

    // Contacts Page
    'contacts.title': 'Contatti',
    'contacts.subtitle': 'Gestisci la tua base clienti',
    'contacts.scanQr': 'Scansiona QR',
    'contacts.newContact': 'Nuovo Contatto',
    'contacts.stats.total': 'Totale',
    'contacts.stats.viaQr': 'Via QR Code',
    'contacts.stats.withEmail': 'Con Email',
    'contacts.stats.thisWeek': 'Questa Settimana',
    'contacts.search.placeholder': 'Cerca per nome, telefono o email...',
    'contacts.filter.allSources': 'Tutte le fonti',
    'contacts.filter.qrCode': 'QR Code',
    'contacts.filter.manual': 'Manuale',
    'contacts.filter.import': 'Importazione',
    'contacts.export': 'Esporta',
    'contacts.contactsCount': 'contatti',
    'contacts.noContactsFound': 'Nessun contatto trovato',
    'contacts.selectAll': 'Seleziona tutto',
    'contacts.unselectAll': 'Deseleziona tutto',
    'contacts.addedOn': 'Aggiunto il',
    'contacts.confirmDelete': 'Conferma eliminazione',
    'contacts.deleteConfirmMessage': 'Sei sicuro di voler eliminare il contatto',
    'contacts.deleteWarning': 'Questa azione non può essere annullata.',
    'contacts.cancel': 'Annulla',
    'contacts.delete': 'Elimina',
    'contacts.noContactsFoundMessage': 'Nessun contatto trovato',
    'contacts.adjustFilters': 'Prova ad aggiustare i filtri o i termini di ricerca',
    'contacts.getStarted': 'Inizia scansionando QR code o aggiungendo contatti manualmente',
    'contacts.scanQrCode': 'Scansiona QR Code',
    'contacts.addContact': 'Aggiungi Contatto',

    // Campaigns Page
    'campaigns.title': 'Campagne',
    'campaigns.subtitle': 'Crea e gestisci le tue campagne marketing',
    'campaigns.newCampaign': 'Nuova Campagna',
    'campaigns.createNew': 'Crea Nuova Campagna',
    'campaigns.configurePromo': 'Configura la tua campagna promozionale',
    'campaigns.useTemplate': 'Usa un template (opzionale)',
    'campaigns.chooseTemplate': 'Scegli un template esistente',
    'campaigns.createFromScratch': 'Crea da zero',
    'campaigns.templateSelected': 'Template selezionato. Puoi modificare il messaggio sotto.',
    'campaigns.campaignName': 'Nome della campagna',
    'campaigns.campaignNamePlaceholder': 'Es: Boost Lunedì',
    'campaigns.campaignType': 'Tipo di campagna',
    'campaigns.selectType': 'Seleziona un tipo',
    'campaigns.templateVariables': 'Variabili del template',
    'campaigns.variableValue': 'Valore per',
    'campaigns.variablesReplaced': 'Queste variabili saranno sostituite nel messaggio finale.',
    'campaigns.promoMessage': 'Messaggio promozionale',
    'campaigns.promoPlaceholder': 'Scrivi il tuo messaggio promozionale...',
    'campaigns.charactersForSms': 'caratteri per SMS',
    'campaigns.previewWithVariables': 'Anteprima con variabili applicate sotto',
    'campaigns.finalMessagePreview': 'Anteprima messaggio finale:',
    'campaigns.sendDateTime': 'Data e ora di invio (opzionale)',
    'campaigns.leaveEmptyImmediate': 'Lascia vuoto per inviare immediatamente',
    'campaigns.sendingViaTwilio': 'Invio via Twilio',
    'campaigns.twilioConfigured': 'Configurazione Twilio già configurata',
    'campaigns.messagesWillBeSent': 'Messaggi',
    'campaigns.sentDirectly': 'saranno inviati direttamente',
    'campaigns.twilioApiConfigured': 'API Twilio configurata nei secrets',
    'campaigns.creating': 'Creando...',
    'campaigns.createCampaign': 'Crea campagna',
    'campaigns.cancel': 'Annulla',
    'campaigns.myCampaigns': 'Le mie campagne',
    'campaigns.manageAndTrack': 'Gestisci e monitora le tue campagne marketing',
    'campaigns.noCampaigns': 'Nessuna campagna',
    'campaigns.createFirstCampaign': 'Crea la tua prima campagna per iniziare a coinvolgere i tuoi clienti.',
    'campaigns.createACampaign': 'Crea una campagna',
    'campaigns.status.active': 'Attivo',
    'campaigns.status.sent': 'Inviato',
    'campaigns.status.scheduled': 'Programmato',
    'campaigns.status.draft': 'Bozza',
    'campaigns.scheduledFor': 'Programmato per',
    'campaigns.send': 'Invia',
    'campaigns.totalSent': 'Totale inviati',
    'campaigns.success': 'Successo',
    'campaigns.failures': 'Fallimenti',
    'campaigns.sentOn': 'Inviato il',
    'campaigns.error': 'Errore',
    'campaigns.fillRequiredFields': 'Compila tutti i campi obbligatori',
    'campaigns.campaignCreated': 'Campagna creata con successo',
    'campaigns.campaignSent': 'Campagna inviata con successo',
    'campaigns.cannotCreate': 'Impossibile creare la campagna',
    'campaigns.cannotSend': 'Impossibile inviare la campagna',
    'campaigns.campaignDeleted': 'Campagna eliminata con successo',
    'campaigns.cannotDelete': 'Impossibile eliminare la campagna',
    
    // Campaign Stats
    'campaigns.stats.activeCampaigns': 'Campagne Attive',
    'campaigns.stats.messagesSent': 'Messaggi Inviati',
    'campaigns.stats.successRate': 'Tasso di Successo',
    'campaigns.stats.totalCampaigns': 'Totale Campagne',

    // QR Form Errors

    // QR Form Errors

    // QR Form Errors
    'qrForm.errorTitle': 'Errore',

    // QR Form

    // QR Form
    'qrForm.title': 'Scansione QR',
    'qrForm.subtitle': 'Scansiona QR code e aggiungi contatti automaticamente',
    'qrForm.cameraScanner': 'Scanner Fotocamera',
    'qrForm.contactData': 'Dati Contatto',
    'qrForm.scanToFill': 'Scansiona un QR code per riempire automaticamente',
    'qrForm.clickToStart': 'Clicca per iniziare',
    'qrForm.startScanner': 'Avvia Scanner',
    'qrForm.stopScanner': 'Ferma Scanner',
    'qrForm.permissionDenied': 'Permesso fotocamera negato',
    'qrForm.pointToQR': 'Punta verso il QR code',
    'qrForm.positionQR': 'Posiziona il QR code nell\'area evidenziata',
    'qrForm.contactDataFilled': 'I dati di contatto saranno riempiti automaticamente',
    'qrForm.otherQRSaved': 'Altri QR code saranno salvati nelle note',
    'qrForm.qrScanned': 'QR Code Scansionato',
    'qrForm.fillDataBelow': 'Compila o modifica i dati sotto',
    'qrForm.qrDetected': 'QR Code rilevato:',
    'qrForm.requiredFields': 'Campi obbligatori',
    'qrForm.namePhoneRequired': 'Nome e telefono sono obbligatori',
    'qrForm.contactAdded': 'Contatto aggiunto!',
    'qrForm.contactAddedToList': 'è stato aggiunto alla tua lista contatti',
    'qrForm.nameRequired': 'Nome (obbligatorio)',
    'qrForm.customerName': 'Nome cliente',
    'qrForm.phone': 'Telefono',
    'qrForm.email': 'Email',
    'qrForm.tags': 'Tag',
    'qrForm.addTag': 'Aggiungi tag',
    'qrForm.notes': 'Note',
    'qrForm.customerNotes': 'Note sul cliente',
    'qrForm.saving': 'Salvando...',
    'qrForm.saveContact': 'Salva Contatto',
    'qrForm.reset': 'Ripristina',
    'qrForm.scanningTips': 'Consigli di Scansione',
    'qrForm.goodLighting': 'Buona Illuminazione',
    'qrForm.useWellLit': 'Usa ambienti ben illuminati',
    'qrForm.adequateDistance': 'Distanza Adeguata',
    'qrForm.maintain10to30cm': 'Mantieni 10-30cm di distanza',
    'qrForm.cleanQR': 'QR Code Pulito',
    'qrForm.ensureReadable': 'Assicurati che sia leggibile',

    // QR Generator  
    'qrGenerator.loading': 'Caricamento...',
    'qrGenerator.loadError': 'Errore nel caricamento dei dati del profilo',
    'qrGenerator.cannotGenerate': 'Impossibile generare il QR Code',
    'qrGenerator.shareDescription': 'Condividi questo QR Code per raccogliere contatti',
    'qrGenerator.directLink': 'Link Diretto',
    'qrGenerator.downloadQr': 'Scarica QR',
    'qrGenerator.share': 'Condividi',
    'qrGenerator.linkCopied': 'Link copiato!',
    'qrGenerator.linkCopiedDesc': 'Il link è stato copiato negli appunti',
    'qrGenerator.howToUse': 'Come usare:',
    'qrGenerator.instruction1': '1. Stampa o mostra questo QR Code nel tuo locale',
    'qrGenerator.instruction2': '2. I clienti scansionano il codice con la fotocamera del telefono',
    'qrGenerator.instruction3': '3. Compilano il modulo di contatto',
    'qrGenerator.instruction4': '4. Ricevi i dati automaticamente nel sistema',

    // QR Generator

    // QR Generator
  },

  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.generateQr': 'QR Generieren',
    'nav.dashboard': 'Dashboard',
    'nav.contacts': 'Kontakte',
    'nav.campaigns': 'Kampagnen',
    'nav.templates': 'Vorlagen',
    'nav.analytics': 'Analytics',
    'nav.plans': 'Pläne',
    'nav.login': 'Anmelden',
    'nav.logout': 'Abmelden',

    // Auth
    'auth.hello': 'Hallo',
    'auth.loggedAs': 'Angemeldet als',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Übersicht Ihres Restaurants',
    'dashboard.totalContacts': 'Kontakte Gesamt',
    'dashboard.activeCampaigns': 'Aktive Kampagnen',
    'dashboard.messagesSent': 'Nachrichten Gesendet',
    'dashboard.monthlyGrowth': 'Monatliches Wachstum',
    'dashboard.quickActions': 'Schnellaktionen',
    'dashboard.newCampaign': 'Neue Kampagne',
    'dashboard.newCampaignDesc': 'Marketing-Kampagne erstellen',
    'dashboard.manageContacts': 'Kontakte Verwalten',
    'dashboard.manageContactsDesc': 'Kontakte anzeigen und bearbeiten',
    'dashboard.recentContacts': 'Neueste Kontakte',
    'dashboard.noContactsYet': 'Noch keine Kontakte',
    'dashboard.recentCampaigns': 'Neueste Kampagnen',
    'dashboard.noCampaignsYet': 'Noch keine Kampagnen',

    // Campaign Status
    'campaign.status.draft': 'Entwurf',
    'campaign.status.scheduled': 'Geplant',
    'campaign.status.sending': 'Wird gesendet',
    'campaign.status.sent': 'Gesendet',
    'campaign.status.completed': 'Abgeschlossen',
    'campaign.status.failed': 'Fehlgeschlagen',
    'campaign.status.active': 'Aktiv',

    // Footer
    'footer.description': 'Vollständige Marketing-Plattform für Restaurants mit Kontaktsammlung und automatisierten Kampagnen.',
    'footer.features': 'Funktionen',
    'footer.contactCollection': 'Kontaktsammlung',
    'footer.automatedCampaigns': 'Automatisierte Kampagnen',
    'footer.referralProgram': 'Empfehlungsprogramm',
    'footer.detailedAnalytics': 'Detaillierte Analysen',
    'footer.support': 'Support',
    'footer.documentation': 'Dokumentation',
    'footer.contact': 'Kontakt',
    'footer.faq': 'FAQ',
    'footer.onlineHelp': 'Online-Hilfe',
    'footer.allRights': 'Alle Rechte vorbehalten.',

    // Contact Sources
    'contact.source.qr': 'QR-Code',
    'contact.source.manual': 'Manuell',
    'contact.source.import': 'Import',
    'contact.source.api': 'API',

    // Analytics
    'analytics.title': 'Analytics',
    'analytics.subtitle': 'Verfolgen Sie die Leistung Ihrer Kampagnen und Kontakte',
    'analytics.refresh': 'Aktualisieren',
    'analytics.timeRange.7d': 'Letzte 7 Tage',
    'analytics.timeRange.30d': 'Letzte 30 Tage',
    'analytics.timeRange.90d': 'Letzte 90 Tage',
    'analytics.timeRange.365d': 'Letztes Jahr',
    'analytics.campaigns': 'Kampagnen',
    'analytics.sent': 'Gesendet',
    'analytics.contacts': 'Kontakte',
    'analytics.cost': 'Kosten',
    'analytics.inPeriod': 'Im Zeitraum',
    'analytics.success': 'Erfolg',
    'analytics.newContacts': 'Neue Kontakte',
    'analytics.sendTrend': 'Sendungstrend',
    'analytics.campaignTypes': 'Kampagnentypen',
    'analytics.distributionByType': 'Verteilung nach Typ',
    'analytics.performanceMetrics': 'Leistungsmetriken',
    'analytics.keySuccessIndicators': 'Wichtige Erfolgsindikatoren',
    'analytics.deliveryRate': 'Zustellrate',
    'analytics.costPerMessage': 'Kosten pro Nachricht (€)',
    'analytics.messagesPerContact': 'Nachrichten pro Kontakt',
    'analytics.recentActivity': 'Neueste Aktivitäten',
    'analytics.lastActions': 'Letzte durchgeführte Aktionen',
    'analytics.noRecentActivity': 'Keine neuesten Aktivitäten',
    'analytics.sent.chart': 'Gesendet',
    'analytics.delivered.chart': 'Zugestellt',
    'analytics.campaign.label': 'Kampagne',
    'analytics.contact.label': 'Kontakt',
    'analytics.status.draft': 'Entwurf',
    'analytics.status.scheduled': 'Geplant',
    'analytics.status.sending': 'Wird gesendet',
    'analytics.status.completed': 'Abgeschlossen',
    'analytics.status.failed': 'Fehlgeschlagen',
    'analytics.type.sms': 'SMS',
    'analytics.type.email': 'E-Mail',
    'analytics.type.whatsapp': 'WhatsApp',
    'analytics.last7days': 'Letzte 7 Tage',
    'analytics.last30days': 'Letzte 30 Tage',
    'analytics.last90days': 'Letzte 90 Tage',
    'analytics.lastYear': 'Letztes Jahr',
    'analytics.totalCampaigns': 'Kampagnen Gesamt',
    'analytics.selectedPeriod': 'Im ausgewählten Zeitraum',
    'analytics.totalContacts': 'Kontakte Gesamt',
    'analytics.newContactsAdded': 'Neue Kontakte hinzugefügt',
    'analytics.messagesSent': 'Nachrichten Gesendet',
    'analytics.successRate': 'Erfolgsrate',
    'analytics.totalCost': 'Gesamtkosten',
    'analytics.campaignExpenses': 'Kampagnenausgaben',
    'analytics.sentVsDelivered': 'Gesendet vs Zugestellt',
    'analytics.campaignsByType': 'Kampagnen nach Typ',
    'analytics.typeDistribution': 'Verteilung nach Typ',
    'analytics.campaignStatus': 'Kampagnenstatus',
    'analytics.currentState': 'Aktueller Zustand',
    'analytics.noActivity': 'Keine neueste Aktivität',
    'analytics.campaign': 'Kampagne',
    'analytics.contact': 'Kontakt',
    'analytics.performance': 'Leistung',
    'analytics.detailedMetrics': 'Detaillierte Metriken',
    'dashboard.analytics': 'Analytics',
    'dashboard.overview': 'Übersicht',
    'dashboard.overviewTitle': 'Übersicht',
    'dashboard.overviewSubtitle': 'Verfolgen Sie Ihre Geschäftsleistung',
    'dashboard.scanQr': 'QR Scannen',
    'dashboard.thisWeek': 'diese Woche',
    'dashboard.total': 'gesamt',
    'dashboard.conversionRate': 'Konversionsrate',
    'dashboard.last30Days': 'Letzte 30 Tage',
    'dashboard.uniqueQr': 'Einzigartiger QR',
    'dashboard.yourAccessCode': 'Ihr Zugangscode',
    'dashboard.recentCampaignsDesc': 'Ihre neuesten Kampagnen',
    'dashboard.recentContactsDesc': 'Kürzlich hinzugefügte Kontakte',
    'dashboard.quickActionsDesc': 'Schnelle Aktionen zur Verwaltung Ihres Geschäfts',
    'dashboard.captureContact': 'Kontakt Erfassen',
    'dashboard.captureContactDesc': 'QR-Codes scannen um Kontakte hinzuzufügen',
    'dashboard.newCampaignAction': 'Neue Kampagne',

    // Campaign Status

    // QR Generator
    'qr.title': 'QR-Code Generieren',
    'qr.description': 'Erstellen Sie einen benutzerdefinierten QR-Code zum Sammeln von Kontakten',
    'qr.configureForm': 'Formular Konfigurieren',
    'qr.businessName': 'Firmenname',
    'qr.businessNamePlaceholder': 'Geben Sie Ihren Firmennamen ein',
    'qr.campaignType': 'Kampagnentyp',
    'qr.promotionalTitle': 'Werbetitel',
    'qr.promotionalTitlePlaceholder': 'Z.B.: 10% Rabatt erhalten!',
    'qr.promotionalMessage': 'Werbebotschaft',
    'qr.promotionalMessagePlaceholder': 'Beschreiben Sie Ihre Aktion...',
    'qr.thankYouMessage': 'Dankesnachricht',
    'qr.thankYouMessagePlaceholder': 'Danke! Wir werden Sie bald kontaktieren.',
    'qr.generateQR': 'QR-Code Generieren',
    'qr.downloadQR': 'QR-Code Herunterladen',
    'qr.shareLink': 'Link Teilen',
    'qr.linkCopied': 'Link in die Zwischenablage kopiert!',
    'qr.instructions': 'Fügen Sie diesen QR-Code auf Ihre Werbematerialien (Tische, Flyer, etc.) ein, um automatisch Kontakte zu sammeln.',
    'qr.loading': 'QR-Code wird generiert...',
    'qr.error': 'Fehler beim Generieren des QR-Codes',
    'qr.tryAgain': 'Erneut versuchen',
    'qr.campaignType.feedback': 'Feedback',
    'qr.campaignType.promotion': 'Aktion',
    'qr.campaignType.newsletter': 'Newsletter',
    'qr.campaignType.loyalty': 'Treue',
    'qr.campaignType.event': 'Veranstaltung',

    // Home Page
    'home.innovative': 'Innovativ',
    'home.heroTitle': 'Verwandeln Sie Ihr Restaurant in eine Marketing-Maschine',
    'home.heroSubtitle': 'Sammeln Sie automatisch Kontakte und senden Sie personalisierte Kampagnen, um Ihren Umsatz um bis zu 40% zu steigern',
    'home.tryNow': 'Jetzt Testen',
    'home.seeDemo': 'Demo Ansehen',
    'home.openRate': 'Öffnungsrate',
    'home.revenueIncrease': 'Umsatzsteigerung',
    'home.quickSetup': 'Schnelle Einrichtung',
    'home.support': 'Support',
    'home.featuresTitle': 'Leistungsstarke Funktionen',
    'home.featuresSubtitle': 'Alles was Sie brauchen, um Besucher in treue Kunden zu verwandeln',
    'home.features.qrCodeTitle': 'Intelligenter QR-Code',
    'home.features.qrCodeDesc': 'Generieren Sie benutzerdefinierte QR-Codes zum automatischen Sammeln von Kontakten',
    'home.features.smsTitle': 'SMS-Kampagnen',
    'home.features.smsDesc': 'Senden Sie gezielte Nachrichten mit hohen Konversionsraten',
    'home.features.referralTitle': 'Empfehlungsprogramm',
    'home.features.referralDesc': 'Verwandeln Sie Ihre Kunden in Markenbotschafter',
    'home.features.analyticsTitle': 'Erweiterte Analytics',
    'home.features.analyticsDesc': 'Verfolgen Sie detaillierte Metriken Ihrer Kampagnen',
    'home.features.rewardsTitle': 'Belohnungssystem',
    'home.features.rewardsDesc': 'Halten Sie Kunden mit personalisierten Angeboten',
    'home.features.targetingTitle': 'Intelligentes Targeting',
    'home.features.targetingDesc': 'Erreichen Sie die richtige Zielgruppe zur richtigen Zeit',
    'home.howItWorks': 'Wie es Funktioniert',
    'home.simpleSteps': 'Nur 3 Einfache Schritte',
    'home.step1.title': 'QR-Code Generieren',
    'home.step1.desc': 'Richten Sie Ihre Kampagne ein und generieren Sie einen benutzerdefinierten QR-Code',
    'home.step2.title': 'Kontakte Sammeln',
    'home.step2.desc': 'Kunden scannen und geben ihre Informationen an',
    'home.step3.title': 'Kampagnen Senden',
    'home.step3.desc': 'Erstellen und senden Sie automatisch gezielte Kampagnen',
    'home.ctaTitle': 'Bereit Ihre Verkäufe zu Steigern?',
    'home.ctaSubtitle': 'Schließen Sie sich Hunderten von Restaurants an, die bereits ihren Umsatz gesteigert haben',
    'home.testFree': 'Kostenlos Testen',
    'home.scheduleDemo': 'Demo Planen',

    // Index Page
    'index.welcome': 'Willkommen',
    'index.subtitle': 'Marketing-Plattform für Restaurants',

    // Contacts Page
    'contacts.title': 'Kontakte',
    'contacts.subtitle': 'Verwalten Sie Ihren Kundenstamm',
    'contacts.scanQr': 'QR Scannen',
    'contacts.newContact': 'Neuer Kontakt',
    'contacts.stats.total': 'Gesamt',
    'contacts.stats.viaQr': 'Via QR Code',
    'contacts.stats.withEmail': 'Mit E-Mail',
    'contacts.stats.thisWeek': 'Diese Woche',
    'contacts.search.placeholder': 'Suche nach Name, Telefon oder E-Mail...',
    'contacts.filter.allSources': 'Alle Quellen',
    'contacts.filter.qrCode': 'QR Code',
    'contacts.filter.manual': 'Manuell',
    'contacts.filter.import': 'Import',
    'contacts.export': 'Exportieren',
    'contacts.contactsCount': 'Kontakte',
    'contacts.noContactsFound': 'Keine Kontakte gefunden',
    'contacts.selectAll': 'Alle auswählen',
    'contacts.unselectAll': 'Alle abwählen',
    'contacts.addedOn': 'Hinzugefügt am',
    'contacts.confirmDelete': 'Löschung bestätigen',
    'contacts.deleteConfirmMessage': 'Sind Sie sicher, dass Sie den Kontakt löschen möchten',
    'contacts.deleteWarning': 'Diese Aktion kann nicht rückgängig gemacht werden.',
    'contacts.cancel': 'Abbrechen',
    'contacts.delete': 'Löschen',
    'contacts.noContactsFoundMessage': 'Keine Kontakte gefunden',
    'contacts.adjustFilters': 'Versuchen Sie, Filter oder Suchbegriffe anzupassen',
    'contacts.getStarted': 'Beginnen Sie mit dem Scannen von QR-Codes oder fügen Sie manuell Kontakte hinzu',
    'contacts.scanQrCode': 'QR Code Scannen',
    'contacts.addContact': 'Kontakt Hinzufügen',

    // Campaigns Page
    'campaigns.title': 'Kampagnen',
    'campaigns.subtitle': 'Erstellen und verwalten Sie Ihre Marketing-Kampagnen',
    'campaigns.newCampaign': 'Neue Kampagne',
    'campaigns.createNew': 'Neue Kampagne Erstellen',
    'campaigns.configurePromo': 'Konfigurieren Sie Ihre Werbekampagne',
    'campaigns.useTemplate': 'Template verwenden (optional)',
    'campaigns.chooseTemplate': 'Vorhandenes Template wählen',
    'campaigns.createFromScratch': 'Von Grund auf erstellen',
    'campaigns.templateSelected': 'Template ausgewählt. Sie können die Nachricht unten bearbeiten.',
    'campaigns.campaignName': 'Kampagnenname',
    'campaigns.campaignNamePlaceholder': 'Bsp: Montag Boost',
    'campaigns.campaignType': 'Kampagnentyp',
    'campaigns.selectType': 'Typ auswählen',
    'campaigns.templateVariables': 'Template-Variablen',
    'campaigns.variableValue': 'Wert für',
    'campaigns.variablesReplaced': 'Diese Variablen werden in der finalen Nachricht ersetzt.',
    'campaigns.promoMessage': 'Werbenachricht',
    'campaigns.promoPlaceholder': 'Schreiben Sie Ihre Werbenachricht...',
    'campaigns.charactersForSms': 'Zeichen für SMS',
    'campaigns.previewWithVariables': 'Vorschau mit angewendeten Variablen unten',
    'campaigns.finalMessagePreview': 'Finale Nachrichtenvorschau:',
    'campaigns.sendDateTime': 'Sendedatum und -zeit (optional)',
    'campaigns.leaveEmptyImmediate': 'Leer lassen für sofortiges Senden',
    'campaigns.sendingViaTwilio': 'Senden über Twilio',
    'campaigns.twilioConfigured': 'Twilio-Konfiguration bereits konfiguriert',
    'campaigns.messagesWillBeSent': 'Nachrichten',
    'campaigns.sentDirectly': 'werden direkt gesendet',
    'campaigns.twilioApiConfigured': 'Twilio API in Geheimnissen konfiguriert',
    'campaigns.creating': 'Erstellen...',
    'campaigns.createCampaign': 'Kampagne erstellen',
    'campaigns.cancel': 'Abbrechen',
    'campaigns.myCampaigns': 'Meine Kampagnen',
    'campaigns.manageAndTrack': 'Verwalten und verfolgen Sie Ihre Marketing-Kampagnen',
    'campaigns.noCampaigns': 'Keine Kampagnen',
    'campaigns.createFirstCampaign': 'Erstellen Sie Ihre erste Kampagne, um Ihre Kunden zu engagieren.',
    'campaigns.createACampaign': 'Kampagne erstellen',
    'campaigns.status.active': 'Aktiv',
    'campaigns.status.sent': 'Gesendet',
    'campaigns.status.scheduled': 'Geplant',
    'campaigns.status.draft': 'Entwurf',
    'campaigns.scheduledFor': 'Geplant für',
    'campaigns.send': 'Senden',
    'campaigns.totalSent': 'Gesamt gesendet',
    'campaigns.success': 'Erfolg',
    'campaigns.failures': 'Fehler',
    'campaigns.sentOn': 'Gesendet am',
    'campaigns.error': 'Fehler',
    'campaigns.fillRequiredFields': 'Bitte füllen Sie alle Pflichtfelder aus',
    'campaigns.campaignCreated': 'Kampagne erfolgreich erstellt',
    'campaigns.campaignSent': 'Kampagne erfolgreich gesendet',
    'campaigns.cannotCreate': 'Kampagne kann nicht erstellt werden',
    'campaigns.cannotSend': 'Kampagne kann nicht gesendet werden',
    'campaigns.campaignDeleted': 'Kampagne erfolgreich gelöscht',
    'campaigns.cannotDelete': 'Kampagne kann nicht gelöscht werden',
    
    // Campaign Stats
    'campaigns.stats.activeCampaigns': 'Aktive Kampagnen',
    'campaigns.stats.messagesSent': 'Gesendete Nachrichten',
    'campaigns.stats.successRate': 'Erfolgsrate',
    'campaigns.stats.totalCampaigns': 'Gesamte Kampagnen',

    // QR Form Errors

    // QR Form Errors

    // QR Form Errors
    'qrForm.errorTitle': 'Fehler',

    // QR Form

    // QR Form
    'qrForm.title': 'QR-Scan',
    'qrForm.subtitle': 'QR-Codes scannen und Kontakte automatisch hinzufügen',
    'qrForm.cameraScanner': 'Kamera-Scanner',
    'qrForm.contactData': 'Kontaktdaten',
    'qrForm.scanToFill': 'QR-Code scannen zum automatischen Ausfüllen',
    'qrForm.clickToStart': 'Klicken zum Starten',
    'qrForm.startScanner': 'Scanner Starten',
    'qrForm.stopScanner': 'Scanner Stoppen',
    'qrForm.permissionDenied': 'Kamera-Berechtigung verweigert',
    'qrForm.pointToQR': 'Auf QR-Code richten',
    'qrForm.positionQR': 'QR-Code im hervorgehobenen Bereich positionieren',
    'qrForm.contactDataFilled': 'Kontaktdaten werden automatisch ausgefüllt',
    'qrForm.otherQRSaved': 'Andere QR-Codes werden in Notizen gespeichert',
    'qrForm.qrScanned': 'QR-Code Gescannt',
    'qrForm.fillDataBelow': 'Füllen oder bearbeiten Sie die Daten unten',
    'qrForm.qrDetected': 'QR-Code erkannt:',
    'qrForm.requiredFields': 'Pflichtfelder',
    'qrForm.namePhoneRequired': 'Name und Telefon sind erforderlich',
    'qrForm.contactAdded': 'Kontakt hinzugefügt!',
    'qrForm.contactAddedToList': 'wurde zu Ihrer Kontaktliste hinzugefügt',
    'qrForm.nameRequired': 'Name (erforderlich)',
    'qrForm.customerName': 'Kundenname',
    'qrForm.phone': 'Telefon',
    'qrForm.email': 'E-Mail',
    'qrForm.tags': 'Tags',
    'qrForm.addTag': 'Tag hinzufügen',
    'qrForm.notes': 'Notizen',
    'qrForm.customerNotes': 'Kundennotizen',
    'qrForm.saving': 'Speichern...',
    'qrForm.saveContact': 'Kontakt Speichern',
    'qrForm.reset': 'Zurücksetzen',
    'qrForm.scanningTips': 'Scan-Tipps',
    'qrForm.goodLighting': 'Gute Beleuchtung',
    'qrForm.useWellLit': 'Gut beleuchtete Umgebungen verwenden',
    'qrForm.adequateDistance': 'Angemessene Entfernung',
    'qrForm.maintain10to30cm': '10-30cm Abstand halten',
    'qrForm.cleanQR': 'Sauberer QR-Code',
    'qrForm.ensureReadable': 'Stellen Sie sicher, dass er lesbar ist',

    // QR Generator  
    'qrGenerator.loading': 'Laden...',
    'qrGenerator.loadError': 'Fehler beim Laden der Profildaten',
    'qrGenerator.cannotGenerate': 'QR-Code konnte nicht generiert werden',
    'qrGenerator.shareDescription': 'Teilen Sie diesen QR-Code um Kontakte zu sammeln',
    'qrGenerator.directLink': 'Direkter Link',
    'qrGenerator.downloadQr': 'QR Herunterladen',
    'qrGenerator.share': 'Teilen',
    'qrGenerator.linkCopied': 'Link kopiert!',
    'qrGenerator.linkCopiedDesc': 'Der Link wurde in die Zwischenablage kopiert',
    'qrGenerator.howToUse': 'So verwenden:',
    'qrGenerator.instruction1': '1. Drucken oder zeigen Sie diesen QR-Code in Ihrem Betrieb',
    'qrGenerator.instruction2': '2. Kunden scannen den Code mit ihrer Telefonkamera',
    'qrGenerator.instruction3': '3. Sie füllen das Kontaktformular aus',
    'qrGenerator.instruction4': '4. Sie erhalten die Daten automatisch im System',

    // QR Generator

    // QR Generator
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'pt';
  });

  const handleLanguageChange = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider 
      value={{ 
        language, 
        setLanguage: handleLanguageChange, 
        t 
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}