// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibgqldtapyyzntwylots.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliZ3FsZHRhcHl5em50d3lsb3RzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTQ1NjksImV4cCI6MjA2ODMzMDU2OX0.b0-dRNmEhMtNntGoRCBfP2lux1uR8DZCoSUmcTuOUiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});